// Autogenerated from Pigeon. Do not edit by hand.
// Source: pigeons/image_playground_api.dart
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum ImageKindMessage { file, encoded, pixels }

enum ConceptKindMessage { text, extracted, image, drawing }

enum StyleMessage {
  animation,
  illustration,
  sketch,
  emoji,
  externalProvider,
  any,
}

enum PersonalizationMessage { automatic, enabled, disabled }

enum VarietyMessage { automatic, high, low }

enum StrategyMessage { automatic, editExisting, generateNew }

class ImageInputMessage {
  ImageInputMessage({
    required this.kind,
    this.path,
    this.bytes,
    this.width,
    this.height,
    this.bytesPerRow,
  });

  ImageKindMessage kind;

  String? path;

  Uint8List? bytes;

  int? width;

  int? height;

  int? bytesPerRow;

  List<Object?> _toList() {
    return <Object?>[kind, path, bytes, width, height, bytesPerRow];
  }

  Object encode() {
    return _toList();
  }

  static ImageInputMessage decode(Object result) {
    result as List<Object?>;
    return ImageInputMessage(
      kind: result[0]! as ImageKindMessage,
      path: result[1] as String?,
      bytes: result[2] as Uint8List?,
      width: result[3] as int?,
      height: result[4] as int?,
      bytesPerRow: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ImageInputMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(path, other.path) &&
        _deepEquals(bytes, other.bytes) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(bytesPerRow, other.bytesPerRow);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ImageInputMessage(kind: $kind, path: $path, bytes: $bytes, width: $width, height: $height, bytesPerRow: $bytesPerRow)';
  }
}

class ConceptMessage {
  ConceptMessage({
    required this.kind,
    this.text,
    this.title,
    this.image,
    this.drawing,
  });

  ConceptKindMessage kind;

  String? text;

  String? title;

  ImageInputMessage? image;

  Uint8List? drawing;

  List<Object?> _toList() {
    return <Object?>[kind, text, title, image, drawing];
  }

  Object encode() {
    return _toList();
  }

  static ConceptMessage decode(Object result) {
    result as List<Object?>;
    return ConceptMessage(
      kind: result[0]! as ConceptKindMessage,
      text: result[1] as String?,
      title: result[2] as String?,
      image: result[3] as ImageInputMessage?,
      drawing: result[4] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConceptMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(text, other.text) &&
        _deepEquals(title, other.title) &&
        _deepEquals(image, other.image) &&
        _deepEquals(drawing, other.drawing);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConceptMessage(kind: $kind, text: $text, title: $title, image: $image, drawing: $drawing)';
  }
}

class OptionsMessage {
  OptionsMessage({
    this.personalization,
    this.variety,
    this.strategy,
    this.width,
    this.height,
  });

  PersonalizationMessage? personalization;

  VarietyMessage? variety;

  StrategyMessage? strategy;

  double? width;

  double? height;

  List<Object?> _toList() {
    return <Object?>[personalization, variety, strategy, width, height];
  }

  Object encode() {
    return _toList();
  }

  static OptionsMessage decode(Object result) {
    result as List<Object?>;
    return OptionsMessage(
      personalization: result[0] as PersonalizationMessage?,
      variety: result[1] as VarietyMessage?,
      strategy: result[2] as StrategyMessage?,
      width: result[3] as double?,
      height: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(personalization, other.personalization) &&
        _deepEquals(variety, other.variety) &&
        _deepEquals(strategy, other.strategy) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OptionsMessage(personalization: $personalization, variety: $variety, strategy: $strategy, width: $width, height: $height)';
  }
}

class ConfigurationMessage {
  ConfigurationMessage({
    required this.concepts,
    this.sourceImage,
    this.allowedStyles,
    this.selectedStyle,
    this.options,
  });

  List<ConceptMessage> concepts;

  ImageInputMessage? sourceImage;

  List<StyleMessage>? allowedStyles;

  StyleMessage? selectedStyle;

  OptionsMessage? options;

  List<Object?> _toList() {
    return <Object?>[
      concepts,
      sourceImage,
      allowedStyles,
      selectedStyle,
      options,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ConfigurationMessage decode(Object result) {
    result as List<Object?>;
    return ConfigurationMessage(
      concepts: (result[0]! as List<Object?>).cast<ConceptMessage>(),
      sourceImage: result[1] as ImageInputMessage?,
      allowedStyles: (result[2] as List<Object?>?)?.cast<StyleMessage>(),
      selectedStyle: result[3] as StyleMessage?,
      options: result[4] as OptionsMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConfigurationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(concepts, other.concepts) &&
        _deepEquals(sourceImage, other.sourceImage) &&
        _deepEquals(allowedStyles, other.allowedStyles) &&
        _deepEquals(selectedStyle, other.selectedStyle) &&
        _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConfigurationMessage(concepts: $concepts, sourceImage: $sourceImage, allowedStyles: $allowedStyles, selectedStyle: $selectedStyle, options: $options)';
  }
}

class CapabilitiesMessage {
  CapabilitiesMessage({
    required this.isSupported,
    required this.isAvailable,
    required this.supportsStyles,
    required this.supportsOptions,
    required this.supportsVersion27Options,
    required this.styles,
  });

  bool isSupported;

  bool isAvailable;

  bool supportsStyles;

  bool supportsOptions;

  bool supportsVersion27Options;

  List<StyleMessage> styles;

  List<Object?> _toList() {
    return <Object?>[
      isSupported,
      isAvailable,
      supportsStyles,
      supportsOptions,
      supportsVersion27Options,
      styles,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CapabilitiesMessage decode(Object result) {
    result as List<Object?>;
    return CapabilitiesMessage(
      isSupported: result[0]! as bool,
      isAvailable: result[1]! as bool,
      supportsStyles: result[2]! as bool,
      supportsOptions: result[3]! as bool,
      supportsVersion27Options: result[4]! as bool,
      styles: (result[5]! as List<Object?>).cast<StyleMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CapabilitiesMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isSupported, other.isSupported) &&
        _deepEquals(isAvailable, other.isAvailable) &&
        _deepEquals(supportsStyles, other.supportsStyles) &&
        _deepEquals(supportsOptions, other.supportsOptions) &&
        _deepEquals(supportsVersion27Options, other.supportsVersion27Options) &&
        _deepEquals(styles, other.styles);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CapabilitiesMessage(isSupported: $isSupported, isAvailable: $isAvailable, supportsStyles: $supportsStyles, supportsOptions: $supportsOptions, supportsVersion27Options: $supportsVersion27Options, styles: $styles)';
  }
}

class SessionInfoMessage {
  SessionInfoMessage({
    required this.conceptCount,
    required this.hasSourceImage,
    required this.allowedStyles,
    this.selectedStyle,
    required this.isPresenting,
  });

  int conceptCount;

  bool hasSourceImage;

  List<StyleMessage> allowedStyles;

  StyleMessage? selectedStyle;

  bool isPresenting;

  List<Object?> _toList() {
    return <Object?>[
      conceptCount,
      hasSourceImage,
      allowedStyles,
      selectedStyle,
      isPresenting,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SessionInfoMessage decode(Object result) {
    result as List<Object?>;
    return SessionInfoMessage(
      conceptCount: result[0]! as int,
      hasSourceImage: result[1]! as bool,
      allowedStyles: (result[2]! as List<Object?>).cast<StyleMessage>(),
      selectedStyle: result[3] as StyleMessage?,
      isPresenting: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionInfoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(conceptCount, other.conceptCount) &&
        _deepEquals(hasSourceImage, other.hasSourceImage) &&
        _deepEquals(allowedStyles, other.allowedStyles) &&
        _deepEquals(selectedStyle, other.selectedStyle) &&
        _deepEquals(isPresenting, other.isPresenting);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SessionInfoMessage(conceptCount: $conceptCount, hasSourceImage: $hasSourceImage, allowedStyles: $allowedStyles, selectedStyle: $selectedStyle, isPresenting: $isPresenting)';
  }
}

class ResultMessage {
  ResultMessage({
    required this.bytes,
    required this.typeIdentifier,
    required this.width,
    required this.height,
    this.contentIdentifier,
    this.contentDescription,
  });

  Uint8List bytes;

  String typeIdentifier;

  int width;

  int height;

  String? contentIdentifier;

  String? contentDescription;

  List<Object?> _toList() {
    return <Object?>[
      bytes,
      typeIdentifier,
      width,
      height,
      contentIdentifier,
      contentDescription,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ResultMessage decode(Object result) {
    result as List<Object?>;
    return ResultMessage(
      bytes: result[0]! as Uint8List,
      typeIdentifier: result[1]! as String,
      width: result[2]! as int,
      height: result[3]! as int,
      contentIdentifier: result[4] as String?,
      contentDescription: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ResultMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(bytes, other.bytes) &&
        _deepEquals(typeIdentifier, other.typeIdentifier) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(contentIdentifier, other.contentIdentifier) &&
        _deepEquals(contentDescription, other.contentDescription);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ResultMessage(bytes: $bytes, typeIdentifier: $typeIdentifier, width: $width, height: $height, contentIdentifier: $contentIdentifier, contentDescription: $contentDescription)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ImageKindMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ConceptKindMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is StyleMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PersonalizationMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is VarietyMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is StrategyMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is ImageInputMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is ConceptMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is OptionsMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is ConfigurationMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is CapabilitiesMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is SessionInfoMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is ResultMessage) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ImageKindMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConceptKindMessage.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : StyleMessage.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PersonalizationMessage.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : VarietyMessage.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : StrategyMessage.values[value];
      case 135:
        return ImageInputMessage.decode(readValue(buffer)!);
      case 136:
        return ConceptMessage.decode(readValue(buffer)!);
      case 137:
        return OptionsMessage.decode(readValue(buffer)!);
      case 138:
        return ConfigurationMessage.decode(readValue(buffer)!);
      case 139:
        return CapabilitiesMessage.decode(readValue(buffer)!);
      case 140:
        return SessionInfoMessage.decode(readValue(buffer)!);
      case 141:
        return ResultMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ImagePlaygroundPlatformApi {
  /// Constructor for [ImagePlaygroundPlatformApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ImagePlaygroundPlatformApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> isSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundPlatformApi.isSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<CapabilitiesMessage> capabilities() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundPlatformApi.capabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CapabilitiesMessage;
  }
}

class ImagePlaygroundHostApi {
  /// Constructor for [ImagePlaygroundHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ImagePlaygroundHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<int> prepare(ConfigurationMessage configuration) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundHostApi.prepare$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[configuration],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Completes with null for user or programmatic cancellation.
  Future<ResultMessage?> present(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundHostApi.present$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as ResultMessage?;
  }

  Future<SessionInfoMessage> info(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundHostApi.info$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as SessionInfoMessage;
  }

  Future<void> cancel(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> release(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundHostApi.release$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<int> releaseAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundHostApi.releaseAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<int> liveHandleCount() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.image_playground.ImagePlaygroundHostApi.liveHandleCount$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }
}
