// Autogenerated from Pigeon. Do not edit by hand.
// Source: pigeons/foundation_models_api.dart
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class FoundationModelsPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "FoundationModelsPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? FoundationModelsPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FoundationModelsPigeonError {
  return FoundationModelsPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum ModelKindMessage: Int, CaseIterable {
  case system = 0
  case privateCloudCompute = 1
}

enum UseCaseMessage: Int, CaseIterable {
  case general = 0
  case contentTagging = 1
}

enum GuardrailsMessage: Int, CaseIterable {
  case defaults = 0
  case permissiveContentTransformations = 1
}

enum AvailabilityStatusMessage: Int, CaseIterable {
  case available = 0
  case deviceNotEligible = 1
  case appleIntelligenceNotEnabled = 2
  case modelNotReady = 3
  case systemNotReady = 4
  case unknown = 5
}

enum CapabilityMessage: Int, CaseIterable {
  case vision = 0
  case guidedGeneration = 1
  case reasoning = 2
  case toolCalling = 3
}

enum SamplingKindMessage: Int, CaseIterable {
  case greedy = 0
  case topK = 1
  case probabilityThreshold = 2
}

enum ToolCallingModeMessage: Int, CaseIterable {
  case allowed = 0
  case required = 1
  case disallowed = 2
}

enum ReasoningLevelMessage: Int, CaseIterable {
  case light = 0
  case moderate = 1
  case deep = 2
  case custom = 3
}

enum TranscriptPolicyMessage: Int, CaseIterable {
  case revertTranscript = 0
  case preserveTranscript = 1
}

enum FeedbackSentimentMessage: Int, CaseIterable {
  case positive = 0
  case negative = 1
  case neutral = 2
}

enum FeedbackIssueCategoryMessage: Int, CaseIterable {
  case unhelpful = 0
  case tooVerbose = 1
  case didNotFollowInstructions = 2
  case incorrect = 3
  case stereotypeOrBias = 4
  case suggestiveOrSexual = 5
  case vulgarOrOffensive = 6
  case triggeredGuardrailUnexpectedly = 7
}

enum TranscriptEntryKindMessage: Int, CaseIterable {
  case instructions = 0
  case prompt = 1
  case toolCalls = 2
  case toolOutput = 3
  case response = 4
  case reasoning = 5
}

enum SegmentKindMessage: Int, CaseIterable {
  case text = 0
  case structure = 1
  case attachment = 2
}

enum BuiltInToolMessage: Int, CaseIterable {
  case ocr = 0
  case barcodeReader = 1
}

enum ImageInputKindMessage: Int, CaseIterable {
  case file = 0
  case encoded = 1
  case pixels = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct ModelConfigMessage: Hashable, CustomStringConvertible {
  var kind: ModelKindMessage
  var useCase: UseCaseMessage
  var guardrails: GuardrailsMessage
  /// A loaded `SystemLanguageModel.Adapter` handle (system models only).
  var adapterHandle: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelConfigMessage? {
    let kind = pigeonVar_list[0] as! ModelKindMessage
    let useCase = pigeonVar_list[1] as! UseCaseMessage
    let guardrails = pigeonVar_list[2] as! GuardrailsMessage
    let adapterHandle: Int64? = nilOrValue(pigeonVar_list[3])

    return ModelConfigMessage(
      kind: kind,
      useCase: useCase,
      guardrails: guardrails,
      adapterHandle: adapterHandle
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      useCase,
      guardrails,
      adapterHandle,
    ]
  }
  static func == (lhs: ModelConfigMessage, rhs: ModelConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.useCase, rhs.useCase) && MessagesPigeonInternal.deepEquals(lhs.guardrails, rhs.guardrails) && MessagesPigeonInternal.deepEquals(lhs.adapterHandle, rhs.adapterHandle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModelConfigMessage")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: useCase, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: guardrails, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: adapterHandle, hasher: &hasher)
  }

  public var description: String {
    return "ModelConfigMessage(kind: \(String(describing: kind)), useCase: \(String(describing: useCase)), guardrails: \(String(describing: guardrails)), adapterHandle: \(String(describing: adapterHandle)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AvailabilityMessage: Hashable, CustomStringConvertible {
  var status: AvailabilityStatusMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AvailabilityMessage? {
    let status = pigeonVar_list[0] as! AvailabilityStatusMessage

    return AvailabilityMessage(
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      status
    ]
  }
  static func == (lhs: AvailabilityMessage, rhs: AvailabilityMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AvailabilityMessage")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
  }

  public var description: String {
    return "AvailabilityMessage(status: \(String(describing: status)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ModelInfoMessage: Hashable, CustomStringConvertible {
  var contextSize: Int64
  /// `SystemLanguageModel.variant.displayName` (system models only).
  var variantName: String? = nil
  var capabilities: [CapabilityMessage]
  /// BCP 47 identifiers of `Locale.Language`s.
  var supportedLanguages: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelInfoMessage? {
    let contextSize = pigeonVar_list[0] as! Int64
    let variantName: String? = nilOrValue(pigeonVar_list[1])
    let capabilities = pigeonVar_list[2] as! [CapabilityMessage]
    let supportedLanguages = pigeonVar_list[3] as! [String]

    return ModelInfoMessage(
      contextSize: contextSize,
      variantName: variantName,
      capabilities: capabilities,
      supportedLanguages: supportedLanguages
    )
  }
  func toList() -> [Any?] {
    return [
      contextSize,
      variantName,
      capabilities,
      supportedLanguages,
    ]
  }
  static func == (lhs: ModelInfoMessage, rhs: ModelInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.contextSize, rhs.contextSize) && MessagesPigeonInternal.deepEquals(lhs.variantName, rhs.variantName) && MessagesPigeonInternal.deepEquals(lhs.capabilities, rhs.capabilities) && MessagesPigeonInternal.deepEquals(lhs.supportedLanguages, rhs.supportedLanguages)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModelInfoMessage")
    MessagesPigeonInternal.deepHash(value: contextSize, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: variantName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: capabilities, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: supportedLanguages, hasher: &hasher)
  }

  public var description: String {
    return "ModelInfoMessage(contextSize: \(String(describing: contextSize)), variantName: \(String(describing: variantName)), capabilities: \(String(describing: capabilities)), supportedLanguages: \(String(describing: supportedLanguages)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct QuotaUsageMessage: Hashable, CustomStringConvertible {
  var isLimitReached: Bool
  var isApproachingLimit: Bool
  var resetDateMillis: Int64? = nil
  var hasLimitIncreaseSuggestion: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QuotaUsageMessage? {
    let isLimitReached = pigeonVar_list[0] as! Bool
    let isApproachingLimit = pigeonVar_list[1] as! Bool
    let resetDateMillis: Int64? = nilOrValue(pigeonVar_list[2])
    let hasLimitIncreaseSuggestion = pigeonVar_list[3] as! Bool

    return QuotaUsageMessage(
      isLimitReached: isLimitReached,
      isApproachingLimit: isApproachingLimit,
      resetDateMillis: resetDateMillis,
      hasLimitIncreaseSuggestion: hasLimitIncreaseSuggestion
    )
  }
  func toList() -> [Any?] {
    return [
      isLimitReached,
      isApproachingLimit,
      resetDateMillis,
      hasLimitIncreaseSuggestion,
    ]
  }
  static func == (lhs: QuotaUsageMessage, rhs: QuotaUsageMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.isLimitReached, rhs.isLimitReached) && MessagesPigeonInternal.deepEquals(lhs.isApproachingLimit, rhs.isApproachingLimit) && MessagesPigeonInternal.deepEquals(lhs.resetDateMillis, rhs.resetDateMillis) && MessagesPigeonInternal.deepEquals(lhs.hasLimitIncreaseSuggestion, rhs.hasLimitIncreaseSuggestion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("QuotaUsageMessage")
    MessagesPigeonInternal.deepHash(value: isLimitReached, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isApproachingLimit, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: resetDateMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasLimitIncreaseSuggestion, hasher: &hasher)
  }

  public var description: String {
    return "QuotaUsageMessage(isLimitReached: \(String(describing: isLimitReached)), isApproachingLimit: \(String(describing: isApproachingLimit)), resetDateMillis: \(String(describing: resetDateMillis)), hasLimitIncreaseSuggestion: \(String(describing: hasLimitIncreaseSuggestion)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AdapterInfoMessage: Hashable, CustomStringConvertible {
  var handle: Int64
  var creatorDefinedMetadataJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AdapterInfoMessage? {
    let handle = pigeonVar_list[0] as! Int64
    let creatorDefinedMetadataJson = pigeonVar_list[1] as! String

    return AdapterInfoMessage(
      handle: handle,
      creatorDefinedMetadataJson: creatorDefinedMetadataJson
    )
  }
  func toList() -> [Any?] {
    return [
      handle,
      creatorDefinedMetadataJson,
    ]
  }
  static func == (lhs: AdapterInfoMessage, rhs: AdapterInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.handle, rhs.handle) && MessagesPigeonInternal.deepEquals(lhs.creatorDefinedMetadataJson, rhs.creatorDefinedMetadataJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AdapterInfoMessage")
    MessagesPigeonInternal.deepHash(value: handle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: creatorDefinedMetadataJson, hasher: &hasher)
  }

  public var description: String {
    return "AdapterInfoMessage(handle: \(String(describing: handle)), creatorDefinedMetadataJson: \(String(describing: creatorDefinedMetadataJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImageInputMessage: Hashable, CustomStringConvertible {
  var kind: ImageInputKindMessage
  /// For `file`.
  var path: String? = nil
  /// Encoded image bytes (`encoded`) or BGRA8 pixels (`pixels`).
  var bytes: FlutterStandardTypedData? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var bytesPerRow: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageInputMessage? {
    let kind = pigeonVar_list[0] as! ImageInputKindMessage
    let path: String? = nilOrValue(pigeonVar_list[1])
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])
    let width: Int64? = nilOrValue(pigeonVar_list[3])
    let height: Int64? = nilOrValue(pigeonVar_list[4])
    let bytesPerRow: Int64? = nilOrValue(pigeonVar_list[5])

    return ImageInputMessage(
      kind: kind,
      path: path,
      bytes: bytes,
      width: width,
      height: height,
      bytesPerRow: bytesPerRow
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      path,
      bytes,
      width,
      height,
      bytesPerRow,
    ]
  }
  static func == (lhs: ImageInputMessage, rhs: ImageInputMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path) && MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.bytesPerRow, rhs.bytesPerRow)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageInputMessage")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytesPerRow, hasher: &hasher)
  }

  public var description: String {
    return "ImageInputMessage(kind: \(String(describing: kind)), path: \(String(describing: path)), bytes: \(String(describing: bytes)), width: \(String(describing: width)), height: \(String(describing: height)), bytesPerRow: \(String(describing: bytesPerRow)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImageAttachmentMessage: Hashable, CustomStringConvertible {
  var image: ImageInputMessage
  var label: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageAttachmentMessage? {
    let image = pigeonVar_list[0] as! ImageInputMessage
    let label: String? = nilOrValue(pigeonVar_list[1])

    return ImageAttachmentMessage(
      image: image,
      label: label
    )
  }
  func toList() -> [Any?] {
    return [
      image,
      label,
    ]
  }
  static func == (lhs: ImageAttachmentMessage, rhs: ImageAttachmentMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.image, rhs.image) && MessagesPigeonInternal.deepEquals(lhs.label, rhs.label)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageAttachmentMessage")
    MessagesPigeonInternal.deepHash(value: image, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: label, hasher: &hasher)
  }

  public var description: String {
    return "ImageAttachmentMessage(image: \(String(describing: image)), label: \(String(describing: label)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PromptMessage: Hashable, CustomStringConvertible {
  var text: String
  /// Attached after the text, in order.
  var images: [ImageAttachmentMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PromptMessage? {
    let text = pigeonVar_list[0] as! String
    let images = pigeonVar_list[1] as! [ImageAttachmentMessage]

    return PromptMessage(
      text: text,
      images: images
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      images,
    ]
  }
  static func == (lhs: PromptMessage, rhs: PromptMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.images, rhs.images)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PromptMessage")
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: images, hasher: &hasher)
  }

  public var description: String {
    return "PromptMessage(text: \(String(describing: text)), images: \(String(describing: images)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GenerationOptionsMessage: Hashable, CustomStringConvertible {
  var samplingKind: SamplingKindMessage? = nil
  var topK: Int64? = nil
  var probabilityThreshold: Double? = nil
  var seed: Int64? = nil
  var temperature: Double? = nil
  var maximumResponseTokens: Int64? = nil
  var toolCallingMode: ToolCallingModeMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerationOptionsMessage? {
    let samplingKind: SamplingKindMessage? = nilOrValue(pigeonVar_list[0])
    let topK: Int64? = nilOrValue(pigeonVar_list[1])
    let probabilityThreshold: Double? = nilOrValue(pigeonVar_list[2])
    let seed: Int64? = nilOrValue(pigeonVar_list[3])
    let temperature: Double? = nilOrValue(pigeonVar_list[4])
    let maximumResponseTokens: Int64? = nilOrValue(pigeonVar_list[5])
    let toolCallingMode: ToolCallingModeMessage? = nilOrValue(pigeonVar_list[6])

    return GenerationOptionsMessage(
      samplingKind: samplingKind,
      topK: topK,
      probabilityThreshold: probabilityThreshold,
      seed: seed,
      temperature: temperature,
      maximumResponseTokens: maximumResponseTokens,
      toolCallingMode: toolCallingMode
    )
  }
  func toList() -> [Any?] {
    return [
      samplingKind,
      topK,
      probabilityThreshold,
      seed,
      temperature,
      maximumResponseTokens,
      toolCallingMode,
    ]
  }
  static func == (lhs: GenerationOptionsMessage, rhs: GenerationOptionsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.samplingKind, rhs.samplingKind) && MessagesPigeonInternal.deepEquals(lhs.topK, rhs.topK) && MessagesPigeonInternal.deepEquals(lhs.probabilityThreshold, rhs.probabilityThreshold) && MessagesPigeonInternal.deepEquals(lhs.seed, rhs.seed) && MessagesPigeonInternal.deepEquals(lhs.temperature, rhs.temperature) && MessagesPigeonInternal.deepEquals(lhs.maximumResponseTokens, rhs.maximumResponseTokens) && MessagesPigeonInternal.deepEquals(lhs.toolCallingMode, rhs.toolCallingMode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerationOptionsMessage")
    MessagesPigeonInternal.deepHash(value: samplingKind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: topK, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: probabilityThreshold, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: seed, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: temperature, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maximumResponseTokens, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolCallingMode, hasher: &hasher)
  }

  public var description: String {
    return "GenerationOptionsMessage(samplingKind: \(String(describing: samplingKind)), topK: \(String(describing: topK)), probabilityThreshold: \(String(describing: probabilityThreshold)), seed: \(String(describing: seed)), temperature: \(String(describing: temperature)), maximumResponseTokens: \(String(describing: maximumResponseTokens)), toolCallingMode: \(String(describing: toolCallingMode)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ContextOptionsMessage: Hashable, CustomStringConvertible {
  var includeSchemaInPrompt: Bool? = nil
  var reasoningLevel: ReasoningLevelMessage? = nil
  var customReasoningLevel: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContextOptionsMessage? {
    let includeSchemaInPrompt: Bool? = nilOrValue(pigeonVar_list[0])
    let reasoningLevel: ReasoningLevelMessage? = nilOrValue(pigeonVar_list[1])
    let customReasoningLevel: String? = nilOrValue(pigeonVar_list[2])

    return ContextOptionsMessage(
      includeSchemaInPrompt: includeSchemaInPrompt,
      reasoningLevel: reasoningLevel,
      customReasoningLevel: customReasoningLevel
    )
  }
  func toList() -> [Any?] {
    return [
      includeSchemaInPrompt,
      reasoningLevel,
      customReasoningLevel,
    ]
  }
  static func == (lhs: ContextOptionsMessage, rhs: ContextOptionsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.includeSchemaInPrompt, rhs.includeSchemaInPrompt) && MessagesPigeonInternal.deepEquals(lhs.reasoningLevel, rhs.reasoningLevel) && MessagesPigeonInternal.deepEquals(lhs.customReasoningLevel, rhs.customReasoningLevel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ContextOptionsMessage")
    MessagesPigeonInternal.deepHash(value: includeSchemaInPrompt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reasoningLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: customReasoningLevel, hasher: &hasher)
  }

  public var description: String {
    return "ContextOptionsMessage(includeSchemaInPrompt: \(String(describing: includeSchemaInPrompt)), reasoningLevel: \(String(describing: reasoningLevel)), customReasoningLevel: \(String(describing: customReasoningLevel)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ToolDefinitionMessage: Hashable, CustomStringConvertible {
  var name: String
  var toolDescription: String
  /// JSON Schema (GenerationSchema Codable format).
  var parametersJson: String
  var includesSchemaInInstructions: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ToolDefinitionMessage? {
    let name = pigeonVar_list[0] as! String
    let toolDescription = pigeonVar_list[1] as! String
    let parametersJson = pigeonVar_list[2] as! String
    let includesSchemaInInstructions = pigeonVar_list[3] as! Bool

    return ToolDefinitionMessage(
      name: name,
      toolDescription: toolDescription,
      parametersJson: parametersJson,
      includesSchemaInInstructions: includesSchemaInInstructions
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      toolDescription,
      parametersJson,
      includesSchemaInInstructions,
    ]
  }
  static func == (lhs: ToolDefinitionMessage, rhs: ToolDefinitionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.toolDescription, rhs.toolDescription) && MessagesPigeonInternal.deepEquals(lhs.parametersJson, rhs.parametersJson) && MessagesPigeonInternal.deepEquals(lhs.includesSchemaInInstructions, rhs.includesSchemaInInstructions)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ToolDefinitionMessage")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolDescription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: parametersJson, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: includesSchemaInInstructions, hasher: &hasher)
  }

  public var description: String {
    return "ToolDefinitionMessage(name: \(String(describing: name)), toolDescription: \(String(describing: toolDescription)), parametersJson: \(String(describing: parametersJson)), includesSchemaInInstructions: \(String(describing: includesSchemaInInstructions)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionConfigMessage: Hashable, CustomStringConvertible {
  var model: ModelConfigMessage
  var instructions: String? = nil
  /// Tools implemented in Dart (called back through the FlutterApi).
  var tools: [ToolDefinitionMessage]
  var builtInTools: [BuiltInToolMessage]
  /// Restores a session from `Transcript` Codable JSON (instead of
  /// [instructions]).
  var transcriptJson: String? = nil
  var transcriptPolicy: TranscriptPolicyMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionConfigMessage? {
    let model = pigeonVar_list[0] as! ModelConfigMessage
    let instructions: String? = nilOrValue(pigeonVar_list[1])
    let tools = pigeonVar_list[2] as! [ToolDefinitionMessage]
    let builtInTools = pigeonVar_list[3] as! [BuiltInToolMessage]
    let transcriptJson: String? = nilOrValue(pigeonVar_list[4])
    let transcriptPolicy: TranscriptPolicyMessage? = nilOrValue(pigeonVar_list[5])

    return SessionConfigMessage(
      model: model,
      instructions: instructions,
      tools: tools,
      builtInTools: builtInTools,
      transcriptJson: transcriptJson,
      transcriptPolicy: transcriptPolicy
    )
  }
  func toList() -> [Any?] {
    return [
      model,
      instructions,
      tools,
      builtInTools,
      transcriptJson,
      transcriptPolicy,
    ]
  }
  static func == (lhs: SessionConfigMessage, rhs: SessionConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.instructions, rhs.instructions) && MessagesPigeonInternal.deepEquals(lhs.tools, rhs.tools) && MessagesPigeonInternal.deepEquals(lhs.builtInTools, rhs.builtInTools) && MessagesPigeonInternal.deepEquals(lhs.transcriptJson, rhs.transcriptJson) && MessagesPigeonInternal.deepEquals(lhs.transcriptPolicy, rhs.transcriptPolicy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SessionConfigMessage")
    MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: instructions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tools, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: builtInTools, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transcriptJson, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transcriptPolicy, hasher: &hasher)
  }

  public var description: String {
    return "SessionConfigMessage(model: \(String(describing: model)), instructions: \(String(describing: instructions)), tools: \(String(describing: tools)), builtInTools: \(String(describing: builtInTools)), transcriptJson: \(String(describing: transcriptJson)), transcriptPolicy: \(String(describing: transcriptPolicy)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RespondRequestMessage: Hashable, CustomStringConvertible {
  var sessionHandle: Int64
  /// Chosen by Dart; identifies stream events and cancellation.
  var requestId: Int64
  var prompt: PromptMessage
  var options: GenerationOptionsMessage
  var contextOptions: ContextOptionsMessage
  /// When set, generate structured content matching this JSON Schema.
  var schemaJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RespondRequestMessage? {
    let sessionHandle = pigeonVar_list[0] as! Int64
    let requestId = pigeonVar_list[1] as! Int64
    let prompt = pigeonVar_list[2] as! PromptMessage
    let options = pigeonVar_list[3] as! GenerationOptionsMessage
    let contextOptions = pigeonVar_list[4] as! ContextOptionsMessage
    let schemaJson: String? = nilOrValue(pigeonVar_list[5])

    return RespondRequestMessage(
      sessionHandle: sessionHandle,
      requestId: requestId,
      prompt: prompt,
      options: options,
      contextOptions: contextOptions,
      schemaJson: schemaJson
    )
  }
  func toList() -> [Any?] {
    return [
      sessionHandle,
      requestId,
      prompt,
      options,
      contextOptions,
      schemaJson,
    ]
  }
  static func == (lhs: RespondRequestMessage, rhs: RespondRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionHandle, rhs.sessionHandle) && MessagesPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && MessagesPigeonInternal.deepEquals(lhs.prompt, rhs.prompt) && MessagesPigeonInternal.deepEquals(lhs.options, rhs.options) && MessagesPigeonInternal.deepEquals(lhs.contextOptions, rhs.contextOptions) && MessagesPigeonInternal.deepEquals(lhs.schemaJson, rhs.schemaJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RespondRequestMessage")
    MessagesPigeonInternal.deepHash(value: sessionHandle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: prompt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: options, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contextOptions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: schemaJson, hasher: &hasher)
  }

  public var description: String {
    return "RespondRequestMessage(sessionHandle: \(String(describing: sessionHandle)), requestId: \(String(describing: requestId)), prompt: \(String(describing: prompt)), options: \(String(describing: options)), contextOptions: \(String(describing: contextOptions)), schemaJson: \(String(describing: schemaJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TokenCountRequestMessage: Hashable, CustomStringConvertible {
  var prompt: PromptMessage? = nil
  var instructions: String? = nil
  var tools: [ToolDefinitionMessage]
  var schemaJson: String? = nil
  var transcriptJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TokenCountRequestMessage? {
    let prompt: PromptMessage? = nilOrValue(pigeonVar_list[0])
    let instructions: String? = nilOrValue(pigeonVar_list[1])
    let tools = pigeonVar_list[2] as! [ToolDefinitionMessage]
    let schemaJson: String? = nilOrValue(pigeonVar_list[3])
    let transcriptJson: String? = nilOrValue(pigeonVar_list[4])

    return TokenCountRequestMessage(
      prompt: prompt,
      instructions: instructions,
      tools: tools,
      schemaJson: schemaJson,
      transcriptJson: transcriptJson
    )
  }
  func toList() -> [Any?] {
    return [
      prompt,
      instructions,
      tools,
      schemaJson,
      transcriptJson,
    ]
  }
  static func == (lhs: TokenCountRequestMessage, rhs: TokenCountRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.prompt, rhs.prompt) && MessagesPigeonInternal.deepEquals(lhs.instructions, rhs.instructions) && MessagesPigeonInternal.deepEquals(lhs.tools, rhs.tools) && MessagesPigeonInternal.deepEquals(lhs.schemaJson, rhs.schemaJson) && MessagesPigeonInternal.deepEquals(lhs.transcriptJson, rhs.transcriptJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TokenCountRequestMessage")
    MessagesPigeonInternal.deepHash(value: prompt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: instructions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tools, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: schemaJson, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transcriptJson, hasher: &hasher)
  }

  public var description: String {
    return "TokenCountRequestMessage(prompt: \(String(describing: prompt)), instructions: \(String(describing: instructions)), tools: \(String(describing: tools)), schemaJson: \(String(describing: schemaJson)), transcriptJson: \(String(describing: transcriptJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FeedbackIssueMessage: Hashable, CustomStringConvertible {
  var category: FeedbackIssueCategoryMessage
  var explanation: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FeedbackIssueMessage? {
    let category = pigeonVar_list[0] as! FeedbackIssueCategoryMessage
    let explanation: String? = nilOrValue(pigeonVar_list[1])

    return FeedbackIssueMessage(
      category: category,
      explanation: explanation
    )
  }
  func toList() -> [Any?] {
    return [
      category,
      explanation,
    ]
  }
  static func == (lhs: FeedbackIssueMessage, rhs: FeedbackIssueMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.category, rhs.category) && MessagesPigeonInternal.deepEquals(lhs.explanation, rhs.explanation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FeedbackIssueMessage")
    MessagesPigeonInternal.deepHash(value: category, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: explanation, hasher: &hasher)
  }

  public var description: String {
    return "FeedbackIssueMessage(category: \(String(describing: category)), explanation: \(String(describing: explanation)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UsageMessage: Hashable, CustomStringConvertible {
  var inputTokens: Int64
  var cachedInputTokens: Int64
  var outputTokens: Int64
  var reasoningTokens: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UsageMessage? {
    let inputTokens = pigeonVar_list[0] as! Int64
    let cachedInputTokens = pigeonVar_list[1] as! Int64
    let outputTokens = pigeonVar_list[2] as! Int64
    let reasoningTokens = pigeonVar_list[3] as! Int64

    return UsageMessage(
      inputTokens: inputTokens,
      cachedInputTokens: cachedInputTokens,
      outputTokens: outputTokens,
      reasoningTokens: reasoningTokens
    )
  }
  func toList() -> [Any?] {
    return [
      inputTokens,
      cachedInputTokens,
      outputTokens,
      reasoningTokens,
    ]
  }
  static func == (lhs: UsageMessage, rhs: UsageMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.inputTokens, rhs.inputTokens) && MessagesPigeonInternal.deepEquals(lhs.cachedInputTokens, rhs.cachedInputTokens) && MessagesPigeonInternal.deepEquals(lhs.outputTokens, rhs.outputTokens) && MessagesPigeonInternal.deepEquals(lhs.reasoningTokens, rhs.reasoningTokens)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UsageMessage")
    MessagesPigeonInternal.deepHash(value: inputTokens, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cachedInputTokens, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputTokens, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reasoningTokens, hasher: &hasher)
  }

  public var description: String {
    return "UsageMessage(inputTokens: \(String(describing: inputTokens)), cachedInputTokens: \(String(describing: cachedInputTokens)), outputTokens: \(String(describing: outputTokens)), reasoningTokens: \(String(describing: reasoningTokens)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SegmentMessage: Hashable, CustomStringConvertible {
  var id: String
  var kind: SegmentKindMessage
  var text: String? = nil
  var contentJson: String? = nil
  var schemaName: String? = nil
  var attachmentLabel: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SegmentMessage? {
    let id = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! SegmentKindMessage
    let text: String? = nilOrValue(pigeonVar_list[2])
    let contentJson: String? = nilOrValue(pigeonVar_list[3])
    let schemaName: String? = nilOrValue(pigeonVar_list[4])
    let attachmentLabel: String? = nilOrValue(pigeonVar_list[5])

    return SegmentMessage(
      id: id,
      kind: kind,
      text: text,
      contentJson: contentJson,
      schemaName: schemaName,
      attachmentLabel: attachmentLabel
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      kind,
      text,
      contentJson,
      schemaName,
      attachmentLabel,
    ]
  }
  static func == (lhs: SegmentMessage, rhs: SegmentMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.contentJson, rhs.contentJson) && MessagesPigeonInternal.deepEquals(lhs.schemaName, rhs.schemaName) && MessagesPigeonInternal.deepEquals(lhs.attachmentLabel, rhs.attachmentLabel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SegmentMessage")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contentJson, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: schemaName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attachmentLabel, hasher: &hasher)
  }

  public var description: String {
    return "SegmentMessage(id: \(String(describing: id)), kind: \(String(describing: kind)), text: \(String(describing: text)), contentJson: \(String(describing: contentJson)), schemaName: \(String(describing: schemaName)), attachmentLabel: \(String(describing: attachmentLabel)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ToolCallMessage: Hashable, CustomStringConvertible {
  var id: String
  var toolName: String
  var argumentsJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ToolCallMessage? {
    let id = pigeonVar_list[0] as! String
    let toolName = pigeonVar_list[1] as! String
    let argumentsJson = pigeonVar_list[2] as! String

    return ToolCallMessage(
      id: id,
      toolName: toolName,
      argumentsJson: argumentsJson
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      toolName,
      argumentsJson,
    ]
  }
  static func == (lhs: ToolCallMessage, rhs: ToolCallMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.toolName, rhs.toolName) && MessagesPigeonInternal.deepEquals(lhs.argumentsJson, rhs.argumentsJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ToolCallMessage")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: argumentsJson, hasher: &hasher)
  }

  public var description: String {
    return "ToolCallMessage(id: \(String(describing: id)), toolName: \(String(describing: toolName)), argumentsJson: \(String(describing: argumentsJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TranscriptEntryMessage: Hashable, CustomStringConvertible {
  var id: String
  var kind: TranscriptEntryKindMessage
  var segments: [SegmentMessage]
  var toolCalls: [ToolCallMessage]
  var toolDefinitions: [ToolDefinitionMessage]
  var toolName: String? = nil
  var responseFormatName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TranscriptEntryMessage? {
    let id = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! TranscriptEntryKindMessage
    let segments = pigeonVar_list[2] as! [SegmentMessage]
    let toolCalls = pigeonVar_list[3] as! [ToolCallMessage]
    let toolDefinitions = pigeonVar_list[4] as! [ToolDefinitionMessage]
    let toolName: String? = nilOrValue(pigeonVar_list[5])
    let responseFormatName: String? = nilOrValue(pigeonVar_list[6])

    return TranscriptEntryMessage(
      id: id,
      kind: kind,
      segments: segments,
      toolCalls: toolCalls,
      toolDefinitions: toolDefinitions,
      toolName: toolName,
      responseFormatName: responseFormatName
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      kind,
      segments,
      toolCalls,
      toolDefinitions,
      toolName,
      responseFormatName,
    ]
  }
  static func == (lhs: TranscriptEntryMessage, rhs: TranscriptEntryMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.segments, rhs.segments) && MessagesPigeonInternal.deepEquals(lhs.toolCalls, rhs.toolCalls) && MessagesPigeonInternal.deepEquals(lhs.toolDefinitions, rhs.toolDefinitions) && MessagesPigeonInternal.deepEquals(lhs.toolName, rhs.toolName) && MessagesPigeonInternal.deepEquals(lhs.responseFormatName, rhs.responseFormatName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TranscriptEntryMessage")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: segments, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolCalls, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolDefinitions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: responseFormatName, hasher: &hasher)
  }

  public var description: String {
    return "TranscriptEntryMessage(id: \(String(describing: id)), kind: \(String(describing: kind)), segments: \(String(describing: segments)), toolCalls: \(String(describing: toolCalls)), toolDefinitions: \(String(describing: toolDefinitions)), toolName: \(String(describing: toolName)), responseFormatName: \(String(describing: responseFormatName)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TranscriptMessage: Hashable, CustomStringConvertible {
  var entries: [TranscriptEntryMessage]
  var json: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TranscriptMessage? {
    let entries = pigeonVar_list[0] as! [TranscriptEntryMessage]
    let json = pigeonVar_list[1] as! String

    return TranscriptMessage(
      entries: entries,
      json: json
    )
  }
  func toList() -> [Any?] {
    return [
      entries,
      json,
    ]
  }
  static func == (lhs: TranscriptMessage, rhs: TranscriptMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.entries, rhs.entries) && MessagesPigeonInternal.deepEquals(lhs.json, rhs.json)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TranscriptMessage")
    MessagesPigeonInternal.deepHash(value: entries, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: json, hasher: &hasher)
  }

  public var description: String {
    return "TranscriptMessage(entries: \(String(describing: entries)), json: \(String(describing: json)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ResponseMessage: Hashable, CustomStringConvertible {
  /// For text responses.
  var text: String? = nil
  /// For structured responses (`GeneratedContent.jsonString`).
  var contentJson: String? = nil
  var isComplete: Bool
  var entries: [TranscriptEntryMessage]
  var usage: UsageMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ResponseMessage? {
    let text: String? = nilOrValue(pigeonVar_list[0])
    let contentJson: String? = nilOrValue(pigeonVar_list[1])
    let isComplete = pigeonVar_list[2] as! Bool
    let entries = pigeonVar_list[3] as! [TranscriptEntryMessage]
    let usage = pigeonVar_list[4] as! UsageMessage

    return ResponseMessage(
      text: text,
      contentJson: contentJson,
      isComplete: isComplete,
      entries: entries,
      usage: usage
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      contentJson,
      isComplete,
      entries,
      usage,
    ]
  }
  static func == (lhs: ResponseMessage, rhs: ResponseMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.contentJson, rhs.contentJson) && MessagesPigeonInternal.deepEquals(lhs.isComplete, rhs.isComplete) && MessagesPigeonInternal.deepEquals(lhs.entries, rhs.entries) && MessagesPigeonInternal.deepEquals(lhs.usage, rhs.usage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ResponseMessage")
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contentJson, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isComplete, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: entries, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: usage, hasher: &hasher)
  }

  public var description: String {
    return "ResponseMessage(text: \(String(describing: text)), contentJson: \(String(describing: contentJson)), isComplete: \(String(describing: isComplete)), entries: \(String(describing: entries)), usage: \(String(describing: usage)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StreamSnapshotMessage: Hashable, CustomStringConvertible {
  var requestId: Int64
  /// Cumulative content so far (not a delta).
  var text: String? = nil
  var contentJson: String? = nil
  var isComplete: Bool
  var usage: UsageMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StreamSnapshotMessage? {
    let requestId = pigeonVar_list[0] as! Int64
    let text: String? = nilOrValue(pigeonVar_list[1])
    let contentJson: String? = nilOrValue(pigeonVar_list[2])
    let isComplete = pigeonVar_list[3] as! Bool
    let usage = pigeonVar_list[4] as! UsageMessage

    return StreamSnapshotMessage(
      requestId: requestId,
      text: text,
      contentJson: contentJson,
      isComplete: isComplete,
      usage: usage
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      text,
      contentJson,
      isComplete,
      usage,
    ]
  }
  static func == (lhs: StreamSnapshotMessage, rhs: StreamSnapshotMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.contentJson, rhs.contentJson) && MessagesPigeonInternal.deepEquals(lhs.isComplete, rhs.isComplete) && MessagesPigeonInternal.deepEquals(lhs.usage, rhs.usage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StreamSnapshotMessage")
    MessagesPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contentJson, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isComplete, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: usage, hasher: &hasher)
  }

  public var description: String {
    return "StreamSnapshotMessage(requestId: \(String(describing: requestId)), text: \(String(describing: text)), contentJson: \(String(describing: contentJson)), isComplete: \(String(describing: isComplete)), usage: \(String(describing: usage)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ToolCallRequestMessage: Hashable, CustomStringConvertible {
  var sessionHandle: Int64
  var toolName: String
  var argumentsJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ToolCallRequestMessage? {
    let sessionHandle = pigeonVar_list[0] as! Int64
    let toolName = pigeonVar_list[1] as! String
    let argumentsJson = pigeonVar_list[2] as! String

    return ToolCallRequestMessage(
      sessionHandle: sessionHandle,
      toolName: toolName,
      argumentsJson: argumentsJson
    )
  }
  func toList() -> [Any?] {
    return [
      sessionHandle,
      toolName,
      argumentsJson,
    ]
  }
  static func == (lhs: ToolCallRequestMessage, rhs: ToolCallRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionHandle, rhs.sessionHandle) && MessagesPigeonInternal.deepEquals(lhs.toolName, rhs.toolName) && MessagesPigeonInternal.deepEquals(lhs.argumentsJson, rhs.argumentsJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ToolCallRequestMessage")
    MessagesPigeonInternal.deepHash(value: sessionHandle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: argumentsJson, hasher: &hasher)
  }

  public var description: String {
    return "ToolCallRequestMessage(sessionHandle: \(String(describing: sessionHandle)), toolName: \(String(describing: toolName)), argumentsJson: \(String(describing: argumentsJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ToolResultMessage: Hashable, CustomStringConvertible {
  /// Plain-text output.
  var text: String? = nil
  /// Structured output as JSON (used when [text] is null).
  var contentJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ToolResultMessage? {
    let text: String? = nilOrValue(pigeonVar_list[0])
    let contentJson: String? = nilOrValue(pigeonVar_list[1])

    return ToolResultMessage(
      text: text,
      contentJson: contentJson
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      contentJson,
    ]
  }
  static func == (lhs: ToolResultMessage, rhs: ToolResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.contentJson, rhs.contentJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ToolResultMessage")
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contentJson, hasher: &hasher)
  }

  public var description: String {
    return "ToolResultMessage(text: \(String(describing: text)), contentJson: \(String(describing: contentJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ErrorMessage: Hashable, CustomStringConvertible {
  var code: String
  var message: String
  var details: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ErrorMessage? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let details: String? = nilOrValue(pigeonVar_list[2])

    return ErrorMessage(
      code: code,
      message: message,
      details: details
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      details,
    ]
  }
  static func == (lhs: ErrorMessage, rhs: ErrorMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.details, rhs.details)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ErrorMessage")
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: details, hasher: &hasher)
  }

  public var description: String {
    return "ErrorMessage(code: \(String(describing: code)), message: \(String(describing: message)), details: \(String(describing: details)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ModelKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return UseCaseMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GuardrailsMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AvailabilityStatusMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CapabilityMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SamplingKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ToolCallingModeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ReasoningLevelMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TranscriptPolicyMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FeedbackSentimentMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FeedbackIssueCategoryMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TranscriptEntryKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 141:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SegmentKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 142:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BuiltInToolMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 143:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ImageInputKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 144:
      return ModelConfigMessage.fromList(self.readValue() as! [Any?])
    case 145:
      return AvailabilityMessage.fromList(self.readValue() as! [Any?])
    case 146:
      return ModelInfoMessage.fromList(self.readValue() as! [Any?])
    case 147:
      return QuotaUsageMessage.fromList(self.readValue() as! [Any?])
    case 148:
      return AdapterInfoMessage.fromList(self.readValue() as! [Any?])
    case 149:
      return ImageInputMessage.fromList(self.readValue() as! [Any?])
    case 150:
      return ImageAttachmentMessage.fromList(self.readValue() as! [Any?])
    case 151:
      return PromptMessage.fromList(self.readValue() as! [Any?])
    case 152:
      return GenerationOptionsMessage.fromList(self.readValue() as! [Any?])
    case 153:
      return ContextOptionsMessage.fromList(self.readValue() as! [Any?])
    case 154:
      return ToolDefinitionMessage.fromList(self.readValue() as! [Any?])
    case 155:
      return SessionConfigMessage.fromList(self.readValue() as! [Any?])
    case 156:
      return RespondRequestMessage.fromList(self.readValue() as! [Any?])
    case 157:
      return TokenCountRequestMessage.fromList(self.readValue() as! [Any?])
    case 158:
      return FeedbackIssueMessage.fromList(self.readValue() as! [Any?])
    case 159:
      return UsageMessage.fromList(self.readValue() as! [Any?])
    case 160:
      return SegmentMessage.fromList(self.readValue() as! [Any?])
    case 161:
      return ToolCallMessage.fromList(self.readValue() as! [Any?])
    case 162:
      return TranscriptEntryMessage.fromList(self.readValue() as! [Any?])
    case 163:
      return TranscriptMessage.fromList(self.readValue() as! [Any?])
    case 164:
      return ResponseMessage.fromList(self.readValue() as! [Any?])
    case 165:
      return StreamSnapshotMessage.fromList(self.readValue() as! [Any?])
    case 166:
      return ToolCallRequestMessage.fromList(self.readValue() as! [Any?])
    case 167:
      return ToolResultMessage.fromList(self.readValue() as! [Any?])
    case 168:
      return ErrorMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ModelKindMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? UseCaseMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? GuardrailsMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? AvailabilityStatusMessage {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? CapabilityMessage {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? SamplingKindMessage {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? ToolCallingModeMessage {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReasoningLevelMessage {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? TranscriptPolicyMessage {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? FeedbackSentimentMessage {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? FeedbackIssueCategoryMessage {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? TranscriptEntryKindMessage {
      super.writeByte(140)
      super.writeValue(value.rawValue)
    } else if let value = value as? SegmentKindMessage {
      super.writeByte(141)
      super.writeValue(value.rawValue)
    } else if let value = value as? BuiltInToolMessage {
      super.writeByte(142)
      super.writeValue(value.rawValue)
    } else if let value = value as? ImageInputKindMessage {
      super.writeByte(143)
      super.writeValue(value.rawValue)
    } else if let value = value as? ModelConfigMessage {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? AvailabilityMessage {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? ModelInfoMessage {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? QuotaUsageMessage {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? AdapterInfoMessage {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? ImageInputMessage {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? ImageAttachmentMessage {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? PromptMessage {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? GenerationOptionsMessage {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? ContextOptionsMessage {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? ToolDefinitionMessage {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? SessionConfigMessage {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? RespondRequestMessage {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? TokenCountRequestMessage {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else if let value = value as? FeedbackIssueMessage {
      super.writeByte(158)
      super.writeValue(value.toList())
    } else if let value = value as? UsageMessage {
      super.writeByte(159)
      super.writeValue(value.toList())
    } else if let value = value as? SegmentMessage {
      super.writeByte(160)
      super.writeValue(value.toList())
    } else if let value = value as? ToolCallMessage {
      super.writeByte(161)
      super.writeValue(value.toList())
    } else if let value = value as? TranscriptEntryMessage {
      super.writeByte(162)
      super.writeValue(value.toList())
    } else if let value = value as? TranscriptMessage {
      super.writeByte(163)
      super.writeValue(value.toList())
    } else if let value = value as? ResponseMessage {
      super.writeByte(164)
      super.writeValue(value.toList())
    } else if let value = value as? StreamSnapshotMessage {
      super.writeByte(165)
      super.writeValue(value.toList())
    } else if let value = value as? ToolCallRequestMessage {
      super.writeByte(166)
      super.writeValue(value.toList())
    } else if let value = value as? ToolResultMessage {
      super.writeByte(167)
      super.writeValue(value.toList())
    } else if let value = value as? ErrorMessage {
      super.writeByte(168)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Always available.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FoundationModelsPlatformApi {
  /// Whether the Foundation Models framework is available (iOS/macOS 26+).
  func isSupported() throws -> Bool
  /// Whether iOS/macOS 27 features are available (Private Cloud Compute,
  /// capabilities, reasoning).
  func isVersion27Supported() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FoundationModelsPlatformApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `FoundationModelsPlatformApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FoundationModelsPlatformApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether the Foundation Models framework is available (iOS/macOS 26+).
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsPlatformApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// Whether iOS/macOS 27 features are available (Private Cloud Compute,
    /// capabilities, reasoning).
    let isVersion27SupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsPlatformApi.isVersion27Supported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isVersion27SupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isVersion27Supported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isVersion27SupportedChannel.setMessageHandler(nil)
    }
  }
}
/// Registered only when Foundation Models is available.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FoundationModelsHostApi {
  func availability(model: ModelConfigMessage) async throws -> AvailabilityMessage
  func modelInfo(model: ModelConfigMessage) async throws -> ModelInfoMessage
  func supportsLocale(model: ModelConfigMessage, localeIdentifier: String?) async throws -> Bool
  func tokenCount(model: ModelConfigMessage, request: TokenCountRequestMessage) async throws -> Int64
  func privateCloudComputeQuota() async throws -> QuotaUsageMessage
  func showQuotaLimitIncreaseSuggestion() throws
  func loadAdapter(path: String?, name: String?) async throws -> AdapterInfoMessage
  func compileAdapter(adapterHandle: Int64) async throws
  func compatibleAdapterIdentifiers(name: String) throws -> [String]
  func removeObsoleteAdapters() async throws
  /// Decodes and re-encodes a schema, returning Apple's canonical JSON.
  func validateSchema(schemaJson: String) async throws -> String
  /// Decodes `Transcript` Codable JSON into structured entries.
  func decodeTranscript(json: String) async throws -> TranscriptMessage
  func createSession(config: SessionConfigMessage) async throws -> Int64
  func respond(request: RespondRequestMessage) async throws -> ResponseMessage
  /// Starts streaming; snapshots arrive through the callback API.
  func startStream(request: RespondRequestMessage) async throws
  /// Cancels an in-flight `respond` or stream with this request id.
  func cancelRequest(requestId: Int64) throws
  func prewarm(sessionHandle: Int64, promptPrefix: PromptMessage?) throws
  func transcript(sessionHandle: Int64) async throws -> TranscriptMessage
  func isResponding(sessionHandle: Int64) throws -> Bool
  func sessionUsage(sessionHandle: Int64) throws -> UsageMessage
  func setTranscriptPolicy(sessionHandle: Int64, policy: TranscriptPolicyMessage?) throws
  func logFeedbackAttachment(sessionHandle: Int64, sentiment: FeedbackSentimentMessage?, issues: [FeedbackIssueMessage], desiredResponseText: String?) async throws -> FlutterStandardTypedData
  func release(handle: Int64) async throws
  func releaseAll() async throws -> Int64
  func liveHandleCount() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FoundationModelsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `FoundationModelsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FoundationModelsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let availabilityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.availability\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      availabilityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modelArg = args[0] as! ModelConfigMessage
        Task { @MainActor in
          do {
            let result = try await api.availability(model: modelArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      availabilityChannel.setMessageHandler(nil)
    }
    let modelInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.modelInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      modelInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modelArg = args[0] as! ModelConfigMessage
        Task { @MainActor in
          do {
            let result = try await api.modelInfo(model: modelArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      modelInfoChannel.setMessageHandler(nil)
    }
    let supportsLocaleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.supportsLocale\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      supportsLocaleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modelArg = args[0] as! ModelConfigMessage
        let localeIdentifierArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.supportsLocale(model: modelArg, localeIdentifier: localeIdentifierArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      supportsLocaleChannel.setMessageHandler(nil)
    }
    let tokenCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.tokenCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      tokenCountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modelArg = args[0] as! ModelConfigMessage
        let requestArg = args[1] as! TokenCountRequestMessage
        Task { @MainActor in
          do {
            let result = try await api.tokenCount(model: modelArg, request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      tokenCountChannel.setMessageHandler(nil)
    }
    let privateCloudComputeQuotaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.privateCloudComputeQuota\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      privateCloudComputeQuotaChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.privateCloudComputeQuota()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      privateCloudComputeQuotaChannel.setMessageHandler(nil)
    }
    let showQuotaLimitIncreaseSuggestionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.showQuotaLimitIncreaseSuggestion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showQuotaLimitIncreaseSuggestionChannel.setMessageHandler { _, reply in
        do {
          try api.showQuotaLimitIncreaseSuggestion()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showQuotaLimitIncreaseSuggestionChannel.setMessageHandler(nil)
    }
    let loadAdapterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.loadAdapter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadAdapterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg: String? = nilOrValue(args[0])
        let nameArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.loadAdapter(path: pathArg, name: nameArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadAdapterChannel.setMessageHandler(nil)
    }
    let compileAdapterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.compileAdapter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compileAdapterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adapterHandleArg = args[0] as! Int64
        Task { @MainActor in
          do {
            try await api.compileAdapter(adapterHandle: adapterHandleArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      compileAdapterChannel.setMessageHandler(nil)
    }
    let compatibleAdapterIdentifiersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.compatibleAdapterIdentifiers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compatibleAdapterIdentifiersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        do {
          let result = try api.compatibleAdapterIdentifiers(name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      compatibleAdapterIdentifiersChannel.setMessageHandler(nil)
    }
    let removeObsoleteAdaptersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.removeObsoleteAdapters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeObsoleteAdaptersChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.removeObsoleteAdapters()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeObsoleteAdaptersChannel.setMessageHandler(nil)
    }
    /// Decodes and re-encodes a schema, returning Apple's canonical JSON.
    let validateSchemaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.validateSchema\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      validateSchemaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let schemaJsonArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.validateSchema(schemaJson: schemaJsonArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      validateSchemaChannel.setMessageHandler(nil)
    }
    /// Decodes `Transcript` Codable JSON into structured entries.
    let decodeTranscriptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.decodeTranscript\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decodeTranscriptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jsonArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.decodeTranscript(json: jsonArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      decodeTranscriptChannel.setMessageHandler(nil)
    }
    let createSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.createSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! SessionConfigMessage
        Task { @MainActor in
          do {
            let result = try await api.createSession(config: configArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionChannel.setMessageHandler(nil)
    }
    let respondChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.respond\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      respondChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RespondRequestMessage
        Task { @MainActor in
          do {
            let result = try await api.respond(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      respondChannel.setMessageHandler(nil)
    }
    /// Starts streaming; snapshots arrive through the callback API.
    let startStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.startStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RespondRequestMessage
        Task { @MainActor in
          do {
            try await api.startStream(request: requestArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startStreamChannel.setMessageHandler(nil)
    }
    /// Cancels an in-flight `respond` or stream with this request id.
    let cancelRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.cancelRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.cancelRequest(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRequestChannel.setMessageHandler(nil)
    }
    let prewarmChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.prewarm\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prewarmChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! Int64
        let promptPrefixArg: PromptMessage? = nilOrValue(args[1])
        do {
          try api.prewarm(sessionHandle: sessionHandleArg, promptPrefix: promptPrefixArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      prewarmChannel.setMessageHandler(nil)
    }
    let transcriptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.transcript\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      transcriptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.transcript(sessionHandle: sessionHandleArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      transcriptChannel.setMessageHandler(nil)
    }
    let isRespondingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.isResponding\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isRespondingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! Int64
        do {
          let result = try api.isResponding(sessionHandle: sessionHandleArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isRespondingChannel.setMessageHandler(nil)
    }
    let sessionUsageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.sessionUsage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sessionUsageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! Int64
        do {
          let result = try api.sessionUsage(sessionHandle: sessionHandleArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sessionUsageChannel.setMessageHandler(nil)
    }
    let setTranscriptPolicyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.setTranscriptPolicy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTranscriptPolicyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! Int64
        let policyArg: TranscriptPolicyMessage? = nilOrValue(args[1])
        do {
          try api.setTranscriptPolicy(sessionHandle: sessionHandleArg, policy: policyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTranscriptPolicyChannel.setMessageHandler(nil)
    }
    let logFeedbackAttachmentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.logFeedbackAttachment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logFeedbackAttachmentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionHandleArg = args[0] as! Int64
        let sentimentArg: FeedbackSentimentMessage? = nilOrValue(args[1])
        let issuesArg = args[2] as! [FeedbackIssueMessage]
        let desiredResponseTextArg: String? = nilOrValue(args[3])
        Task { @MainActor in
          do {
            let result = try await api.logFeedbackAttachment(sessionHandle: sessionHandleArg, sentiment: sentimentArg, issues: issuesArg, desiredResponseText: desiredResponseTextArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      logFeedbackAttachmentChannel.setMessageHandler(nil)
    }
    let releaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.release\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        Task { @MainActor in
          do {
            try await api.release(handle: handleArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseChannel.setMessageHandler(nil)
    }
    let releaseAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.releaseAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseAllChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.releaseAll()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseAllChannel.setMessageHandler(nil)
    }
    let liveHandleCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foundation_models.FoundationModelsHostApi.liveHandleCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      liveHandleCountChannel.setMessageHandler { _, reply in
        do {
          let result = try api.liveHandleCount()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      liveHandleCountChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FoundationModelsCallbackApiProtocol {
  /// Runs a Dart-implemented tool.
  @MainActor func callTool(request requestArg: ToolCallRequestMessage) async throws -> ToolResultMessage
  @MainActor func onStreamSnapshot(snapshot snapshotArg: StreamSnapshotMessage) async throws
  @MainActor func onStreamDone(requestId requestIdArg: Int64, response responseArg: ResponseMessage) async throws
  @MainActor func onStreamError(requestId requestIdArg: Int64, error errorArg: ErrorMessage) async throws
}
class FoundationModelsCallbackApi: FoundationModelsCallbackApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Runs a Dart-implemented tool.
  @MainActor func callTool(request requestArg: ToolCallRequestMessage) async throws -> ToolResultMessage {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.foundation_models.FoundationModelsCallbackApi.callTool\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([requestArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: FoundationModelsPigeonError(code: code, message: message, details: details))
        } else if listResponse[0] == nil || listResponse[0] is NSNull {
          continuation.resume(throwing: FoundationModelsPigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: ""))
        } else {
          let result = listResponse[0] as! ToolResultMessage
          continuation.resume(returning: result)
        }
      }
    }
  }
  @MainActor func onStreamSnapshot(snapshot snapshotArg: StreamSnapshotMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.foundation_models.FoundationModelsCallbackApi.onStreamSnapshot\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([snapshotArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: FoundationModelsPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onStreamDone(requestId requestIdArg: Int64, response responseArg: ResponseMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.foundation_models.FoundationModelsCallbackApi.onStreamDone\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([requestIdArg, responseArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: FoundationModelsPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onStreamError(requestId requestIdArg: Int64, error errorArg: ErrorMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.foundation_models.FoundationModelsCallbackApi.onStreamError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([requestIdArg, errorArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: FoundationModelsPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
