name: apple_speech_example
description: "Demonstrates the apple_speech plugin."
publish_to: 'none'

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  apple_speech:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/speech.wav
