// Autogenerated from Pigeon. Do not edit by hand.
// Source: pigeons/apple_speech_api.dart
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Mirrors `SFSpeechRecognizerAuthorizationStatus` and
/// `AVAuthorizationStatus`.
enum AuthorizationStatusMessage {
  notDetermined,
  denied,
  restricted,
  authorized,
}

/// Mirrors `SFSpeechRecognitionTaskHint`.
enum TaskHintMessage { unspecified, dictation, search, confirmation }

/// Where audio comes from.
enum AudioSourceKindMessage {
  /// An audio file read with `AVAudioFile`.
  file,

  /// Any media file (audio or video) read with `AVAsset` (iOS/macOS 27).
  asset,

  /// The default input device, captured with `AVAudioEngine`.
  microphone,

  /// A file fed buffer by buffer through the microphone pipeline (tests).
  simulatedMicrophone,
}

/// The kind of a `SpeechModule`.
enum ModuleKindMessage {
  speechTranscriber,
  dictationTranscriber,
  speechDetector,
}

/// Mirrors `SpeechTranscriber.Preset`.
enum SpeechTranscriberPresetMessage {
  transcription,
  transcriptionWithAlternatives,
  timeIndexedTranscriptionWithAlternatives,
  progressiveTranscription,
  timeIndexedProgressiveTranscription,
}

/// Mirrors `DictationTranscriber.Preset`.
enum DictationPresetMessage {
  phrase,
  shortDictation,
  progressiveShortDictation,
  longDictation,
  progressiveLongDictation,
  timeIndexedLongDictation,
}

/// Mirrors `SpeechTranscriber.TranscriptionOption` and
/// `DictationTranscriber.TranscriptionOption`.
enum TranscriptionOptionMessage { punctuation, emoji, etiquetteReplacements }

/// Mirrors `SpeechTranscriber.ReportingOption` and
/// `DictationTranscriber.ReportingOption`.
enum ReportingOptionMessage {
  volatileResults,
  alternativeTranscriptions,
  fastResults,
  frequentFinalization,
}

/// Mirrors `ResultAttributeOption`.
enum ResultAttributeOptionMessage { audioTimeRange, transcriptionConfidence }

/// Mirrors `DictationTranscriber.ContentHint` (except custom language
/// models).
enum ContentHintMessage { shortForm, farField, atypicalSpeech }

/// Mirrors `SpeechDetector.SensitivityLevel`.
enum SensitivityLevelMessage { low, medium, high }

/// Mirrors `SpeechAnalyzer.Options.ModelRetention`.
enum ModelRetentionMessage { whileInUse, lingering, processLifetime }

/// Mirrors `TaskPriority`.
enum TaskPriorityMessage {
  background,
  utility,
  low,
  medium,
  high,
  userInitiated,
}

/// Mirrors `AssetInventory.Status`.
enum AssetStatusMessage { unsupported, supported, downloading, installed }

/// One word or phrase of a transcription.
class TranscriptionSegmentMessage {
  TranscriptionSegmentMessage({
    required this.text,
    required this.start,
    required this.length,
    this.startTime,
    this.endTime,
    this.confidence,
    required this.alternatives,
  });

  String text;

  /// UTF-16 offset of the segment in the full text.
  int start;

  /// UTF-16 length of the segment in the full text.
  int length;

  /// Seconds from the start of the audio.
  double? startTime;

  double? endTime;

  /// 0...1.
  double? confidence;

  List<String> alternatives;

  List<Object?> _toList() {
    return <Object?>[
      text,
      start,
      length,
      startTime,
      endTime,
      confidence,
      alternatives,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TranscriptionSegmentMessage decode(Object result) {
    result as List<Object?>;
    return TranscriptionSegmentMessage(
      text: result[0]! as String,
      start: result[1]! as int,
      length: result[2]! as int,
      startTime: result[3] as double?,
      endTime: result[4] as double?,
      confidence: result[5] as double?,
      alternatives: (result[6]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TranscriptionSegmentMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) &&
        _deepEquals(start, other.start) &&
        _deepEquals(length, other.length) &&
        _deepEquals(startTime, other.startTime) &&
        _deepEquals(endTime, other.endTime) &&
        _deepEquals(confidence, other.confidence) &&
        _deepEquals(alternatives, other.alternatives);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TranscriptionSegmentMessage(text: $text, start: $start, length: $length, startTime: $startTime, endTime: $endTime, confidence: $confidence, alternatives: $alternatives)';
  }
}

class ErrorMessage {
  ErrorMessage({required this.code, required this.message, this.details});

  String code;

  String message;

  String? details;

  List<Object?> _toList() {
    return <Object?>[code, message, details];
  }

  Object encode() {
    return _toList();
  }

  static ErrorMessage decode(Object result) {
    result as List<Object?>;
    return ErrorMessage(
      code: result[0]! as String,
      message: result[1]! as String,
      details: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ErrorMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) &&
        _deepEquals(message, other.message) &&
        _deepEquals(details, other.details);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ErrorMessage(code: $code, message: $message, details: $details)';
  }
}

class AudioFormatMessage {
  AudioFormatMessage({
    required this.sampleRate,
    required this.channelCount,
    required this.commonFormat,
    required this.isInterleaved,
  });

  double sampleRate;

  int channelCount;

  /// `pcmFormatInt16`, `pcmFormatFloat32`, ... or `other`.
  String commonFormat;

  bool isInterleaved;

  List<Object?> _toList() {
    return <Object?>[sampleRate, channelCount, commonFormat, isInterleaved];
  }

  Object encode() {
    return _toList();
  }

  static AudioFormatMessage decode(Object result) {
    result as List<Object?>;
    return AudioFormatMessage(
      sampleRate: result[0]! as double,
      channelCount: result[1]! as int,
      commonFormat: result[2]! as String,
      isInterleaved: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioFormatMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sampleRate, other.sampleRate) &&
        _deepEquals(channelCount, other.channelCount) &&
        _deepEquals(commonFormat, other.commonFormat) &&
        _deepEquals(isInterleaved, other.isInterleaved);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioFormatMessage(sampleRate: $sampleRate, channelCount: $channelCount, commonFormat: $commonFormat, isInterleaved: $isInterleaved)';
  }
}

class RecognizerInfoMessage {
  RecognizerInfoMessage({
    required this.locale,
    required this.isAvailable,
    required this.supportsOnDeviceRecognition,
    required this.defaultTaskHint,
  });

  String locale;

  bool isAvailable;

  bool supportsOnDeviceRecognition;

  TaskHintMessage defaultTaskHint;

  List<Object?> _toList() {
    return <Object?>[
      locale,
      isAvailable,
      supportsOnDeviceRecognition,
      defaultTaskHint,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RecognizerInfoMessage decode(Object result) {
    result as List<Object?>;
    return RecognizerInfoMessage(
      locale: result[0]! as String,
      isAvailable: result[1]! as bool,
      supportsOnDeviceRecognition: result[2]! as bool,
      defaultTaskHint: result[3]! as TaskHintMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecognizerInfoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(locale, other.locale) &&
        _deepEquals(isAvailable, other.isAvailable) &&
        _deepEquals(
          supportsOnDeviceRecognition,
          other.supportsOnDeviceRecognition,
        ) &&
        _deepEquals(defaultTaskHint, other.defaultTaskHint);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RecognizerInfoMessage(locale: $locale, isAvailable: $isAvailable, supportsOnDeviceRecognition: $supportsOnDeviceRecognition, defaultTaskHint: $defaultTaskHint)';
  }
}

class RecognitionRequestMessage {
  RecognitionRequestMessage({
    required this.requestId,
    this.locale,
    required this.source,
    this.path,
    required this.taskHint,
    required this.shouldReportPartialResults,
    required this.contextualStrings,
    required this.requiresOnDeviceRecognition,
    this.addsPunctuation,
    required this.configureAudioSession,
  });

  int requestId;

  /// Null for the user's current locale.
  String? locale;

  /// `file` or `microphone`.
  AudioSourceKindMessage source;

  String? path;

  TaskHintMessage taskHint;

  bool shouldReportPartialResults;

  List<String> contextualStrings;

  bool requiresOnDeviceRecognition;

  /// iOS 16 / macOS 13; null keeps Apple's default.
  bool? addsPunctuation;

  /// iOS only: activate a recording `AVAudioSession` for the microphone.
  bool configureAudioSession;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      locale,
      source,
      path,
      taskHint,
      shouldReportPartialResults,
      contextualStrings,
      requiresOnDeviceRecognition,
      addsPunctuation,
      configureAudioSession,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RecognitionRequestMessage decode(Object result) {
    result as List<Object?>;
    return RecognitionRequestMessage(
      requestId: result[0]! as int,
      locale: result[1] as String?,
      source: result[2]! as AudioSourceKindMessage,
      path: result[3] as String?,
      taskHint: result[4]! as TaskHintMessage,
      shouldReportPartialResults: result[5]! as bool,
      contextualStrings: (result[6]! as List<Object?>).cast<String>(),
      requiresOnDeviceRecognition: result[7]! as bool,
      addsPunctuation: result[8] as bool?,
      configureAudioSession: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecognitionRequestMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) &&
        _deepEquals(locale, other.locale) &&
        _deepEquals(source, other.source) &&
        _deepEquals(path, other.path) &&
        _deepEquals(taskHint, other.taskHint) &&
        _deepEquals(
          shouldReportPartialResults,
          other.shouldReportPartialResults,
        ) &&
        _deepEquals(contextualStrings, other.contextualStrings) &&
        _deepEquals(
          requiresOnDeviceRecognition,
          other.requiresOnDeviceRecognition,
        ) &&
        _deepEquals(addsPunctuation, other.addsPunctuation) &&
        _deepEquals(configureAudioSession, other.configureAudioSession);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RecognitionRequestMessage(requestId: $requestId, locale: $locale, source: $source, path: $path, taskHint: $taskHint, shouldReportPartialResults: $shouldReportPartialResults, contextualStrings: $contextualStrings, requiresOnDeviceRecognition: $requiresOnDeviceRecognition, addsPunctuation: $addsPunctuation, configureAudioSession: $configureAudioSession)';
  }
}

class TranscriptionMessage {
  TranscriptionMessage({required this.formattedString, required this.segments});

  String formattedString;

  List<TranscriptionSegmentMessage> segments;

  List<Object?> _toList() {
    return <Object?>[formattedString, segments];
  }

  Object encode() {
    return _toList();
  }

  static TranscriptionMessage decode(Object result) {
    result as List<Object?>;
    return TranscriptionMessage(
      formattedString: result[0]! as String,
      segments: (result[1]! as List<Object?>)
          .cast<TranscriptionSegmentMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TranscriptionMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(formattedString, other.formattedString) &&
        _deepEquals(segments, other.segments);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TranscriptionMessage(formattedString: $formattedString, segments: $segments)';
  }
}

class RecognitionMetadataMessage {
  RecognitionMetadataMessage({
    required this.speakingRate,
    required this.averagePauseDuration,
    required this.speechStartTimestamp,
    required this.speechDuration,
  });

  double speakingRate;

  double averagePauseDuration;

  double speechStartTimestamp;

  double speechDuration;

  List<Object?> _toList() {
    return <Object?>[
      speakingRate,
      averagePauseDuration,
      speechStartTimestamp,
      speechDuration,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RecognitionMetadataMessage decode(Object result) {
    result as List<Object?>;
    return RecognitionMetadataMessage(
      speakingRate: result[0]! as double,
      averagePauseDuration: result[1]! as double,
      speechStartTimestamp: result[2]! as double,
      speechDuration: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecognitionMetadataMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(speakingRate, other.speakingRate) &&
        _deepEquals(averagePauseDuration, other.averagePauseDuration) &&
        _deepEquals(speechStartTimestamp, other.speechStartTimestamp) &&
        _deepEquals(speechDuration, other.speechDuration);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RecognitionMetadataMessage(speakingRate: $speakingRate, averagePauseDuration: $averagePauseDuration, speechStartTimestamp: $speechStartTimestamp, speechDuration: $speechDuration)';
  }
}

class RecognitionResultMessage {
  RecognitionResultMessage({
    required this.requestId,
    required this.bestTranscription,
    required this.transcriptions,
    required this.isFinal,
    this.metadata,
  });

  int requestId;

  TranscriptionMessage bestTranscription;

  List<TranscriptionMessage> transcriptions;

  bool isFinal;

  RecognitionMetadataMessage? metadata;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      bestTranscription,
      transcriptions,
      isFinal,
      metadata,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RecognitionResultMessage decode(Object result) {
    result as List<Object?>;
    return RecognitionResultMessage(
      requestId: result[0]! as int,
      bestTranscription: result[1]! as TranscriptionMessage,
      transcriptions: (result[2]! as List<Object?>)
          .cast<TranscriptionMessage>(),
      isFinal: result[3]! as bool,
      metadata: result[4] as RecognitionMetadataMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecognitionResultMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) &&
        _deepEquals(bestTranscription, other.bestTranscription) &&
        _deepEquals(transcriptions, other.transcriptions) &&
        _deepEquals(isFinal, other.isFinal) &&
        _deepEquals(metadata, other.metadata);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RecognitionResultMessage(requestId: $requestId, bestTranscription: $bestTranscription, transcriptions: $transcriptions, isFinal: $isFinal, metadata: $metadata)';
  }
}

/// A `SpeechTranscriber`, `DictationTranscriber` or `SpeechDetector`.
class ModuleConfigMessage {
  ModuleConfigMessage({
    required this.kind,
    this.locale,
    this.speechPreset,
    this.dictationPreset,
    required this.transcriptionOptions,
    required this.reportingOptions,
    required this.attributeOptions,
    required this.contentHints,
    this.sensitivityLevel,
    this.reportResults,
  });

  ModuleKindMessage kind;

  /// Transcribers only.
  String? locale;

  /// When set, used instead of the option lists.
  SpeechTranscriberPresetMessage? speechPreset;

  DictationPresetMessage? dictationPreset;

  List<TranscriptionOptionMessage> transcriptionOptions;

  List<ReportingOptionMessage> reportingOptions;

  List<ResultAttributeOptionMessage> attributeOptions;

  List<ContentHintMessage> contentHints;

  /// Detector only.
  SensitivityLevelMessage? sensitivityLevel;

  bool? reportResults;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      locale,
      speechPreset,
      dictationPreset,
      transcriptionOptions,
      reportingOptions,
      attributeOptions,
      contentHints,
      sensitivityLevel,
      reportResults,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ModuleConfigMessage decode(Object result) {
    result as List<Object?>;
    return ModuleConfigMessage(
      kind: result[0]! as ModuleKindMessage,
      locale: result[1] as String?,
      speechPreset: result[2] as SpeechTranscriberPresetMessage?,
      dictationPreset: result[3] as DictationPresetMessage?,
      transcriptionOptions: (result[4]! as List<Object?>)
          .cast<TranscriptionOptionMessage>(),
      reportingOptions: (result[5]! as List<Object?>)
          .cast<ReportingOptionMessage>(),
      attributeOptions: (result[6]! as List<Object?>)
          .cast<ResultAttributeOptionMessage>(),
      contentHints: (result[7]! as List<Object?>).cast<ContentHintMessage>(),
      sensitivityLevel: result[8] as SensitivityLevelMessage?,
      reportResults: result[9] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ModuleConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(locale, other.locale) &&
        _deepEquals(speechPreset, other.speechPreset) &&
        _deepEquals(dictationPreset, other.dictationPreset) &&
        _deepEquals(transcriptionOptions, other.transcriptionOptions) &&
        _deepEquals(reportingOptions, other.reportingOptions) &&
        _deepEquals(attributeOptions, other.attributeOptions) &&
        _deepEquals(contentHints, other.contentHints) &&
        _deepEquals(sensitivityLevel, other.sensitivityLevel) &&
        _deepEquals(reportResults, other.reportResults);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ModuleConfigMessage(kind: $kind, locale: $locale, speechPreset: $speechPreset, dictationPreset: $dictationPreset, transcriptionOptions: $transcriptionOptions, reportingOptions: $reportingOptions, attributeOptions: $attributeOptions, contentHints: $contentHints, sensitivityLevel: $sensitivityLevel, reportResults: $reportResults)';
  }
}

class AnalyzerOptionsMessage {
  AnalyzerOptionsMessage({
    required this.priority,
    required this.modelRetention,
    this.ignoresResourceLimits,
  });

  TaskPriorityMessage priority;

  ModelRetentionMessage modelRetention;

  /// iOS/macOS 27.
  bool? ignoresResourceLimits;

  List<Object?> _toList() {
    return <Object?>[priority, modelRetention, ignoresResourceLimits];
  }

  Object encode() {
    return _toList();
  }

  static AnalyzerOptionsMessage decode(Object result) {
    result as List<Object?>;
    return AnalyzerOptionsMessage(
      priority: result[0]! as TaskPriorityMessage,
      modelRetention: result[1]! as ModelRetentionMessage,
      ignoresResourceLimits: result[2] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AnalyzerOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(priority, other.priority) &&
        _deepEquals(modelRetention, other.modelRetention) &&
        _deepEquals(ignoresResourceLimits, other.ignoresResourceLimits);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AnalyzerOptionsMessage(priority: $priority, modelRetention: $modelRetention, ignoresResourceLimits: $ignoresResourceLimits)';
  }
}

class AnalysisRequestMessage {
  AnalysisRequestMessage({
    required this.requestId,
    required this.source,
    this.path,
    required this.modules,
    this.options,
    required this.contextualStrings,
    required this.configureAudioSession,
  });

  int requestId;

  AudioSourceKindMessage source;

  String? path;

  List<ModuleConfigMessage> modules;

  AnalyzerOptionsMessage? options;

  /// `AnalysisContext.contextualStrings`, keyed by tag (e.g. "general").
  Map<String, List<String>> contextualStrings;

  /// iOS only: activate a recording `AVAudioSession` for the microphone.
  bool configureAudioSession;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      source,
      path,
      modules,
      options,
      contextualStrings,
      configureAudioSession,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AnalysisRequestMessage decode(Object result) {
    result as List<Object?>;
    return AnalysisRequestMessage(
      requestId: result[0]! as int,
      source: result[1]! as AudioSourceKindMessage,
      path: result[2] as String?,
      modules: (result[3]! as List<Object?>).cast<ModuleConfigMessage>(),
      options: result[4] as AnalyzerOptionsMessage?,
      contextualStrings: (result[5]! as Map<Object?, Object?>)
          .cast<String, List<String>>(),
      configureAudioSession: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AnalysisRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) &&
        _deepEquals(source, other.source) &&
        _deepEquals(path, other.path) &&
        _deepEquals(modules, other.modules) &&
        _deepEquals(options, other.options) &&
        _deepEquals(contextualStrings, other.contextualStrings) &&
        _deepEquals(configureAudioSession, other.configureAudioSession);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AnalysisRequestMessage(requestId: $requestId, source: $source, path: $path, modules: $modules, options: $options, contextualStrings: $contextualStrings, configureAudioSession: $configureAudioSession)';
  }
}

/// A result from one module of an analysis.
class AnalyzerResultMessage {
  AnalyzerResultMessage({
    required this.requestId,
    required this.moduleIndex,
    required this.rangeStart,
    required this.rangeEnd,
    required this.resultsFinalizationTime,
    required this.isFinal,
    this.text,
    required this.segments,
    required this.alternatives,
    this.speechDetected,
  });

  int requestId;

  /// Index into `AnalysisRequestMessage.modules`.
  int moduleIndex;

  double rangeStart;

  double rangeEnd;

  double resultsFinalizationTime;

  bool isFinal;

  /// Transcribers: the transcribed text.
  String? text;

  /// Transcribers: the runs of `text` with their attributes.
  List<TranscriptionSegmentMessage> segments;

  /// Transcribers: alternative transcriptions, best first.
  List<String> alternatives;

  /// Detector: whether speech was detected in the range.
  bool? speechDetected;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      moduleIndex,
      rangeStart,
      rangeEnd,
      resultsFinalizationTime,
      isFinal,
      text,
      segments,
      alternatives,
      speechDetected,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AnalyzerResultMessage decode(Object result) {
    result as List<Object?>;
    return AnalyzerResultMessage(
      requestId: result[0]! as int,
      moduleIndex: result[1]! as int,
      rangeStart: result[2]! as double,
      rangeEnd: result[3]! as double,
      resultsFinalizationTime: result[4]! as double,
      isFinal: result[5]! as bool,
      text: result[6] as String?,
      segments: (result[7]! as List<Object?>)
          .cast<TranscriptionSegmentMessage>(),
      alternatives: (result[8]! as List<Object?>).cast<String>(),
      speechDetected: result[9] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AnalyzerResultMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) &&
        _deepEquals(moduleIndex, other.moduleIndex) &&
        _deepEquals(rangeStart, other.rangeStart) &&
        _deepEquals(rangeEnd, other.rangeEnd) &&
        _deepEquals(resultsFinalizationTime, other.resultsFinalizationTime) &&
        _deepEquals(isFinal, other.isFinal) &&
        _deepEquals(text, other.text) &&
        _deepEquals(segments, other.segments) &&
        _deepEquals(alternatives, other.alternatives) &&
        _deepEquals(speechDetected, other.speechDetected);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AnalyzerResultMessage(requestId: $requestId, moduleIndex: $moduleIndex, rangeStart: $rangeStart, rangeEnd: $rangeEnd, resultsFinalizationTime: $resultsFinalizationTime, isFinal: $isFinal, text: $text, segments: $segments, alternatives: $alternatives, speechDetected: $speechDetected)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AuthorizationStatusMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is TaskHintMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is AudioSourceKindMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is ModuleKindMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is SpeechTranscriberPresetMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is DictationPresetMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is TranscriptionOptionMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is ReportingOptionMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is ResultAttributeOptionMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is ContentHintMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is SensitivityLevelMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    } else if (value is ModelRetentionMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    } else if (value is TaskPriorityMessage) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    } else if (value is AssetStatusMessage) {
      buffer.putUint8(142);
      writeValue(buffer, value.index);
    } else if (value is TranscriptionSegmentMessage) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is ErrorMessage) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is AudioFormatMessage) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is RecognizerInfoMessage) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is RecognitionRequestMessage) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is TranscriptionMessage) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is RecognitionMetadataMessage) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is RecognitionResultMessage) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is ModuleConfigMessage) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is AnalyzerOptionsMessage) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is AnalysisRequestMessage) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is AnalyzerResultMessage) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AuthorizationStatusMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : TaskHintMessage.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AudioSourceKindMessage.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : ModuleKindMessage.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : SpeechTranscriberPresetMessage.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : DictationPresetMessage.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : TranscriptionOptionMessage.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : ReportingOptionMessage.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : ResultAttributeOptionMessage.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : ContentHintMessage.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : SensitivityLevelMessage.values[value];
      case 140:
        final value = readValue(buffer) as int?;
        return value == null ? null : ModelRetentionMessage.values[value];
      case 141:
        final value = readValue(buffer) as int?;
        return value == null ? null : TaskPriorityMessage.values[value];
      case 142:
        final value = readValue(buffer) as int?;
        return value == null ? null : AssetStatusMessage.values[value];
      case 143:
        return TranscriptionSegmentMessage.decode(readValue(buffer)!);
      case 144:
        return ErrorMessage.decode(readValue(buffer)!);
      case 145:
        return AudioFormatMessage.decode(readValue(buffer)!);
      case 146:
        return RecognizerInfoMessage.decode(readValue(buffer)!);
      case 147:
        return RecognitionRequestMessage.decode(readValue(buffer)!);
      case 148:
        return TranscriptionMessage.decode(readValue(buffer)!);
      case 149:
        return RecognitionMetadataMessage.decode(readValue(buffer)!);
      case 150:
        return RecognitionResultMessage.decode(readValue(buffer)!);
      case 151:
        return ModuleConfigMessage.decode(readValue(buffer)!);
      case 152:
        return AnalyzerOptionsMessage.decode(readValue(buffer)!);
      case 153:
        return AnalysisRequestMessage.decode(readValue(buffer)!);
      case 154:
        return AnalyzerResultMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Always available.
class AppleSpeechPlatformApi {
  /// Constructor for [AppleSpeechPlatformApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppleSpeechPlatformApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Whether the Speech framework is available (`SFSpeechRecognizer`).
  Future<bool> isSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechPlatformApi.isSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Whether `SpeechAnalyzer` is available (iOS/macOS 26+).
  Future<bool> isAnalyzerSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechPlatformApi.isAnalyzerSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Whether iOS/macOS 27 additions are available.
  Future<bool> isVersion27Supported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechPlatformApi.isVersion27Supported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Registered when the Speech framework can be imported.
class AppleSpeechHostApi {
  /// Constructor for [AppleSpeechHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppleSpeechHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AuthorizationStatusMessage> speechAuthorizationStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.speechAuthorizationStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AuthorizationStatusMessage;
  }

  Future<AuthorizationStatusMessage> requestSpeechAuthorization() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.requestSpeechAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AuthorizationStatusMessage;
  }

  Future<AuthorizationStatusMessage> microphoneAuthorizationStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.microphoneAuthorizationStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AuthorizationStatusMessage;
  }

  Future<AuthorizationStatusMessage> requestMicrophoneAuthorization() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.requestMicrophoneAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AuthorizationStatusMessage;
  }

  Future<List<String>> recognizerSupportedLocales() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.recognizerSupportedLocales$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Null when no recognizer exists for [locale].
  Future<RecognizerInfoMessage?> recognizerInfo(String? locale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.recognizerInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[locale],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as RecognizerInfoMessage?;
  }

  /// Starts recognition; results arrive through the callback API.
  Future<void> startRecognition(RecognitionRequestMessage request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.startRecognition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> speechTranscriberIsAvailable() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.speechTranscriberIsAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<List<String>> supportedLocales(ModuleKindMessage kind) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.supportedLocales$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[kind],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<List<String>> installedLocales(ModuleKindMessage kind) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.installedLocales$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[kind],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<String?> supportedLocaleEquivalent(
    ModuleKindMessage kind,
    String locale,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.supportedLocaleEquivalent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[kind, locale],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<AssetStatusMessage> assetStatus(
    List<ModuleConfigMessage> modules,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.assetStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[modules],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AssetStatusMessage;
  }

  /// Downloads and installs assets; returns false when nothing was needed.
  /// Progress arrives through `onInstallProgress`.
  Future<bool> installAssets(
    int requestId,
    List<ModuleConfigMessage> modules,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.installAssets$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId, modules],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<List<String>> reservedLocales() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.reservedLocales$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<int> maximumReservedLocales() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.maximumReservedLocales$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<bool> reserveLocale(String locale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.reserveLocale$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[locale],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> releaseLocale(String locale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.releaseLocale$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[locale],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<AudioFormatMessage?> bestAvailableAudioFormat(
    List<ModuleConfigMessage> modules,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.bestAvailableAudioFormat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[modules],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as AudioFormatMessage?;
  }

  /// Starts an analysis; results arrive through the callback API.
  Future<void> startAnalysis(AnalysisRequestMessage request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.startAnalysis$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> endModelRetention() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.endModelRetention$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Ends live input (stops the microphone) and finalizes the results.
  Future<void> finishRequest(int requestId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.finishRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Cancels a request. No further events are sent for it.
  Future<void> cancelRequest(int requestId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.cancelRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Cancels every request; returns how many were active.
  Future<int> cancelAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.cancelAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<int> activeRequestCount() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.activeRequestCount$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }
}

/// Native -> Dart.
abstract class AppleSpeechCallbackApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAnalyzerResult(AnalyzerResultMessage result);

  void onRecognitionResult(RecognitionResultMessage result);

  void onInstallProgress(int requestId, double fractionCompleted);

  /// The request finished. For analyses, [lastSampleTime] is the end of the
  /// analyzed audio in seconds.
  void onRequestDone(int requestId, double? lastSampleTime);

  void onRequestError(int requestId, ErrorMessage error);

  static void setUp(
    AppleSpeechCallbackApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onAnalyzerResult$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AnalyzerResultMessage arg_result =
              args[0]! as AnalyzerResultMessage;
          try {
            api.onAnalyzerResult(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onRecognitionResult$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final RecognitionResultMessage arg_result =
              args[0]! as RecognitionResultMessage;
          try {
            api.onRecognitionResult(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onInstallProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_requestId = args[0]! as int;
          final double arg_fractionCompleted = args[1]! as double;
          try {
            api.onInstallProgress(arg_requestId, arg_fractionCompleted);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onRequestDone$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_requestId = args[0]! as int;
          final double? arg_lastSampleTime = args[1] as double?;
          try {
            api.onRequestDone(arg_requestId, arg_lastSampleTime);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onRequestError$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_requestId = args[0]! as int;
          final ErrorMessage arg_error = args[1]! as ErrorMessage;
          try {
            api.onRequestError(arg_requestId, arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
