// Autogenerated from Pigeon. Do not edit by hand.
// Source: pigeons/apple_natural_language_api.dart
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Mirrors `NLTokenUnit`.
enum TokenUnitMessage { word, sentence, paragraph, document }

/// Mirrors `NLTagScheme`.
enum TagSchemeMessage {
  tokenType,
  lexicalClass,
  nameType,
  nameTypeOrLexicalClass,
  lemma,
  language,
  script,
  sentimentScore,
}

/// Mirrors `NLTaggerOptions`.
enum TagOptionMessage {
  omitWords,
  omitPunctuation,
  omitWhitespace,
  omitOther,
  joinNames,
  joinContractions,
}

/// Mirrors `NLTokenizerAttributes`.
enum TokenAttributeMessage { numeric, symbolic, emoji }

/// Mirrors `NLDistanceType`.
enum DistanceTypeMessage { cosine }

/// Mirrors `NLModelType`.
enum ModelTypeMessage { classifier, sequence }

/// Mirrors `NLTaggerAssetsResult` / `NLContextualEmbeddingAssetsResult`.
enum AssetsResultMessage { available, notAvailable, error }

class TokenMessage {
  TokenMessage({
    required this.start,
    required this.length,
    required this.attributes,
  });

  int start;

  int length;

  List<TokenAttributeMessage> attributes;

  List<Object?> _toList() {
    return <Object?>[start, length, attributes];
  }

  Object encode() {
    return _toList();
  }

  static TokenMessage decode(Object result) {
    result as List<Object?>;
    return TokenMessage(
      start: result[0]! as int,
      length: result[1]! as int,
      attributes: (result[2]! as List<Object?>).cast<TokenAttributeMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TokenMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(start, other.start) &&
        _deepEquals(length, other.length) &&
        _deepEquals(attributes, other.attributes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TokenMessage(start: $start, length: $length, attributes: $attributes)';
  }
}

class TagMessage {
  TagMessage({required this.start, required this.length, this.tag});

  int start;

  int length;

  /// Null when the tagger had no tag for the token.
  String? tag;

  List<Object?> _toList() {
    return <Object?>[start, length, tag];
  }

  Object encode() {
    return _toList();
  }

  static TagMessage decode(Object result) {
    result as List<Object?>;
    return TagMessage(
      start: result[0]! as int,
      length: result[1]! as int,
      tag: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TagMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(start, other.start) &&
        _deepEquals(length, other.length) &&
        _deepEquals(tag, other.tag);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TagMessage(start: $start, length: $length, tag: $tag)';
  }
}

class LanguageHypothesisMessage {
  LanguageHypothesisMessage({required this.language, required this.confidence});

  String language;

  double confidence;

  List<Object?> _toList() {
    return <Object?>[language, confidence];
  }

  Object encode() {
    return _toList();
  }

  static LanguageHypothesisMessage decode(Object result) {
    result as List<Object?>;
    return LanguageHypothesisMessage(
      language: result[0]! as String,
      confidence: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LanguageHypothesisMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(language, other.language) &&
        _deepEquals(confidence, other.confidence);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LanguageHypothesisMessage(language: $language, confidence: $confidence)';
  }
}

class TagHypothesisMessage {
  TagHypothesisMessage({required this.tag, required this.confidence});

  String tag;

  double confidence;

  List<Object?> _toList() {
    return <Object?>[tag, confidence];
  }

  Object encode() {
    return _toList();
  }

  static TagHypothesisMessage decode(Object result) {
    result as List<Object?>;
    return TagHypothesisMessage(
      tag: result[0]! as String,
      confidence: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TagHypothesisMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(tag, other.tag) &&
        _deepEquals(confidence, other.confidence);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TagHypothesisMessage(tag: $tag, confidence: $confidence)';
  }
}

class EmbeddingInfoMessage {
  EmbeddingInfoMessage({
    required this.handle,
    required this.dimension,
    required this.vocabularySize,
    this.language,
    required this.revision,
  });

  int handle;

  int dimension;

  int vocabularySize;

  String? language;

  int revision;

  List<Object?> _toList() {
    return <Object?>[handle, dimension, vocabularySize, language, revision];
  }

  Object encode() {
    return _toList();
  }

  static EmbeddingInfoMessage decode(Object result) {
    result as List<Object?>;
    return EmbeddingInfoMessage(
      handle: result[0]! as int,
      dimension: result[1]! as int,
      vocabularySize: result[2]! as int,
      language: result[3] as String?,
      revision: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EmbeddingInfoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(handle, other.handle) &&
        _deepEquals(dimension, other.dimension) &&
        _deepEquals(vocabularySize, other.vocabularySize) &&
        _deepEquals(language, other.language) &&
        _deepEquals(revision, other.revision);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EmbeddingInfoMessage(handle: $handle, dimension: $dimension, vocabularySize: $vocabularySize, language: $language, revision: $revision)';
  }
}

class NeighborMessage {
  NeighborMessage({required this.text, required this.distance});

  String text;

  double distance;

  List<Object?> _toList() {
    return <Object?>[text, distance];
  }

  Object encode() {
    return _toList();
  }

  static NeighborMessage decode(Object result) {
    result as List<Object?>;
    return NeighborMessage(
      text: result[0]! as String,
      distance: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NeighborMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) &&
        _deepEquals(distance, other.distance);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NeighborMessage(text: $text, distance: $distance)';
  }
}

class ContextualEmbeddingInfoMessage {
  ContextualEmbeddingInfoMessage({
    required this.handle,
    required this.modelIdentifier,
    required this.languages,
    required this.scripts,
    required this.revision,
    required this.dimension,
    required this.maximumSequenceLength,
    required this.hasAvailableAssets,
  });

  int handle;

  String modelIdentifier;

  List<String> languages;

  List<String> scripts;

  int revision;

  int dimension;

  int maximumSequenceLength;

  bool hasAvailableAssets;

  List<Object?> _toList() {
    return <Object?>[
      handle,
      modelIdentifier,
      languages,
      scripts,
      revision,
      dimension,
      maximumSequenceLength,
      hasAvailableAssets,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ContextualEmbeddingInfoMessage decode(Object result) {
    result as List<Object?>;
    return ContextualEmbeddingInfoMessage(
      handle: result[0]! as int,
      modelIdentifier: result[1]! as String,
      languages: (result[2]! as List<Object?>).cast<String>(),
      scripts: (result[3]! as List<Object?>).cast<String>(),
      revision: result[4]! as int,
      dimension: result[5]! as int,
      maximumSequenceLength: result[6]! as int,
      hasAvailableAssets: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ContextualEmbeddingInfoMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(handle, other.handle) &&
        _deepEquals(modelIdentifier, other.modelIdentifier) &&
        _deepEquals(languages, other.languages) &&
        _deepEquals(scripts, other.scripts) &&
        _deepEquals(revision, other.revision) &&
        _deepEquals(dimension, other.dimension) &&
        _deepEquals(maximumSequenceLength, other.maximumSequenceLength) &&
        _deepEquals(hasAvailableAssets, other.hasAvailableAssets);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ContextualEmbeddingInfoMessage(handle: $handle, modelIdentifier: $modelIdentifier, languages: $languages, scripts: $scripts, revision: $revision, dimension: $dimension, maximumSequenceLength: $maximumSequenceLength, hasAvailableAssets: $hasAvailableAssets)';
  }
}

class TokenVectorMessage {
  TokenVectorMessage({
    required this.start,
    required this.length,
    required this.vector,
  });

  int start;

  int length;

  /// The token's embedding, `dimension` values long.
  Float64List vector;

  List<Object?> _toList() {
    return <Object?>[start, length, vector];
  }

  Object encode() {
    return _toList();
  }

  static TokenVectorMessage decode(Object result) {
    result as List<Object?>;
    return TokenVectorMessage(
      start: result[0]! as int,
      length: result[1]! as int,
      vector: result[2]! as Float64List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TokenVectorMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(start, other.start) &&
        _deepEquals(length, other.length) &&
        _deepEquals(vector, other.vector);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TokenVectorMessage(start: $start, length: $length, vector: $vector)';
  }
}

class ContextualEmbeddingResultMessage {
  ContextualEmbeddingResultMessage({
    required this.language,
    required this.sequenceLength,
    required this.tokens,
  });

  String language;

  int sequenceLength;

  List<TokenVectorMessage> tokens;

  List<Object?> _toList() {
    return <Object?>[language, sequenceLength, tokens];
  }

  Object encode() {
    return _toList();
  }

  static ContextualEmbeddingResultMessage decode(Object result) {
    result as List<Object?>;
    return ContextualEmbeddingResultMessage(
      language: result[0]! as String,
      sequenceLength: result[1]! as int,
      tokens: (result[2]! as List<Object?>).cast<TokenVectorMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ContextualEmbeddingResultMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(language, other.language) &&
        _deepEquals(sequenceLength, other.sequenceLength) &&
        _deepEquals(tokens, other.tokens);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ContextualEmbeddingResultMessage(language: $language, sequenceLength: $sequenceLength, tokens: $tokens)';
  }
}

class ModelInfoMessage {
  ModelInfoMessage({
    required this.handle,
    required this.type,
    this.language,
    required this.revision,
  });

  int handle;

  ModelTypeMessage type;

  String? language;

  int revision;

  List<Object?> _toList() {
    return <Object?>[handle, type, language, revision];
  }

  Object encode() {
    return _toList();
  }

  static ModelInfoMessage decode(Object result) {
    result as List<Object?>;
    return ModelInfoMessage(
      handle: result[0]! as int,
      type: result[1]! as ModelTypeMessage,
      language: result[2] as String?,
      revision: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ModelInfoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(handle, other.handle) &&
        _deepEquals(type, other.type) &&
        _deepEquals(language, other.language) &&
        _deepEquals(revision, other.revision);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ModelInfoMessage(handle: $handle, type: $type, language: $language, revision: $revision)';
  }
}

class LabelHypothesisMessage {
  LabelHypothesisMessage({required this.label, required this.confidence});

  String label;

  double confidence;

  List<Object?> _toList() {
    return <Object?>[label, confidence];
  }

  Object encode() {
    return _toList();
  }

  static LabelHypothesisMessage decode(Object result) {
    result as List<Object?>;
    return LabelHypothesisMessage(
      label: result[0]! as String,
      confidence: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LabelHypothesisMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(label, other.label) &&
        _deepEquals(confidence, other.confidence);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LabelHypothesisMessage(label: $label, confidence: $confidence)';
  }
}

class TagRequestMessage {
  TagRequestMessage({
    required this.text,
    required this.scheme,
    required this.unit,
    required this.options,
    this.language,
    required this.modelHandles,
    required this.gazetteerHandles,
  });

  String text;

  TagSchemeMessage scheme;

  TokenUnitMessage unit;

  List<TagOptionMessage> options;

  /// Forces the language instead of detecting it.
  String? language;

  /// Custom `NLModel`s to use for this scheme.
  List<int> modelHandles;

  /// Custom `NLGazetteer`s to use for this scheme.
  List<int> gazetteerHandles;

  List<Object?> _toList() {
    return <Object?>[
      text,
      scheme,
      unit,
      options,
      language,
      modelHandles,
      gazetteerHandles,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TagRequestMessage decode(Object result) {
    result as List<Object?>;
    return TagRequestMessage(
      text: result[0]! as String,
      scheme: result[1]! as TagSchemeMessage,
      unit: result[2]! as TokenUnitMessage,
      options: (result[3]! as List<Object?>).cast<TagOptionMessage>(),
      language: result[4] as String?,
      modelHandles: (result[5]! as List<Object?>).cast<int>(),
      gazetteerHandles: (result[6]! as List<Object?>).cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TagRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) &&
        _deepEquals(scheme, other.scheme) &&
        _deepEquals(unit, other.unit) &&
        _deepEquals(options, other.options) &&
        _deepEquals(language, other.language) &&
        _deepEquals(modelHandles, other.modelHandles) &&
        _deepEquals(gazetteerHandles, other.gazetteerHandles);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TagRequestMessage(text: $text, scheme: $scheme, unit: $unit, options: $options, language: $language, modelHandles: $modelHandles, gazetteerHandles: $gazetteerHandles)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is TokenUnitMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is TagSchemeMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is TagOptionMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is TokenAttributeMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is DistanceTypeMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is ModelTypeMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is AssetsResultMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is TokenMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is TagMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is LanguageHypothesisMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is TagHypothesisMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is EmbeddingInfoMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is NeighborMessage) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is ContextualEmbeddingInfoMessage) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is TokenVectorMessage) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is ContextualEmbeddingResultMessage) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is ModelInfoMessage) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is LabelHypothesisMessage) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is TagRequestMessage) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : TokenUnitMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : TagSchemeMessage.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : TagOptionMessage.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : TokenAttributeMessage.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : DistanceTypeMessage.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : ModelTypeMessage.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : AssetsResultMessage.values[value];
      case 136:
        return TokenMessage.decode(readValue(buffer)!);
      case 137:
        return TagMessage.decode(readValue(buffer)!);
      case 138:
        return LanguageHypothesisMessage.decode(readValue(buffer)!);
      case 139:
        return TagHypothesisMessage.decode(readValue(buffer)!);
      case 140:
        return EmbeddingInfoMessage.decode(readValue(buffer)!);
      case 141:
        return NeighborMessage.decode(readValue(buffer)!);
      case 142:
        return ContextualEmbeddingInfoMessage.decode(readValue(buffer)!);
      case 143:
        return TokenVectorMessage.decode(readValue(buffer)!);
      case 144:
        return ContextualEmbeddingResultMessage.decode(readValue(buffer)!);
      case 145:
        return ModelInfoMessage.decode(readValue(buffer)!);
      case 146:
        return LabelHypothesisMessage.decode(readValue(buffer)!);
      case 147:
        return TagRequestMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Always available.
class AppleNaturalLanguagePlatformApi {
  /// Constructor for [AppleNaturalLanguagePlatformApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppleNaturalLanguagePlatformApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Whether the Natural Language framework is available.
  Future<bool> isSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguagePlatformApi.isSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Registered only when the framework is available.
class AppleNaturalLanguageHostApi {
  /// Constructor for [AppleNaturalLanguageHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppleNaturalLanguageHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String?> dominantLanguage(String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.dominantLanguage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<List<LanguageHypothesisMessage>> languageHypotheses(
    String text,
    int maximumCount,
    Map<String, double> hints,
    List<String> constraints,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.languageHypotheses$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text, maximumCount, hints, constraints],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<LanguageHypothesisMessage>();
  }

  Future<List<TokenMessage>> tokenize(
    String text,
    TokenUnitMessage unit,
    String? language,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.tokenize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text, unit, language],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<TokenMessage>();
  }

  Future<List<TagMessage>> tags(TagRequestMessage request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.tags$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<TagMessage>();
  }

  Future<List<TagHypothesisMessage>> tagHypotheses(
    String text,
    int characterIndex,
    TagSchemeMessage scheme,
    TokenUnitMessage unit,
    int maximumCount,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.tagHypotheses$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text, characterIndex, scheme, unit, maximumCount],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<TagHypothesisMessage>();
  }

  Future<List<String>> availableTagSchemes(
    TokenUnitMessage unit,
    String language,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.availableTagSchemes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[unit, language],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<AssetsResultMessage> requestTaggerAssets(
    String language,
    TagSchemeMessage scheme,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.requestTaggerAssets$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[language, scheme],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AssetsResultMessage;
  }

  Future<EmbeddingInfoMessage> loadWordEmbedding(
    String language,
    int? revision,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.loadWordEmbedding$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[language, revision],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as EmbeddingInfoMessage;
  }

  Future<EmbeddingInfoMessage> loadSentenceEmbedding(
    String language,
    int? revision,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.loadSentenceEmbedding$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[language, revision],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as EmbeddingInfoMessage;
  }

  Future<EmbeddingInfoMessage> loadEmbeddingFromFile(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.loadEmbeddingFromFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as EmbeddingInfoMessage;
  }

  Future<Float64List?> embeddingVector(int handle, String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.embeddingVector$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as Float64List?;
  }

  Future<double> embeddingDistance(
    int handle,
    String first,
    String second,
    DistanceTypeMessage distanceType,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.embeddingDistance$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, first, second, distanceType],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as double;
  }

  Future<bool> embeddingContains(int handle, String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.embeddingContains$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<List<NeighborMessage>> embeddingNeighbors(
    int handle,
    String text,
    int maximumCount,
    double? maximumDistance,
    DistanceTypeMessage distanceType,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.embeddingNeighbors$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, text, maximumCount, maximumDistance, distanceType],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<NeighborMessage>();
  }

  Future<List<NeighborMessage>> embeddingNeighborsForVector(
    int handle,
    Float64List vector,
    int maximumCount,
    double? maximumDistance,
    DistanceTypeMessage distanceType,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.embeddingNeighborsForVector$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, vector, maximumCount, maximumDistance, distanceType],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<NeighborMessage>();
  }

  Future<ContextualEmbeddingInfoMessage> loadContextualEmbedding(
    String? modelIdentifier,
    String? language,
    String? script,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.loadContextualEmbedding$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[modelIdentifier, language, script],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ContextualEmbeddingInfoMessage;
  }

  Future<AssetsResultMessage> requestContextualEmbeddingAssets(
    int handle,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.requestContextualEmbeddingAssets$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AssetsResultMessage;
  }

  Future<ContextualEmbeddingResultMessage> contextualEmbeddingResult(
    int handle,
    String text,
    String? language,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.contextualEmbeddingResult$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, text, language],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ContextualEmbeddingResultMessage;
  }

  Future<ModelInfoMessage> loadModel(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.loadModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ModelInfoMessage;
  }

  Future<String?> predictedLabel(int handle, String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.predictedLabel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<List<LabelHypothesisMessage>> predictedLabelHypotheses(
    int handle,
    String text,
    int maximumCount,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.predictedLabelHypotheses$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, text, maximumCount],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<LabelHypothesisMessage>();
  }

  Future<List<String>> predictedLabelsForTokens(
    int handle,
    List<String> tokens,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.predictedLabelsForTokens$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, tokens],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<int> loadGazetteer(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.loadGazetteer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<int> createGazetteer(
    Map<String, List<String>> entries,
    String? language,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.createGazetteer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[entries, language],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<String?> gazetteerLabel(int handle, String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.gazetteerLabel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<void> release(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.release$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<int> releaseAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.releaseAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<int> liveHandleCount() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.apple_natural_language.AppleNaturalLanguageHostApi.liveHandleCount$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }
}
