// Autogenerated from Pigeon. Do not edit by hand.
// Source: pigeons/core_ml_api.dart
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class CoreMLPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "CoreMLPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? CoreMLPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Mirrors `MLComputeUnits`.
enum ComputeUnitsMessage: Int, CaseIterable {
  case cpuOnly = 0
  case cpuAndGpu = 1
  case all = 2
  case cpuAndNeuralEngine = 3
}

/// Mirrors `MLMultiArrayDataType`. The order matches the public Dart enum.
enum MultiArrayDataTypeMessage: Int, CaseIterable {
  case float16 = 0
  case float32 = 1
  case float64 = 2
  case int32 = 3
  case int8 = 4
}

/// Mirrors `MLFeatureType`. The order matches the public Dart enum.
enum FeatureTypeMessage: Int, CaseIterable {
  case invalid = 0
  case int64 = 1
  case float64 = 2
  case string = 3
  case image = 4
  case multiArray = 5
  case dictionary = 6
  case sequence = 7
  case state = 8
}

/// Mirrors `MLOptimizationHints.ReshapeFrequency`.
enum ReshapeFrequencyMessage: Int, CaseIterable {
  case frequent = 0
  case infrequent = 1
}

/// Mirrors `MLOptimizationHints.SpecializationStrategy`.
enum SpecializationStrategyMessage: Int, CaseIterable {
  case defaults = 0
  case fastPrediction = 1
}

/// Mirrors `MLMultiArrayShapeConstraintType`.
enum ShapeConstraintTypeMessage: Int, CaseIterable {
  case unspecified = 0
  case enumerated = 1
  case range = 2
}

/// Mirrors `MLImageSizeConstraintType`.
enum ImageSizeConstraintTypeMessage: Int, CaseIterable {
  case unspecified = 0
  case enumerated = 1
  case range = 2
}

/// Which case of `MLComputeDevice` a device is.
enum ComputeDeviceKindMessage: Int, CaseIterable {
  case cpu = 0
  case gpu = 1
  case neuralEngine = 2
}

/// Encoded image formats for pixel-buffer export.
enum ImageEncodingMessage: Int, CaseIterable {
  case png = 0
  case jpeg = 1
}

/// Mirrors `MLModelConfiguration`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelConfigurationMessage: Hashable, CustomStringConvertible {
  var computeUnits: ComputeUnitsMessage
  var allowLowPrecisionAccumulationOnGPU: Bool
  /// Selects a function of a multi-function model (iOS 18 / macOS 15).
  var functionName: String? = nil
  var modelDisplayName: String? = nil
  /// `MLOptimizationHints.reshapeFrequency`, left alone when null.
  var reshapeFrequency: ReshapeFrequencyMessage? = nil
  /// `MLOptimizationHints.specializationStrategy`, left alone when null.
  var specializationStrategy: SpecializationStrategyMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelConfigurationMessage? {
    let computeUnits = pigeonVar_list[0] as! ComputeUnitsMessage
    let allowLowPrecisionAccumulationOnGPU = pigeonVar_list[1] as! Bool
    let functionName: String? = nilOrValue(pigeonVar_list[2])
    let modelDisplayName: String? = nilOrValue(pigeonVar_list[3])
    let reshapeFrequency: ReshapeFrequencyMessage? = nilOrValue(pigeonVar_list[4])
    let specializationStrategy: SpecializationStrategyMessage? = nilOrValue(pigeonVar_list[5])

    return ModelConfigurationMessage(
      computeUnits: computeUnits,
      allowLowPrecisionAccumulationOnGPU: allowLowPrecisionAccumulationOnGPU,
      functionName: functionName,
      modelDisplayName: modelDisplayName,
      reshapeFrequency: reshapeFrequency,
      specializationStrategy: specializationStrategy
    )
  }
  func toList() -> [Any?] {
    return [
      computeUnits,
      allowLowPrecisionAccumulationOnGPU,
      functionName,
      modelDisplayName,
      reshapeFrequency,
      specializationStrategy,
    ]
  }
  static func == (lhs: ModelConfigurationMessage, rhs: ModelConfigurationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.computeUnits, rhs.computeUnits) && MessagesPigeonInternal.deepEquals(lhs.allowLowPrecisionAccumulationOnGPU, rhs.allowLowPrecisionAccumulationOnGPU) && MessagesPigeonInternal.deepEquals(lhs.functionName, rhs.functionName) && MessagesPigeonInternal.deepEquals(lhs.modelDisplayName, rhs.modelDisplayName) && MessagesPigeonInternal.deepEquals(lhs.reshapeFrequency, rhs.reshapeFrequency) && MessagesPigeonInternal.deepEquals(lhs.specializationStrategy, rhs.specializationStrategy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModelConfigurationMessage")
    MessagesPigeonInternal.deepHash(value: computeUnits, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: allowLowPrecisionAccumulationOnGPU, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: functionName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: modelDisplayName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reshapeFrequency, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: specializationStrategy, hasher: &hasher)
  }

  public var description: String {
    return "ModelConfigurationMessage(computeUnits: \(String(describing: computeUnits)), allowLowPrecisionAccumulationOnGPU: \(String(describing: allowLowPrecisionAccumulationOnGPU)), functionName: \(String(describing: functionName)), modelDisplayName: \(String(describing: modelDisplayName)), reshapeFrequency: \(String(describing: reshapeFrequency)), specializationStrategy: \(String(describing: specializationStrategy)))"
  }
}

/// One multi-array shape, so nested lists stay off the wire.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ShapeMessage: Hashable, CustomStringConvertible {
  var dimensions: [Int64]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ShapeMessage? {
    let dimensions = pigeonVar_list[0] as! [Int64]

    return ShapeMessage(
      dimensions: dimensions
    )
  }
  func toList() -> [Any?] {
    return [
      dimensions
    ]
  }
  static func == (lhs: ShapeMessage, rhs: ShapeMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.dimensions, rhs.dimensions)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ShapeMessage")
    MessagesPigeonInternal.deepHash(value: dimensions, hasher: &hasher)
  }

  public var description: String {
    return "ShapeMessage(dimensions: \(String(describing: dimensions)))"
  }
}

/// A width/height pair from `MLImageSize`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ImageSizeMessage: Hashable, CustomStringConvertible {
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageSizeMessage? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64

    return ImageSizeMessage(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
  static func == (lhs: ImageSizeMessage, rhs: ImageSizeMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageSizeMessage")
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "ImageSizeMessage(width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Mirrors `MLMultiArrayConstraint` and its `MLMultiArrayShapeConstraint`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MultiArrayConstraintMessage: Hashable, CustomStringConvertible {
  var dataType: MultiArrayDataTypeMessage
  var shape: [Int64]
  var shapeConstraintType: ShapeConstraintTypeMessage
  /// Non-empty for [ShapeConstraintTypeMessage.enumerated].
  var enumeratedShapes: [ShapeMessage]
  /// Per-dimension lower bounds for [ShapeConstraintTypeMessage.range].
  var minimumSizes: [Int64]
  /// Per-dimension upper bounds; `-1` means unbounded.
  var maximumSizes: [Int64]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MultiArrayConstraintMessage? {
    let dataType = pigeonVar_list[0] as! MultiArrayDataTypeMessage
    let shape = pigeonVar_list[1] as! [Int64]
    let shapeConstraintType = pigeonVar_list[2] as! ShapeConstraintTypeMessage
    let enumeratedShapes = pigeonVar_list[3] as! [ShapeMessage]
    let minimumSizes = pigeonVar_list[4] as! [Int64]
    let maximumSizes = pigeonVar_list[5] as! [Int64]

    return MultiArrayConstraintMessage(
      dataType: dataType,
      shape: shape,
      shapeConstraintType: shapeConstraintType,
      enumeratedShapes: enumeratedShapes,
      minimumSizes: minimumSizes,
      maximumSizes: maximumSizes
    )
  }
  func toList() -> [Any?] {
    return [
      dataType,
      shape,
      shapeConstraintType,
      enumeratedShapes,
      minimumSizes,
      maximumSizes,
    ]
  }
  static func == (lhs: MultiArrayConstraintMessage, rhs: MultiArrayConstraintMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.dataType, rhs.dataType) && MessagesPigeonInternal.deepEquals(lhs.shape, rhs.shape) && MessagesPigeonInternal.deepEquals(lhs.shapeConstraintType, rhs.shapeConstraintType) && MessagesPigeonInternal.deepEquals(lhs.enumeratedShapes, rhs.enumeratedShapes) && MessagesPigeonInternal.deepEquals(lhs.minimumSizes, rhs.minimumSizes) && MessagesPigeonInternal.deepEquals(lhs.maximumSizes, rhs.maximumSizes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MultiArrayConstraintMessage")
    MessagesPigeonInternal.deepHash(value: dataType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shape, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shapeConstraintType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enumeratedShapes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: minimumSizes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maximumSizes, hasher: &hasher)
  }

  public var description: String {
    return "MultiArrayConstraintMessage(dataType: \(String(describing: dataType)), shape: \(String(describing: shape)), shapeConstraintType: \(String(describing: shapeConstraintType)), enumeratedShapes: \(String(describing: enumeratedShapes)), minimumSizes: \(String(describing: minimumSizes)), maximumSizes: \(String(describing: maximumSizes)))"
  }
}

/// Mirrors `MLImageConstraint` and its `MLImageSizeConstraint`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ImageConstraintMessage: Hashable, CustomStringConvertible {
  var pixelsWide: Int64
  var pixelsHigh: Int64
  var pixelFormatType: Int64
  var sizeConstraintType: ImageSizeConstraintTypeMessage
  var enumeratedSizes: [ImageSizeMessage]
  var minimumWidth: Int64
  /// `-1` means unbounded.
  var maximumWidth: Int64
  var minimumHeight: Int64
  /// `-1` means unbounded.
  var maximumHeight: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageConstraintMessage? {
    let pixelsWide = pigeonVar_list[0] as! Int64
    let pixelsHigh = pigeonVar_list[1] as! Int64
    let pixelFormatType = pigeonVar_list[2] as! Int64
    let sizeConstraintType = pigeonVar_list[3] as! ImageSizeConstraintTypeMessage
    let enumeratedSizes = pigeonVar_list[4] as! [ImageSizeMessage]
    let minimumWidth = pigeonVar_list[5] as! Int64
    let maximumWidth = pigeonVar_list[6] as! Int64
    let minimumHeight = pigeonVar_list[7] as! Int64
    let maximumHeight = pigeonVar_list[8] as! Int64

    return ImageConstraintMessage(
      pixelsWide: pixelsWide,
      pixelsHigh: pixelsHigh,
      pixelFormatType: pixelFormatType,
      sizeConstraintType: sizeConstraintType,
      enumeratedSizes: enumeratedSizes,
      minimumWidth: minimumWidth,
      maximumWidth: maximumWidth,
      minimumHeight: minimumHeight,
      maximumHeight: maximumHeight
    )
  }
  func toList() -> [Any?] {
    return [
      pixelsWide,
      pixelsHigh,
      pixelFormatType,
      sizeConstraintType,
      enumeratedSizes,
      minimumWidth,
      maximumWidth,
      minimumHeight,
      maximumHeight,
    ]
  }
  static func == (lhs: ImageConstraintMessage, rhs: ImageConstraintMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.pixelsWide, rhs.pixelsWide) && MessagesPigeonInternal.deepEquals(lhs.pixelsHigh, rhs.pixelsHigh) && MessagesPigeonInternal.deepEquals(lhs.pixelFormatType, rhs.pixelFormatType) && MessagesPigeonInternal.deepEquals(lhs.sizeConstraintType, rhs.sizeConstraintType) && MessagesPigeonInternal.deepEquals(lhs.enumeratedSizes, rhs.enumeratedSizes) && MessagesPigeonInternal.deepEquals(lhs.minimumWidth, rhs.minimumWidth) && MessagesPigeonInternal.deepEquals(lhs.maximumWidth, rhs.maximumWidth) && MessagesPigeonInternal.deepEquals(lhs.minimumHeight, rhs.minimumHeight) && MessagesPigeonInternal.deepEquals(lhs.maximumHeight, rhs.maximumHeight)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageConstraintMessage")
    MessagesPigeonInternal.deepHash(value: pixelsWide, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pixelsHigh, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pixelFormatType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sizeConstraintType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enumeratedSizes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: minimumWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maximumWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: minimumHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maximumHeight, hasher: &hasher)
  }

  public var description: String {
    return "ImageConstraintMessage(pixelsWide: \(String(describing: pixelsWide)), pixelsHigh: \(String(describing: pixelsHigh)), pixelFormatType: \(String(describing: pixelFormatType)), sizeConstraintType: \(String(describing: sizeConstraintType)), enumeratedSizes: \(String(describing: enumeratedSizes)), minimumWidth: \(String(describing: minimumWidth)), maximumWidth: \(String(describing: maximumWidth)), minimumHeight: \(String(describing: minimumHeight)), maximumHeight: \(String(describing: maximumHeight)))"
  }
}

/// Mirrors `MLDictionaryConstraint`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DictionaryConstraintMessage: Hashable, CustomStringConvertible {
  var keyType: FeatureTypeMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DictionaryConstraintMessage? {
    let keyType = pigeonVar_list[0] as! FeatureTypeMessage

    return DictionaryConstraintMessage(
      keyType: keyType
    )
  }
  func toList() -> [Any?] {
    return [
      keyType
    ]
  }
  static func == (lhs: DictionaryConstraintMessage, rhs: DictionaryConstraintMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.keyType, rhs.keyType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DictionaryConstraintMessage")
    MessagesPigeonInternal.deepHash(value: keyType, hasher: &hasher)
  }

  public var description: String {
    return "DictionaryConstraintMessage(keyType: \(String(describing: keyType)))"
  }
}

/// Mirrors `MLSequenceConstraint`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SequenceConstraintMessage: Hashable, CustomStringConvertible {
  var valueType: FeatureTypeMessage
  var minimumCount: Int64
  var maximumCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SequenceConstraintMessage? {
    let valueType = pigeonVar_list[0] as! FeatureTypeMessage
    let minimumCount = pigeonVar_list[1] as! Int64
    let maximumCount = pigeonVar_list[2] as! Int64

    return SequenceConstraintMessage(
      valueType: valueType,
      minimumCount: minimumCount,
      maximumCount: maximumCount
    )
  }
  func toList() -> [Any?] {
    return [
      valueType,
      minimumCount,
      maximumCount,
    ]
  }
  static func == (lhs: SequenceConstraintMessage, rhs: SequenceConstraintMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.valueType, rhs.valueType) && MessagesPigeonInternal.deepEquals(lhs.minimumCount, rhs.minimumCount) && MessagesPigeonInternal.deepEquals(lhs.maximumCount, rhs.maximumCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SequenceConstraintMessage")
    MessagesPigeonInternal.deepHash(value: valueType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: minimumCount, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maximumCount, hasher: &hasher)
  }

  public var description: String {
    return "SequenceConstraintMessage(valueType: \(String(describing: valueType)), minimumCount: \(String(describing: minimumCount)), maximumCount: \(String(describing: maximumCount)))"
  }
}

/// Mirrors `MLStateConstraint`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct StateConstraintMessage: Hashable, CustomStringConvertible {
  var dataType: MultiArrayDataTypeMessage
  var bufferShape: [Int64]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StateConstraintMessage? {
    let dataType = pigeonVar_list[0] as! MultiArrayDataTypeMessage
    let bufferShape = pigeonVar_list[1] as! [Int64]

    return StateConstraintMessage(
      dataType: dataType,
      bufferShape: bufferShape
    )
  }
  func toList() -> [Any?] {
    return [
      dataType,
      bufferShape,
    ]
  }
  static func == (lhs: StateConstraintMessage, rhs: StateConstraintMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.dataType, rhs.dataType) && MessagesPigeonInternal.deepEquals(lhs.bufferShape, rhs.bufferShape)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StateConstraintMessage")
    MessagesPigeonInternal.deepHash(value: dataType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bufferShape, hasher: &hasher)
  }

  public var description: String {
    return "StateConstraintMessage(dataType: \(String(describing: dataType)), bufferShape: \(String(describing: bufferShape)))"
  }
}

/// Mirrors `MLFeatureDescription`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FeatureDescriptionMessage: Hashable, CustomStringConvertible {
  var name: String
  var type: FeatureTypeMessage
  var optional: Bool
  var multiArrayConstraint: MultiArrayConstraintMessage? = nil
  var imageConstraint: ImageConstraintMessage? = nil
  var dictionaryConstraint: DictionaryConstraintMessage? = nil
  var sequenceConstraint: SequenceConstraintMessage? = nil
  var stateConstraint: StateConstraintMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FeatureDescriptionMessage? {
    let name = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! FeatureTypeMessage
    let optional = pigeonVar_list[2] as! Bool
    let multiArrayConstraint: MultiArrayConstraintMessage? = nilOrValue(pigeonVar_list[3])
    let imageConstraint: ImageConstraintMessage? = nilOrValue(pigeonVar_list[4])
    let dictionaryConstraint: DictionaryConstraintMessage? = nilOrValue(pigeonVar_list[5])
    let sequenceConstraint: SequenceConstraintMessage? = nilOrValue(pigeonVar_list[6])
    let stateConstraint: StateConstraintMessage? = nilOrValue(pigeonVar_list[7])

    return FeatureDescriptionMessage(
      name: name,
      type: type,
      optional: optional,
      multiArrayConstraint: multiArrayConstraint,
      imageConstraint: imageConstraint,
      dictionaryConstraint: dictionaryConstraint,
      sequenceConstraint: sequenceConstraint,
      stateConstraint: stateConstraint
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      type,
      optional,
      multiArrayConstraint,
      imageConstraint,
      dictionaryConstraint,
      sequenceConstraint,
      stateConstraint,
    ]
  }
  static func == (lhs: FeatureDescriptionMessage, rhs: FeatureDescriptionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.optional, rhs.optional) && MessagesPigeonInternal.deepEquals(lhs.multiArrayConstraint, rhs.multiArrayConstraint) && MessagesPigeonInternal.deepEquals(lhs.imageConstraint, rhs.imageConstraint) && MessagesPigeonInternal.deepEquals(lhs.dictionaryConstraint, rhs.dictionaryConstraint) && MessagesPigeonInternal.deepEquals(lhs.sequenceConstraint, rhs.sequenceConstraint) && MessagesPigeonInternal.deepEquals(lhs.stateConstraint, rhs.stateConstraint)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FeatureDescriptionMessage")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: optional, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: multiArrayConstraint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imageConstraint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: dictionaryConstraint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sequenceConstraint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stateConstraint, hasher: &hasher)
  }

  public var description: String {
    return "FeatureDescriptionMessage(name: \(String(describing: name)), type: \(String(describing: type)), optional: \(String(describing: optional)), multiArrayConstraint: \(String(describing: multiArrayConstraint)), imageConstraint: \(String(describing: imageConstraint)), dictionaryConstraint: \(String(describing: dictionaryConstraint)), sequenceConstraint: \(String(describing: sequenceConstraint)), stateConstraint: \(String(describing: stateConstraint)))"
  }
}

/// The `metadata` dictionary of an `MLModelDescription`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelMetadataMessage: Hashable, CustomStringConvertible {
  var author: String? = nil
  var license: String? = nil
  /// `MLModelDescriptionKey`.
  var modelDescription: String? = nil
  var versionString: String? = nil
  /// `MLModelCreatorDefinedKey`, flattened to strings.
  var creatorDefined: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelMetadataMessage? {
    let author: String? = nilOrValue(pigeonVar_list[0])
    let license: String? = nilOrValue(pigeonVar_list[1])
    let modelDescription: String? = nilOrValue(pigeonVar_list[2])
    let versionString: String? = nilOrValue(pigeonVar_list[3])
    let creatorDefined = pigeonVar_list[4] as! [String: String]

    return ModelMetadataMessage(
      author: author,
      license: license,
      modelDescription: modelDescription,
      versionString: versionString,
      creatorDefined: creatorDefined
    )
  }
  func toList() -> [Any?] {
    return [
      author,
      license,
      modelDescription,
      versionString,
      creatorDefined,
    ]
  }
  static func == (lhs: ModelMetadataMessage, rhs: ModelMetadataMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.author, rhs.author) && MessagesPigeonInternal.deepEquals(lhs.license, rhs.license) && MessagesPigeonInternal.deepEquals(lhs.modelDescription, rhs.modelDescription) && MessagesPigeonInternal.deepEquals(lhs.versionString, rhs.versionString) && MessagesPigeonInternal.deepEquals(lhs.creatorDefined, rhs.creatorDefined)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModelMetadataMessage")
    MessagesPigeonInternal.deepHash(value: author, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: license, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: modelDescription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: versionString, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: creatorDefined, hasher: &hasher)
  }

  public var description: String {
    return "ModelMetadataMessage(author: \(String(describing: author)), license: \(String(describing: license)), modelDescription: \(String(describing: modelDescription)), versionString: \(String(describing: versionString)), creatorDefined: \(String(describing: creatorDefined)))"
  }
}

/// Mirrors `MLModelDescription`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelDescriptionMessage: Hashable, CustomStringConvertible {
  var inputs: [FeatureDescriptionMessage]
  var outputs: [FeatureDescriptionMessage]
  var states: [FeatureDescriptionMessage]
  var trainingInputs: [FeatureDescriptionMessage]
  var predictedFeatureName: String? = nil
  var predictedProbabilitiesName: String? = nil
  /// Set when the model has string class labels.
  var classLabelStrings: [String]? = nil
  /// Set when the model has int64 class labels.
  var classLabelInts: [Int64]? = nil
  var isUpdatable: Bool
  var metadata: ModelMetadataMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelDescriptionMessage? {
    let inputs = pigeonVar_list[0] as! [FeatureDescriptionMessage]
    let outputs = pigeonVar_list[1] as! [FeatureDescriptionMessage]
    let states = pigeonVar_list[2] as! [FeatureDescriptionMessage]
    let trainingInputs = pigeonVar_list[3] as! [FeatureDescriptionMessage]
    let predictedFeatureName: String? = nilOrValue(pigeonVar_list[4])
    let predictedProbabilitiesName: String? = nilOrValue(pigeonVar_list[5])
    let classLabelStrings: [String]? = nilOrValue(pigeonVar_list[6])
    let classLabelInts: [Int64]? = nilOrValue(pigeonVar_list[7])
    let isUpdatable = pigeonVar_list[8] as! Bool
    let metadata = pigeonVar_list[9] as! ModelMetadataMessage

    return ModelDescriptionMessage(
      inputs: inputs,
      outputs: outputs,
      states: states,
      trainingInputs: trainingInputs,
      predictedFeatureName: predictedFeatureName,
      predictedProbabilitiesName: predictedProbabilitiesName,
      classLabelStrings: classLabelStrings,
      classLabelInts: classLabelInts,
      isUpdatable: isUpdatable,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      inputs,
      outputs,
      states,
      trainingInputs,
      predictedFeatureName,
      predictedProbabilitiesName,
      classLabelStrings,
      classLabelInts,
      isUpdatable,
      metadata,
    ]
  }
  static func == (lhs: ModelDescriptionMessage, rhs: ModelDescriptionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.inputs, rhs.inputs) && MessagesPigeonInternal.deepEquals(lhs.outputs, rhs.outputs) && MessagesPigeonInternal.deepEquals(lhs.states, rhs.states) && MessagesPigeonInternal.deepEquals(lhs.trainingInputs, rhs.trainingInputs) && MessagesPigeonInternal.deepEquals(lhs.predictedFeatureName, rhs.predictedFeatureName) && MessagesPigeonInternal.deepEquals(lhs.predictedProbabilitiesName, rhs.predictedProbabilitiesName) && MessagesPigeonInternal.deepEquals(lhs.classLabelStrings, rhs.classLabelStrings) && MessagesPigeonInternal.deepEquals(lhs.classLabelInts, rhs.classLabelInts) && MessagesPigeonInternal.deepEquals(lhs.isUpdatable, rhs.isUpdatable) && MessagesPigeonInternal.deepEquals(lhs.metadata, rhs.metadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModelDescriptionMessage")
    MessagesPigeonInternal.deepHash(value: inputs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: states, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: trainingInputs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: predictedFeatureName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: predictedProbabilitiesName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: classLabelStrings, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: classLabelInts, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isUpdatable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: metadata, hasher: &hasher)
  }

  public var description: String {
    return "ModelDescriptionMessage(inputs: \(String(describing: inputs)), outputs: \(String(describing: outputs)), states: \(String(describing: states)), trainingInputs: \(String(describing: trainingInputs)), predictedFeatureName: \(String(describing: predictedFeatureName)), predictedProbabilitiesName: \(String(describing: predictedProbabilitiesName)), classLabelStrings: \(String(describing: classLabelStrings)), classLabelInts: \(String(describing: classLabelInts)), isUpdatable: \(String(describing: isUpdatable)), metadata: \(String(describing: metadata)))"
  }
}

/// A loaded `MLModel`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelInfoMessage: Hashable, CustomStringConvertible {
  var handle: Int64
  var modelDescription: ModelDescriptionMessage
  /// The configuration Core ML actually used.
  var configuration: ModelConfigurationMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelInfoMessage? {
    let handle = pigeonVar_list[0] as! Int64
    let modelDescription = pigeonVar_list[1] as! ModelDescriptionMessage
    let configuration = pigeonVar_list[2] as! ModelConfigurationMessage

    return ModelInfoMessage(
      handle: handle,
      modelDescription: modelDescription,
      configuration: configuration
    )
  }
  func toList() -> [Any?] {
    return [
      handle,
      modelDescription,
      configuration,
    ]
  }
  static func == (lhs: ModelInfoMessage, rhs: ModelInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.handle, rhs.handle) && MessagesPigeonInternal.deepEquals(lhs.modelDescription, rhs.modelDescription) && MessagesPigeonInternal.deepEquals(lhs.configuration, rhs.configuration)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModelInfoMessage")
    MessagesPigeonInternal.deepHash(value: handle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: modelDescription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: configuration, hasher: &hasher)
  }

  public var description: String {
    return "ModelInfoMessage(handle: \(String(describing: handle)), modelDescription: \(String(describing: modelDescription)), configuration: \(String(describing: configuration)))"
  }
}

/// Any `MLFeatureValue`.
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol FeatureValueMessage {

}

/// An `MLMultiArray`, transferred by value as raw storage bytes.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MultiArrayMessage: FeatureValueMessage {
  var dataType: MultiArrayDataTypeMessage
  var shape: [Int64]
  /// Element strides, same length as [shape]. Empty means row-major
  /// contiguous.
  var strides: [Int64]
  /// The raw backing storage.
  var data: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MultiArrayMessage? {
    let dataType = pigeonVar_list[0] as! MultiArrayDataTypeMessage
    let shape = pigeonVar_list[1] as! [Int64]
    let strides = pigeonVar_list[2] as! [Int64]
    let data = pigeonVar_list[3] as! FlutterStandardTypedData

    return MultiArrayMessage(
      dataType: dataType,
      shape: shape,
      strides: strides,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      dataType,
      shape,
      strides,
      data,
    ]
  }
  static func == (lhs: MultiArrayMessage, rhs: MultiArrayMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.dataType, rhs.dataType) && MessagesPigeonInternal.deepEquals(lhs.shape, rhs.shape) && MessagesPigeonInternal.deepEquals(lhs.strides, rhs.strides) && MessagesPigeonInternal.deepEquals(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MultiArrayMessage")
    MessagesPigeonInternal.deepHash(value: dataType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shape, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: strides, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: data, hasher: &hasher)
  }

  public var description: String {
    return "MultiArrayMessage(dataType: \(String(describing: dataType)), shape: \(String(describing: shape)), strides: \(String(describing: strides)), data: \(String(describing: data)))"
  }
}

/// One plane of a [PixelBufferMessage].
///
/// Generated class from Pigeon that represents data sent in messages.
struct PixelBufferPlaneMessage: Hashable, CustomStringConvertible {
  var width: Int64
  var height: Int64
  var bytesPerRow: Int64
  var data: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PixelBufferPlaneMessage? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64
    let bytesPerRow = pigeonVar_list[2] as! Int64
    let data = pigeonVar_list[3] as! FlutterStandardTypedData

    return PixelBufferPlaneMessage(
      width: width,
      height: height,
      bytesPerRow: bytesPerRow,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      bytesPerRow,
      data,
    ]
  }
  static func == (lhs: PixelBufferPlaneMessage, rhs: PixelBufferPlaneMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.bytesPerRow, rhs.bytesPerRow) && MessagesPigeonInternal.deepEquals(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PixelBufferPlaneMessage")
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytesPerRow, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: data, hasher: &hasher)
  }

  public var description: String {
    return "PixelBufferPlaneMessage(width: \(String(describing: width)), height: \(String(describing: height)), bytesPerRow: \(String(describing: bytesPerRow)), data: \(String(describing: data)))"
  }
}

/// A `CVPixelBuffer` image feature, transferred by value.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PixelBufferMessage: FeatureValueMessage {
  var width: Int64
  var height: Int64
  var pixelFormatType: Int64
  var planes: [PixelBufferPlaneMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PixelBufferMessage? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64
    let pixelFormatType = pigeonVar_list[2] as! Int64
    let planes = pigeonVar_list[3] as! [PixelBufferPlaneMessage]

    return PixelBufferMessage(
      width: width,
      height: height,
      pixelFormatType: pixelFormatType,
      planes: planes
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      pixelFormatType,
      planes,
    ]
  }
  static func == (lhs: PixelBufferMessage, rhs: PixelBufferMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.pixelFormatType, rhs.pixelFormatType) && MessagesPigeonInternal.deepEquals(lhs.planes, rhs.planes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PixelBufferMessage")
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pixelFormatType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: planes, hasher: &hasher)
  }

  public var description: String {
    return "PixelBufferMessage(width: \(String(describing: width)), height: \(String(describing: height)), pixelFormatType: \(String(describing: pixelFormatType)), planes: \(String(describing: planes)))"
  }
}

/// An image input given as encoded bytes or a file path. The native side
/// decodes it and resizes it to the feature's `MLImageConstraint` unless
/// [width], [height] or [pixelFormatType] override it.
///
/// Generated class from Pigeon that represents data sent in messages.
struct EncodedImageMessage: FeatureValueMessage {
  var bytes: FlutterStandardTypedData? = nil
  var path: String? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var pixelFormatType: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EncodedImageMessage? {
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])
    let path: String? = nilOrValue(pigeonVar_list[1])
    let width: Int64? = nilOrValue(pigeonVar_list[2])
    let height: Int64? = nilOrValue(pigeonVar_list[3])
    let pixelFormatType: Int64? = nilOrValue(pigeonVar_list[4])

    return EncodedImageMessage(
      bytes: bytes,
      path: path,
      width: width,
      height: height,
      pixelFormatType: pixelFormatType
    )
  }
  func toList() -> [Any?] {
    return [
      bytes,
      path,
      width,
      height,
      pixelFormatType,
    ]
  }
  static func == (lhs: EncodedImageMessage, rhs: EncodedImageMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.pixelFormatType, rhs.pixelFormatType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EncodedImageMessage")
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pixelFormatType, hasher: &hasher)
  }

  public var description: String {
    return "EncodedImageMessage(bytes: \(String(describing: bytes)), path: \(String(describing: path)), width: \(String(describing: width)), height: \(String(describing: height)), pixelFormatType: \(String(describing: pixelFormatType)))"
  }
}

/// An `MLFeatureValue` holding a string.
///
/// Generated class from Pigeon that represents data sent in messages.
struct StringValueMessage: FeatureValueMessage {
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StringValueMessage? {
    let value = pigeonVar_list[0] as! String

    return StringValueMessage(
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      value
    ]
  }
  static func == (lhs: StringValueMessage, rhs: StringValueMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StringValueMessage")
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
  }

  public var description: String {
    return "StringValueMessage(value: \(String(describing: value)))"
  }
}

/// An `MLFeatureValue` holding an int64.
///
/// Generated class from Pigeon that represents data sent in messages.
struct Int64ValueMessage: FeatureValueMessage {
  var value: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Int64ValueMessage? {
    let value = pigeonVar_list[0] as! Int64

    return Int64ValueMessage(
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      value
    ]
  }
  static func == (lhs: Int64ValueMessage, rhs: Int64ValueMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Int64ValueMessage")
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
  }

  public var description: String {
    return "Int64ValueMessage(value: \(String(describing: value)))"
  }
}

/// An `MLFeatureValue` holding a double.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DoubleValueMessage: FeatureValueMessage {
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DoubleValueMessage? {
    let value = pigeonVar_list[0] as! Double

    return DoubleValueMessage(
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      value
    ]
  }
  static func == (lhs: DoubleValueMessage, rhs: DoubleValueMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DoubleValueMessage")
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
  }

  public var description: String {
    return "DoubleValueMessage(value: \(String(describing: value)))"
  }
}

/// An `MLFeatureValue` holding a dictionary. Exactly one map is set.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DictionaryValueMessage: FeatureValueMessage {
  var stringKeyed: [String: Double]? = nil
  var int64Keyed: [Int64: Double]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DictionaryValueMessage? {
    let stringKeyed: [String: Double]? = nilOrValue(pigeonVar_list[0])
    let int64Keyed: [Int64: Double]? = nilOrValue(pigeonVar_list[1])

    return DictionaryValueMessage(
      stringKeyed: stringKeyed,
      int64Keyed: int64Keyed
    )
  }
  func toList() -> [Any?] {
    return [
      stringKeyed,
      int64Keyed,
    ]
  }
  static func == (lhs: DictionaryValueMessage, rhs: DictionaryValueMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.stringKeyed, rhs.stringKeyed) && MessagesPigeonInternal.deepEquals(lhs.int64Keyed, rhs.int64Keyed)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DictionaryValueMessage")
    MessagesPigeonInternal.deepHash(value: stringKeyed, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: int64Keyed, hasher: &hasher)
  }

  public var description: String {
    return "DictionaryValueMessage(stringKeyed: \(String(describing: stringKeyed)), int64Keyed: \(String(describing: int64Keyed)))"
  }
}

/// An `MLSequence`. Exactly one list is set.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SequenceValueMessage: FeatureValueMessage {
  var strings: [String]? = nil
  var int64s: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SequenceValueMessage? {
    let strings: [String]? = nilOrValue(pigeonVar_list[0])
    let int64s: [Int64]? = nilOrValue(pigeonVar_list[1])

    return SequenceValueMessage(
      strings: strings,
      int64s: int64s
    )
  }
  func toList() -> [Any?] {
    return [
      strings,
      int64s,
    ]
  }
  static func == (lhs: SequenceValueMessage, rhs: SequenceValueMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.strings, rhs.strings) && MessagesPigeonInternal.deepEquals(lhs.int64s, rhs.int64s)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SequenceValueMessage")
    MessagesPigeonInternal.deepHash(value: strings, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: int64s, hasher: &hasher)
  }

  public var description: String {
    return "SequenceValueMessage(strings: \(String(describing: strings)), int64s: \(String(describing: int64s)))"
  }
}

/// An undefined `MLFeatureValue` of a given type, used for optional inputs.
///
/// Generated class from Pigeon that represents data sent in messages.
struct UndefinedValueMessage: FeatureValueMessage {
  var featureType: FeatureTypeMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UndefinedValueMessage? {
    let featureType = pigeonVar_list[0] as! FeatureTypeMessage

    return UndefinedValueMessage(
      featureType: featureType
    )
  }
  func toList() -> [Any?] {
    return [
      featureType
    ]
  }
  static func == (lhs: UndefinedValueMessage, rhs: UndefinedValueMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.featureType, rhs.featureType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UndefinedValueMessage")
    MessagesPigeonInternal.deepHash(value: featureType, hasher: &hasher)
  }

  public var description: String {
    return "UndefinedValueMessage(featureType: \(String(describing: featureType)))"
  }
}

/// A named set of feature values, so nested maps stay off the wire.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FeatureMapMessage: Hashable, CustomStringConvertible {
  var features: [String: FeatureValueMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FeatureMapMessage? {
    let features = pigeonVar_list[0] as! [String: FeatureValueMessage]

    return FeatureMapMessage(
      features: features
    )
  }
  func toList() -> [Any?] {
    return [
      features
    ]
  }
  static func == (lhs: FeatureMapMessage, rhs: FeatureMapMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.features, rhs.features)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FeatureMapMessage")
    MessagesPigeonInternal.deepHash(value: features, hasher: &hasher)
  }

  public var description: String {
    return "FeatureMapMessage(features: \(String(describing: features)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PredictionRequestMessage: Hashable, CustomStringConvertible {
  var modelHandle: Int64
  var inputs: [String: FeatureValueMessage]
  /// An `MLState` handle for a stateful model.
  var stateHandle: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PredictionRequestMessage? {
    let modelHandle = pigeonVar_list[0] as! Int64
    let inputs = pigeonVar_list[1] as! [String: FeatureValueMessage]
    let stateHandle: Int64? = nilOrValue(pigeonVar_list[2])

    return PredictionRequestMessage(
      modelHandle: modelHandle,
      inputs: inputs,
      stateHandle: stateHandle
    )
  }
  func toList() -> [Any?] {
    return [
      modelHandle,
      inputs,
      stateHandle,
    ]
  }
  static func == (lhs: PredictionRequestMessage, rhs: PredictionRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.modelHandle, rhs.modelHandle) && MessagesPigeonInternal.deepEquals(lhs.inputs, rhs.inputs) && MessagesPigeonInternal.deepEquals(lhs.stateHandle, rhs.stateHandle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PredictionRequestMessage")
    MessagesPigeonInternal.deepHash(value: modelHandle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: inputs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stateHandle, hasher: &hasher)
  }

  public var description: String {
    return "PredictionRequestMessage(modelHandle: \(String(describing: modelHandle)), inputs: \(String(describing: inputs)), stateHandle: \(String(describing: stateHandle)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PredictionResultMessage: Hashable, CustomStringConvertible {
  var outputs: [String: FeatureValueMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PredictionResultMessage? {
    let outputs = pigeonVar_list[0] as! [String: FeatureValueMessage]

    return PredictionResultMessage(
      outputs: outputs
    )
  }
  func toList() -> [Any?] {
    return [
      outputs
    ]
  }
  static func == (lhs: PredictionResultMessage, rhs: PredictionResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.outputs, rhs.outputs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PredictionResultMessage")
    MessagesPigeonInternal.deepHash(value: outputs, hasher: &hasher)
  }

  public var description: String {
    return "PredictionResultMessage(outputs: \(String(describing: outputs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BatchPredictionRequestMessage: Hashable, CustomStringConvertible {
  var modelHandle: Int64
  var inputs: [FeatureMapMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BatchPredictionRequestMessage? {
    let modelHandle = pigeonVar_list[0] as! Int64
    let inputs = pigeonVar_list[1] as! [FeatureMapMessage]

    return BatchPredictionRequestMessage(
      modelHandle: modelHandle,
      inputs: inputs
    )
  }
  func toList() -> [Any?] {
    return [
      modelHandle,
      inputs,
    ]
  }
  static func == (lhs: BatchPredictionRequestMessage, rhs: BatchPredictionRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.modelHandle, rhs.modelHandle) && MessagesPigeonInternal.deepEquals(lhs.inputs, rhs.inputs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BatchPredictionRequestMessage")
    MessagesPigeonInternal.deepHash(value: modelHandle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: inputs, hasher: &hasher)
  }

  public var description: String {
    return "BatchPredictionRequestMessage(modelHandle: \(String(describing: modelHandle)), inputs: \(String(describing: inputs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BatchPredictionResultMessage: Hashable, CustomStringConvertible {
  var outputs: [FeatureMapMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BatchPredictionResultMessage? {
    let outputs = pigeonVar_list[0] as! [FeatureMapMessage]

    return BatchPredictionResultMessage(
      outputs: outputs
    )
  }
  func toList() -> [Any?] {
    return [
      outputs
    ]
  }
  static func == (lhs: BatchPredictionResultMessage, rhs: BatchPredictionResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.outputs, rhs.outputs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BatchPredictionResultMessage")
    MessagesPigeonInternal.deepHash(value: outputs, hasher: &hasher)
  }

  public var description: String {
    return "BatchPredictionResultMessage(outputs: \(String(describing: outputs)))"
  }
}

/// Mirrors a case of `MLComputeDevice`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ComputeDeviceMessage: Hashable, CustomStringConvertible {
  var kind: ComputeDeviceKindMessage
  var name: String
  var neuralEngineCoreCount: Int64? = nil
  var metalDeviceName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ComputeDeviceMessage? {
    let kind = pigeonVar_list[0] as! ComputeDeviceKindMessage
    let name = pigeonVar_list[1] as! String
    let neuralEngineCoreCount: Int64? = nilOrValue(pigeonVar_list[2])
    let metalDeviceName: String? = nilOrValue(pigeonVar_list[3])

    return ComputeDeviceMessage(
      kind: kind,
      name: name,
      neuralEngineCoreCount: neuralEngineCoreCount,
      metalDeviceName: metalDeviceName
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      name,
      neuralEngineCoreCount,
      metalDeviceName,
    ]
  }
  static func == (lhs: ComputeDeviceMessage, rhs: ComputeDeviceMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.neuralEngineCoreCount, rhs.neuralEngineCoreCount) && MessagesPigeonInternal.deepEquals(lhs.metalDeviceName, rhs.metalDeviceName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ComputeDeviceMessage")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: neuralEngineCoreCount, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: metalDeviceName, hasher: &hasher)
  }

  public var description: String {
    return "ComputeDeviceMessage(kind: \(String(describing: kind)), name: \(String(describing: name)), neuralEngineCoreCount: \(String(describing: neuralEngineCoreCount)), metalDeviceName: \(String(describing: metalDeviceName)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ComputeUnitsMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MultiArrayDataTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FeatureTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ReshapeFrequencyMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SpecializationStrategyMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ShapeConstraintTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ImageSizeConstraintTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ComputeDeviceKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ImageEncodingMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      return ModelConfigurationMessage.fromList(self.readValue() as! [Any?])
    case 139:
      return ShapeMessage.fromList(self.readValue() as! [Any?])
    case 140:
      return ImageSizeMessage.fromList(self.readValue() as! [Any?])
    case 141:
      return MultiArrayConstraintMessage.fromList(self.readValue() as! [Any?])
    case 142:
      return ImageConstraintMessage.fromList(self.readValue() as! [Any?])
    case 143:
      return DictionaryConstraintMessage.fromList(self.readValue() as! [Any?])
    case 144:
      return SequenceConstraintMessage.fromList(self.readValue() as! [Any?])
    case 145:
      return StateConstraintMessage.fromList(self.readValue() as! [Any?])
    case 146:
      return FeatureDescriptionMessage.fromList(self.readValue() as! [Any?])
    case 147:
      return ModelMetadataMessage.fromList(self.readValue() as! [Any?])
    case 148:
      return ModelDescriptionMessage.fromList(self.readValue() as! [Any?])
    case 149:
      return ModelInfoMessage.fromList(self.readValue() as! [Any?])
    case 150:
      return MultiArrayMessage.fromList(self.readValue() as! [Any?])
    case 151:
      return PixelBufferPlaneMessage.fromList(self.readValue() as! [Any?])
    case 152:
      return PixelBufferMessage.fromList(self.readValue() as! [Any?])
    case 153:
      return EncodedImageMessage.fromList(self.readValue() as! [Any?])
    case 154:
      return StringValueMessage.fromList(self.readValue() as! [Any?])
    case 155:
      return Int64ValueMessage.fromList(self.readValue() as! [Any?])
    case 156:
      return DoubleValueMessage.fromList(self.readValue() as! [Any?])
    case 157:
      return DictionaryValueMessage.fromList(self.readValue() as! [Any?])
    case 158:
      return SequenceValueMessage.fromList(self.readValue() as! [Any?])
    case 159:
      return UndefinedValueMessage.fromList(self.readValue() as! [Any?])
    case 160:
      return FeatureMapMessage.fromList(self.readValue() as! [Any?])
    case 161:
      return PredictionRequestMessage.fromList(self.readValue() as! [Any?])
    case 162:
      return PredictionResultMessage.fromList(self.readValue() as! [Any?])
    case 163:
      return BatchPredictionRequestMessage.fromList(self.readValue() as! [Any?])
    case 164:
      return BatchPredictionResultMessage.fromList(self.readValue() as! [Any?])
    case 165:
      return ComputeDeviceMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ComputeUnitsMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? MultiArrayDataTypeMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? FeatureTypeMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReshapeFrequencyMessage {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? SpecializationStrategyMessage {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? ShapeConstraintTypeMessage {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? ImageSizeConstraintTypeMessage {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? ComputeDeviceKindMessage {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? ImageEncodingMessage {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? ModelConfigurationMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ShapeMessage {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ImageSizeMessage {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? MultiArrayConstraintMessage {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? ImageConstraintMessage {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? DictionaryConstraintMessage {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? SequenceConstraintMessage {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? StateConstraintMessage {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? FeatureDescriptionMessage {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? ModelMetadataMessage {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? ModelDescriptionMessage {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? ModelInfoMessage {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? MultiArrayMessage {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? PixelBufferPlaneMessage {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? PixelBufferMessage {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? EncodedImageMessage {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? StringValueMessage {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? Int64ValueMessage {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? DoubleValueMessage {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? DictionaryValueMessage {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else if let value = value as? SequenceValueMessage {
      super.writeByte(158)
      super.writeValue(value.toList())
    } else if let value = value as? UndefinedValueMessage {
      super.writeByte(159)
      super.writeValue(value.toList())
    } else if let value = value as? FeatureMapMessage {
      super.writeByte(160)
      super.writeValue(value.toList())
    } else if let value = value as? PredictionRequestMessage {
      super.writeByte(161)
      super.writeValue(value.toList())
    } else if let value = value as? PredictionResultMessage {
      super.writeByte(162)
      super.writeValue(value.toList())
    } else if let value = value as? BatchPredictionRequestMessage {
      super.writeByte(163)
      super.writeValue(value.toList())
    } else if let value = value as? BatchPredictionResultMessage {
      super.writeByte(164)
      super.writeValue(value.toList())
    } else if let value = value as? ComputeDeviceMessage {
      super.writeByte(165)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Always available, on every OS version.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CoreMLPlatformApi {
  /// Whether this plugin's Core ML surface is available
  /// (iOS 18+ / macOS 15+).
  func isSupported() throws -> Bool
  /// The OS name and version, for diagnostics.
  func platformVersion() throws -> String
  /// The absolute on-disk path of a Flutter asset (file or directory, such as
  /// a bundled `.mlpackage`), or null if it is not in the app bundle.
  func assetPath(assetKey: String, package: String?) throws -> String?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CoreMLPlatformApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CoreMLPlatformApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CoreMLPlatformApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether this plugin's Core ML surface is available
    /// (iOS 18+ / macOS 15+).
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLPlatformApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// The OS name and version, for diagnostics.
    let platformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLPlatformApi.platformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      platformVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.platformVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      platformVersionChannel.setMessageHandler(nil)
    }
    /// The absolute on-disk path of a Flutter asset (file or directory, such as
    /// a bundled `.mlpackage`), or null if it is not in the app bundle.
    let assetPathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLPlatformApi.assetPath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      assetPathChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetKeyArg = args[0] as! String
        let packageArg: String? = nilOrValue(args[1])
        do {
          let result = try api.assetPath(assetKey: assetKeyArg, package: packageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      assetPathChannel.setMessageHandler(nil)
    }
  }
}
/// Only registered when Core ML's iOS 18 / macOS 15 surface is available.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CoreMLHostApi {
  /// `MLModel.compileModel(at:)`. Compiles a `.mlmodel` or `.mlpackage` to a
  /// `.mlmodelc` directory. When [destinationPath] is given the result is
  /// moved there (replacing anything already at that path) and that path is
  /// returned; otherwise Core ML's temporary path is returned.
  func compileModel(path: String, destinationPath: String?) async throws -> String
  /// `MLModelAsset.functionNames` for a compiled model.
  func functionNames(compiledPath: String) async throws -> [String]
  /// `MLModelAsset.modelDescription`, optionally of one function.
  func assetModelDescription(compiledPath: String, functionName: String?) async throws -> ModelDescriptionMessage
  /// `MLModel.load(contentsOf:configuration:)`.
  func loadModel(compiledPath: String, configuration: ModelConfigurationMessage) async throws -> ModelInfoMessage
  /// `MLModel.prediction(from:options:)`, or `prediction(from:using:options:)`
  /// when the request carries a state handle.
  func predict(request: PredictionRequestMessage) async throws -> PredictionResultMessage
  /// `MLModel.predictions(from:options:)`.
  func predictBatch(request: BatchPredictionRequestMessage) async throws -> BatchPredictionResultMessage
  /// `MLModel.makeState()`.
  func makeState(modelHandle: Int64) throws -> Int64
  /// Copies a state buffer into Dart (`MLState.withMultiArray(for:)`).
  func readState(stateHandle: Int64, stateName: String) async throws -> MultiArrayMessage
  /// Overwrites a state buffer. The data type and shape must match.
  func writeState(stateHandle: Int64, stateName: String, array: MultiArrayMessage) async throws
  /// `MLModel.availableComputeDevices`.
  func availableComputeDevices() throws -> [ComputeDeviceMessage]
  /// `MLComputeDevice.allComputeDevices`.
  func allComputeDevices() throws -> [ComputeDeviceMessage]
  /// Encodes an image feature value as PNG or JPEG, for display in Dart.
  func encodeImage(image: PixelBufferMessage, encoding: ImageEncodingMessage, quality: Double) async throws -> FlutterStandardTypedData
  /// Releases a model or state handle.
  func release(handle: Int64) async throws
  /// Releases every handle owned by this engine. Returns how many were freed.
  func releaseAll() async throws -> Int64
  func liveHandleCount() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CoreMLHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CoreMLHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CoreMLHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// `MLModel.compileModel(at:)`. Compiles a `.mlmodel` or `.mlpackage` to a
    /// `.mlmodelc` directory. When [destinationPath] is given the result is
    /// moved there (replacing anything already at that path) and that path is
    /// returned; otherwise Core ML's temporary path is returned.
    let compileModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.compileModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compileModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let destinationPathArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.compileModel(path: pathArg, destinationPath: destinationPathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      compileModelChannel.setMessageHandler(nil)
    }
    /// `MLModelAsset.functionNames` for a compiled model.
    let functionNamesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.functionNames\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      functionNamesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let compiledPathArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.functionNames(compiledPath: compiledPathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      functionNamesChannel.setMessageHandler(nil)
    }
    /// `MLModelAsset.modelDescription`, optionally of one function.
    let assetModelDescriptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.assetModelDescription\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      assetModelDescriptionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let compiledPathArg = args[0] as! String
        let functionNameArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.assetModelDescription(compiledPath: compiledPathArg, functionName: functionNameArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      assetModelDescriptionChannel.setMessageHandler(nil)
    }
    /// `MLModel.load(contentsOf:configuration:)`.
    let loadModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.loadModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let compiledPathArg = args[0] as! String
        let configurationArg = args[1] as! ModelConfigurationMessage
        Task { @MainActor in
          do {
            let result = try await api.loadModel(compiledPath: compiledPathArg, configuration: configurationArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadModelChannel.setMessageHandler(nil)
    }
    /// `MLModel.prediction(from:options:)`, or `prediction(from:using:options:)`
    /// when the request carries a state handle.
    let predictChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.predict\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      predictChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PredictionRequestMessage
        Task { @MainActor in
          do {
            let result = try await api.predict(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      predictChannel.setMessageHandler(nil)
    }
    /// `MLModel.predictions(from:options:)`.
    let predictBatchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.predictBatch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      predictBatchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! BatchPredictionRequestMessage
        Task { @MainActor in
          do {
            let result = try await api.predictBatch(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      predictBatchChannel.setMessageHandler(nil)
    }
    /// `MLModel.makeState()`.
    let makeStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.makeState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      makeStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modelHandleArg = args[0] as! Int64
        do {
          let result = try api.makeState(modelHandle: modelHandleArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      makeStateChannel.setMessageHandler(nil)
    }
    /// Copies a state buffer into Dart (`MLState.withMultiArray(for:)`).
    let readStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.readState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateHandleArg = args[0] as! Int64
        let stateNameArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.readState(stateHandle: stateHandleArg, stateName: stateNameArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      readStateChannel.setMessageHandler(nil)
    }
    /// Overwrites a state buffer. The data type and shape must match.
    let writeStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.writeState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateHandleArg = args[0] as! Int64
        let stateNameArg = args[1] as! String
        let arrayArg = args[2] as! MultiArrayMessage
        Task { @MainActor in
          do {
            try await api.writeState(stateHandle: stateHandleArg, stateName: stateNameArg, array: arrayArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeStateChannel.setMessageHandler(nil)
    }
    /// `MLModel.availableComputeDevices`.
    let availableComputeDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.availableComputeDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      availableComputeDevicesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.availableComputeDevices()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      availableComputeDevicesChannel.setMessageHandler(nil)
    }
    /// `MLComputeDevice.allComputeDevices`.
    let allComputeDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.allComputeDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      allComputeDevicesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.allComputeDevices()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      allComputeDevicesChannel.setMessageHandler(nil)
    }
    /// Encodes an image feature value as PNG or JPEG, for display in Dart.
    let encodeImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.encodeImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      encodeImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageArg = args[0] as! PixelBufferMessage
        let encodingArg = args[1] as! ImageEncodingMessage
        let qualityArg = args[2] as! Double
        Task { @MainActor in
          do {
            let result = try await api.encodeImage(image: imageArg, encoding: encodingArg, quality: qualityArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      encodeImageChannel.setMessageHandler(nil)
    }
    /// Releases a model or state handle.
    let releaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.release\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        Task { @MainActor in
          do {
            try await api.release(handle: handleArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseChannel.setMessageHandler(nil)
    }
    /// Releases every handle owned by this engine. Returns how many were freed.
    let releaseAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.releaseAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseAllChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.releaseAll()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseAllChannel.setMessageHandler(nil)
    }
    let liveHandleCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.core_ml.CoreMLHostApi.liveHandleCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      liveHandleCountChannel.setMessageHandler { _, reply in
        do {
          let result = try api.liveHandleCount()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      liveHandleCountChannel.setMessageHandler(nil)
    }
  }
}
