// Autogenerated from Pigeon. Do not edit by hand.
// Source: pigeons/apple_speech_api.dart
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class AppleSpeechPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "AppleSpeechPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? AppleSpeechPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> AppleSpeechPigeonError {
  return AppleSpeechPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Mirrors `SFSpeechRecognizerAuthorizationStatus` and
/// `AVAuthorizationStatus`.
enum AuthorizationStatusMessage: Int, CaseIterable {
  case notDetermined = 0
  case denied = 1
  case restricted = 2
  case authorized = 3
}

/// Mirrors `SFSpeechRecognitionTaskHint`.
enum TaskHintMessage: Int, CaseIterable {
  case unspecified = 0
  case dictation = 1
  case search = 2
  case confirmation = 3
}

/// Where audio comes from.
enum AudioSourceKindMessage: Int, CaseIterable {
  /// An audio file read with `AVAudioFile`.
  case file = 0
  /// Any media file (audio or video) read with `AVAsset` (iOS/macOS 27).
  case asset = 1
  /// The default input device, captured with `AVAudioEngine`.
  case microphone = 2
  /// A file fed buffer by buffer through the microphone pipeline (tests).
  case simulatedMicrophone = 3
}

/// The kind of a `SpeechModule`.
enum ModuleKindMessage: Int, CaseIterable {
  case speechTranscriber = 0
  case dictationTranscriber = 1
  case speechDetector = 2
}

/// Mirrors `SpeechTranscriber.Preset`.
enum SpeechTranscriberPresetMessage: Int, CaseIterable {
  case transcription = 0
  case transcriptionWithAlternatives = 1
  case timeIndexedTranscriptionWithAlternatives = 2
  case progressiveTranscription = 3
  case timeIndexedProgressiveTranscription = 4
}

/// Mirrors `DictationTranscriber.Preset`.
enum DictationPresetMessage: Int, CaseIterable {
  case phrase = 0
  case shortDictation = 1
  case progressiveShortDictation = 2
  case longDictation = 3
  case progressiveLongDictation = 4
  case timeIndexedLongDictation = 5
}

/// Mirrors `SpeechTranscriber.TranscriptionOption` and
/// `DictationTranscriber.TranscriptionOption`.
enum TranscriptionOptionMessage: Int, CaseIterable {
  case punctuation = 0
  case emoji = 1
  case etiquetteReplacements = 2
}

/// Mirrors `SpeechTranscriber.ReportingOption` and
/// `DictationTranscriber.ReportingOption`.
enum ReportingOptionMessage: Int, CaseIterable {
  case volatileResults = 0
  case alternativeTranscriptions = 1
  case fastResults = 2
  case frequentFinalization = 3
}

/// Mirrors `ResultAttributeOption`.
enum ResultAttributeOptionMessage: Int, CaseIterable {
  case audioTimeRange = 0
  case transcriptionConfidence = 1
}

/// Mirrors `DictationTranscriber.ContentHint` (except custom language
/// models).
enum ContentHintMessage: Int, CaseIterable {
  case shortForm = 0
  case farField = 1
  case atypicalSpeech = 2
}

/// Mirrors `SpeechDetector.SensitivityLevel`.
enum SensitivityLevelMessage: Int, CaseIterable {
  case low = 0
  case medium = 1
  case high = 2
}

/// Mirrors `SpeechAnalyzer.Options.ModelRetention`.
enum ModelRetentionMessage: Int, CaseIterable {
  case whileInUse = 0
  case lingering = 1
  case processLifetime = 2
}

/// Mirrors `TaskPriority`.
enum TaskPriorityMessage: Int, CaseIterable {
  case background = 0
  case utility = 1
  case low = 2
  case medium = 3
  case high = 4
  case userInitiated = 5
}

/// Mirrors `AssetInventory.Status`.
enum AssetStatusMessage: Int, CaseIterable {
  case unsupported = 0
  case supported = 1
  case downloading = 2
  case installed = 3
}

/// One word or phrase of a transcription.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TranscriptionSegmentMessage: Hashable, CustomStringConvertible {
  var text: String
  /// UTF-16 offset of the segment in the full text.
  var start: Int64
  /// UTF-16 length of the segment in the full text.
  var length: Int64
  /// Seconds from the start of the audio.
  var startTime: Double? = nil
  var endTime: Double? = nil
  /// 0...1.
  var confidence: Double? = nil
  var alternatives: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TranscriptionSegmentMessage? {
    let text = pigeonVar_list[0] as! String
    let start = pigeonVar_list[1] as! Int64
    let length = pigeonVar_list[2] as! Int64
    let startTime: Double? = nilOrValue(pigeonVar_list[3])
    let endTime: Double? = nilOrValue(pigeonVar_list[4])
    let confidence: Double? = nilOrValue(pigeonVar_list[5])
    let alternatives = pigeonVar_list[6] as! [String]

    return TranscriptionSegmentMessage(
      text: text,
      start: start,
      length: length,
      startTime: startTime,
      endTime: endTime,
      confidence: confidence,
      alternatives: alternatives
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      start,
      length,
      startTime,
      endTime,
      confidence,
      alternatives,
    ]
  }
  static func == (lhs: TranscriptionSegmentMessage, rhs: TranscriptionSegmentMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.start, rhs.start) && MessagesPigeonInternal.deepEquals(lhs.length, rhs.length) && MessagesPigeonInternal.deepEquals(lhs.startTime, rhs.startTime) && MessagesPigeonInternal.deepEquals(lhs.endTime, rhs.endTime) && MessagesPigeonInternal.deepEquals(lhs.confidence, rhs.confidence) && MessagesPigeonInternal.deepEquals(lhs.alternatives, rhs.alternatives)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TranscriptionSegmentMessage")
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: start, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: length, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: startTime, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: endTime, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: confidence, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: alternatives, hasher: &hasher)
  }

  public var description: String {
    return "TranscriptionSegmentMessage(text: \(String(describing: text)), start: \(String(describing: start)), length: \(String(describing: length)), startTime: \(String(describing: startTime)), endTime: \(String(describing: endTime)), confidence: \(String(describing: confidence)), alternatives: \(String(describing: alternatives)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ErrorMessage: Hashable, CustomStringConvertible {
  var code: String
  var message: String
  var details: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ErrorMessage? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let details: String? = nilOrValue(pigeonVar_list[2])

    return ErrorMessage(
      code: code,
      message: message,
      details: details
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      details,
    ]
  }
  static func == (lhs: ErrorMessage, rhs: ErrorMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.details, rhs.details)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ErrorMessage")
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: details, hasher: &hasher)
  }

  public var description: String {
    return "ErrorMessage(code: \(String(describing: code)), message: \(String(describing: message)), details: \(String(describing: details)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AudioFormatMessage: Hashable, CustomStringConvertible {
  var sampleRate: Double
  var channelCount: Int64
  /// `pcmFormatInt16`, `pcmFormatFloat32`, ... or `other`.
  var commonFormat: String
  var isInterleaved: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioFormatMessage? {
    let sampleRate = pigeonVar_list[0] as! Double
    let channelCount = pigeonVar_list[1] as! Int64
    let commonFormat = pigeonVar_list[2] as! String
    let isInterleaved = pigeonVar_list[3] as! Bool

    return AudioFormatMessage(
      sampleRate: sampleRate,
      channelCount: channelCount,
      commonFormat: commonFormat,
      isInterleaved: isInterleaved
    )
  }
  func toList() -> [Any?] {
    return [
      sampleRate,
      channelCount,
      commonFormat,
      isInterleaved,
    ]
  }
  static func == (lhs: AudioFormatMessage, rhs: AudioFormatMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sampleRate, rhs.sampleRate) && MessagesPigeonInternal.deepEquals(lhs.channelCount, rhs.channelCount) && MessagesPigeonInternal.deepEquals(lhs.commonFormat, rhs.commonFormat) && MessagesPigeonInternal.deepEquals(lhs.isInterleaved, rhs.isInterleaved)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioFormatMessage")
    MessagesPigeonInternal.deepHash(value: sampleRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: channelCount, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: commonFormat, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isInterleaved, hasher: &hasher)
  }

  public var description: String {
    return "AudioFormatMessage(sampleRate: \(String(describing: sampleRate)), channelCount: \(String(describing: channelCount)), commonFormat: \(String(describing: commonFormat)), isInterleaved: \(String(describing: isInterleaved)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecognizerInfoMessage: Hashable, CustomStringConvertible {
  var locale: String
  var isAvailable: Bool
  var supportsOnDeviceRecognition: Bool
  var defaultTaskHint: TaskHintMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecognizerInfoMessage? {
    let locale = pigeonVar_list[0] as! String
    let isAvailable = pigeonVar_list[1] as! Bool
    let supportsOnDeviceRecognition = pigeonVar_list[2] as! Bool
    let defaultTaskHint = pigeonVar_list[3] as! TaskHintMessage

    return RecognizerInfoMessage(
      locale: locale,
      isAvailable: isAvailable,
      supportsOnDeviceRecognition: supportsOnDeviceRecognition,
      defaultTaskHint: defaultTaskHint
    )
  }
  func toList() -> [Any?] {
    return [
      locale,
      isAvailable,
      supportsOnDeviceRecognition,
      defaultTaskHint,
    ]
  }
  static func == (lhs: RecognizerInfoMessage, rhs: RecognizerInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.locale, rhs.locale) && MessagesPigeonInternal.deepEquals(lhs.isAvailable, rhs.isAvailable) && MessagesPigeonInternal.deepEquals(lhs.supportsOnDeviceRecognition, rhs.supportsOnDeviceRecognition) && MessagesPigeonInternal.deepEquals(lhs.defaultTaskHint, rhs.defaultTaskHint)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecognizerInfoMessage")
    MessagesPigeonInternal.deepHash(value: locale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isAvailable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: supportsOnDeviceRecognition, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: defaultTaskHint, hasher: &hasher)
  }

  public var description: String {
    return "RecognizerInfoMessage(locale: \(String(describing: locale)), isAvailable: \(String(describing: isAvailable)), supportsOnDeviceRecognition: \(String(describing: supportsOnDeviceRecognition)), defaultTaskHint: \(String(describing: defaultTaskHint)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecognitionRequestMessage: Hashable, CustomStringConvertible {
  var requestId: Int64
  /// Null for the user's current locale.
  var locale: String? = nil
  /// `file` or `microphone`.
  var source: AudioSourceKindMessage
  var path: String? = nil
  var taskHint: TaskHintMessage
  var shouldReportPartialResults: Bool
  var contextualStrings: [String]
  var requiresOnDeviceRecognition: Bool
  /// iOS 16 / macOS 13; null keeps Apple's default.
  var addsPunctuation: Bool? = nil
  /// iOS only: activate a recording `AVAudioSession` for the microphone.
  var configureAudioSession: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecognitionRequestMessage? {
    let requestId = pigeonVar_list[0] as! Int64
    let locale: String? = nilOrValue(pigeonVar_list[1])
    let source = pigeonVar_list[2] as! AudioSourceKindMessage
    let path: String? = nilOrValue(pigeonVar_list[3])
    let taskHint = pigeonVar_list[4] as! TaskHintMessage
    let shouldReportPartialResults = pigeonVar_list[5] as! Bool
    let contextualStrings = pigeonVar_list[6] as! [String]
    let requiresOnDeviceRecognition = pigeonVar_list[7] as! Bool
    let addsPunctuation: Bool? = nilOrValue(pigeonVar_list[8])
    let configureAudioSession = pigeonVar_list[9] as! Bool

    return RecognitionRequestMessage(
      requestId: requestId,
      locale: locale,
      source: source,
      path: path,
      taskHint: taskHint,
      shouldReportPartialResults: shouldReportPartialResults,
      contextualStrings: contextualStrings,
      requiresOnDeviceRecognition: requiresOnDeviceRecognition,
      addsPunctuation: addsPunctuation,
      configureAudioSession: configureAudioSession
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      locale,
      source,
      path,
      taskHint,
      shouldReportPartialResults,
      contextualStrings,
      requiresOnDeviceRecognition,
      addsPunctuation,
      configureAudioSession,
    ]
  }
  static func == (lhs: RecognitionRequestMessage, rhs: RecognitionRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && MessagesPigeonInternal.deepEquals(lhs.locale, rhs.locale) && MessagesPigeonInternal.deepEquals(lhs.source, rhs.source) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path) && MessagesPigeonInternal.deepEquals(lhs.taskHint, rhs.taskHint) && MessagesPigeonInternal.deepEquals(lhs.shouldReportPartialResults, rhs.shouldReportPartialResults) && MessagesPigeonInternal.deepEquals(lhs.contextualStrings, rhs.contextualStrings) && MessagesPigeonInternal.deepEquals(lhs.requiresOnDeviceRecognition, rhs.requiresOnDeviceRecognition) && MessagesPigeonInternal.deepEquals(lhs.addsPunctuation, rhs.addsPunctuation) && MessagesPigeonInternal.deepEquals(lhs.configureAudioSession, rhs.configureAudioSession)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecognitionRequestMessage")
    MessagesPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: locale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: source, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: taskHint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shouldReportPartialResults, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contextualStrings, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requiresOnDeviceRecognition, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: addsPunctuation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: configureAudioSession, hasher: &hasher)
  }

  public var description: String {
    return "RecognitionRequestMessage(requestId: \(String(describing: requestId)), locale: \(String(describing: locale)), source: \(String(describing: source)), path: \(String(describing: path)), taskHint: \(String(describing: taskHint)), shouldReportPartialResults: \(String(describing: shouldReportPartialResults)), contextualStrings: \(String(describing: contextualStrings)), requiresOnDeviceRecognition: \(String(describing: requiresOnDeviceRecognition)), addsPunctuation: \(String(describing: addsPunctuation)), configureAudioSession: \(String(describing: configureAudioSession)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TranscriptionMessage: Hashable, CustomStringConvertible {
  var formattedString: String
  var segments: [TranscriptionSegmentMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TranscriptionMessage? {
    let formattedString = pigeonVar_list[0] as! String
    let segments = pigeonVar_list[1] as! [TranscriptionSegmentMessage]

    return TranscriptionMessage(
      formattedString: formattedString,
      segments: segments
    )
  }
  func toList() -> [Any?] {
    return [
      formattedString,
      segments,
    ]
  }
  static func == (lhs: TranscriptionMessage, rhs: TranscriptionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.formattedString, rhs.formattedString) && MessagesPigeonInternal.deepEquals(lhs.segments, rhs.segments)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TranscriptionMessage")
    MessagesPigeonInternal.deepHash(value: formattedString, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: segments, hasher: &hasher)
  }

  public var description: String {
    return "TranscriptionMessage(formattedString: \(String(describing: formattedString)), segments: \(String(describing: segments)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecognitionMetadataMessage: Hashable, CustomStringConvertible {
  var speakingRate: Double
  var averagePauseDuration: Double
  var speechStartTimestamp: Double
  var speechDuration: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecognitionMetadataMessage? {
    let speakingRate = pigeonVar_list[0] as! Double
    let averagePauseDuration = pigeonVar_list[1] as! Double
    let speechStartTimestamp = pigeonVar_list[2] as! Double
    let speechDuration = pigeonVar_list[3] as! Double

    return RecognitionMetadataMessage(
      speakingRate: speakingRate,
      averagePauseDuration: averagePauseDuration,
      speechStartTimestamp: speechStartTimestamp,
      speechDuration: speechDuration
    )
  }
  func toList() -> [Any?] {
    return [
      speakingRate,
      averagePauseDuration,
      speechStartTimestamp,
      speechDuration,
    ]
  }
  static func == (lhs: RecognitionMetadataMessage, rhs: RecognitionMetadataMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.speakingRate, rhs.speakingRate) && MessagesPigeonInternal.deepEquals(lhs.averagePauseDuration, rhs.averagePauseDuration) && MessagesPigeonInternal.deepEquals(lhs.speechStartTimestamp, rhs.speechStartTimestamp) && MessagesPigeonInternal.deepEquals(lhs.speechDuration, rhs.speechDuration)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecognitionMetadataMessage")
    MessagesPigeonInternal.deepHash(value: speakingRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: averagePauseDuration, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: speechStartTimestamp, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: speechDuration, hasher: &hasher)
  }

  public var description: String {
    return "RecognitionMetadataMessage(speakingRate: \(String(describing: speakingRate)), averagePauseDuration: \(String(describing: averagePauseDuration)), speechStartTimestamp: \(String(describing: speechStartTimestamp)), speechDuration: \(String(describing: speechDuration)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecognitionResultMessage: Hashable, CustomStringConvertible {
  var requestId: Int64
  var bestTranscription: TranscriptionMessage
  var transcriptions: [TranscriptionMessage]
  var isFinal: Bool
  var metadata: RecognitionMetadataMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecognitionResultMessage? {
    let requestId = pigeonVar_list[0] as! Int64
    let bestTranscription = pigeonVar_list[1] as! TranscriptionMessage
    let transcriptions = pigeonVar_list[2] as! [TranscriptionMessage]
    let isFinal = pigeonVar_list[3] as! Bool
    let metadata: RecognitionMetadataMessage? = nilOrValue(pigeonVar_list[4])

    return RecognitionResultMessage(
      requestId: requestId,
      bestTranscription: bestTranscription,
      transcriptions: transcriptions,
      isFinal: isFinal,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      bestTranscription,
      transcriptions,
      isFinal,
      metadata,
    ]
  }
  static func == (lhs: RecognitionResultMessage, rhs: RecognitionResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && MessagesPigeonInternal.deepEquals(lhs.bestTranscription, rhs.bestTranscription) && MessagesPigeonInternal.deepEquals(lhs.transcriptions, rhs.transcriptions) && MessagesPigeonInternal.deepEquals(lhs.isFinal, rhs.isFinal) && MessagesPigeonInternal.deepEquals(lhs.metadata, rhs.metadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecognitionResultMessage")
    MessagesPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bestTranscription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transcriptions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isFinal, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: metadata, hasher: &hasher)
  }

  public var description: String {
    return "RecognitionResultMessage(requestId: \(String(describing: requestId)), bestTranscription: \(String(describing: bestTranscription)), transcriptions: \(String(describing: transcriptions)), isFinal: \(String(describing: isFinal)), metadata: \(String(describing: metadata)))"
  }
}

/// A `SpeechTranscriber`, `DictationTranscriber` or `SpeechDetector`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModuleConfigMessage: Hashable, CustomStringConvertible {
  var kind: ModuleKindMessage
  /// Transcribers only.
  var locale: String? = nil
  /// When set, used instead of the option lists.
  var speechPreset: SpeechTranscriberPresetMessage? = nil
  var dictationPreset: DictationPresetMessage? = nil
  var transcriptionOptions: [TranscriptionOptionMessage]
  var reportingOptions: [ReportingOptionMessage]
  var attributeOptions: [ResultAttributeOptionMessage]
  var contentHints: [ContentHintMessage]
  /// Detector only.
  var sensitivityLevel: SensitivityLevelMessage? = nil
  var reportResults: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModuleConfigMessage? {
    let kind = pigeonVar_list[0] as! ModuleKindMessage
    let locale: String? = nilOrValue(pigeonVar_list[1])
    let speechPreset: SpeechTranscriberPresetMessage? = nilOrValue(pigeonVar_list[2])
    let dictationPreset: DictationPresetMessage? = nilOrValue(pigeonVar_list[3])
    let transcriptionOptions = pigeonVar_list[4] as! [TranscriptionOptionMessage]
    let reportingOptions = pigeonVar_list[5] as! [ReportingOptionMessage]
    let attributeOptions = pigeonVar_list[6] as! [ResultAttributeOptionMessage]
    let contentHints = pigeonVar_list[7] as! [ContentHintMessage]
    let sensitivityLevel: SensitivityLevelMessage? = nilOrValue(pigeonVar_list[8])
    let reportResults: Bool? = nilOrValue(pigeonVar_list[9])

    return ModuleConfigMessage(
      kind: kind,
      locale: locale,
      speechPreset: speechPreset,
      dictationPreset: dictationPreset,
      transcriptionOptions: transcriptionOptions,
      reportingOptions: reportingOptions,
      attributeOptions: attributeOptions,
      contentHints: contentHints,
      sensitivityLevel: sensitivityLevel,
      reportResults: reportResults
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      locale,
      speechPreset,
      dictationPreset,
      transcriptionOptions,
      reportingOptions,
      attributeOptions,
      contentHints,
      sensitivityLevel,
      reportResults,
    ]
  }
  static func == (lhs: ModuleConfigMessage, rhs: ModuleConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.locale, rhs.locale) && MessagesPigeonInternal.deepEquals(lhs.speechPreset, rhs.speechPreset) && MessagesPigeonInternal.deepEquals(lhs.dictationPreset, rhs.dictationPreset) && MessagesPigeonInternal.deepEquals(lhs.transcriptionOptions, rhs.transcriptionOptions) && MessagesPigeonInternal.deepEquals(lhs.reportingOptions, rhs.reportingOptions) && MessagesPigeonInternal.deepEquals(lhs.attributeOptions, rhs.attributeOptions) && MessagesPigeonInternal.deepEquals(lhs.contentHints, rhs.contentHints) && MessagesPigeonInternal.deepEquals(lhs.sensitivityLevel, rhs.sensitivityLevel) && MessagesPigeonInternal.deepEquals(lhs.reportResults, rhs.reportResults)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModuleConfigMessage")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: locale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: speechPreset, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: dictationPreset, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: transcriptionOptions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reportingOptions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attributeOptions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contentHints, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sensitivityLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reportResults, hasher: &hasher)
  }

  public var description: String {
    return "ModuleConfigMessage(kind: \(String(describing: kind)), locale: \(String(describing: locale)), speechPreset: \(String(describing: speechPreset)), dictationPreset: \(String(describing: dictationPreset)), transcriptionOptions: \(String(describing: transcriptionOptions)), reportingOptions: \(String(describing: reportingOptions)), attributeOptions: \(String(describing: attributeOptions)), contentHints: \(String(describing: contentHints)), sensitivityLevel: \(String(describing: sensitivityLevel)), reportResults: \(String(describing: reportResults)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnalyzerOptionsMessage: Hashable, CustomStringConvertible {
  var priority: TaskPriorityMessage
  var modelRetention: ModelRetentionMessage
  /// iOS/macOS 27.
  var ignoresResourceLimits: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnalyzerOptionsMessage? {
    let priority = pigeonVar_list[0] as! TaskPriorityMessage
    let modelRetention = pigeonVar_list[1] as! ModelRetentionMessage
    let ignoresResourceLimits: Bool? = nilOrValue(pigeonVar_list[2])

    return AnalyzerOptionsMessage(
      priority: priority,
      modelRetention: modelRetention,
      ignoresResourceLimits: ignoresResourceLimits
    )
  }
  func toList() -> [Any?] {
    return [
      priority,
      modelRetention,
      ignoresResourceLimits,
    ]
  }
  static func == (lhs: AnalyzerOptionsMessage, rhs: AnalyzerOptionsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.priority, rhs.priority) && MessagesPigeonInternal.deepEquals(lhs.modelRetention, rhs.modelRetention) && MessagesPigeonInternal.deepEquals(lhs.ignoresResourceLimits, rhs.ignoresResourceLimits)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnalyzerOptionsMessage")
    MessagesPigeonInternal.deepHash(value: priority, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: modelRetention, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ignoresResourceLimits, hasher: &hasher)
  }

  public var description: String {
    return "AnalyzerOptionsMessage(priority: \(String(describing: priority)), modelRetention: \(String(describing: modelRetention)), ignoresResourceLimits: \(String(describing: ignoresResourceLimits)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnalysisRequestMessage: Hashable, CustomStringConvertible {
  var requestId: Int64
  var source: AudioSourceKindMessage
  var path: String? = nil
  var modules: [ModuleConfigMessage]
  var options: AnalyzerOptionsMessage? = nil
  /// `AnalysisContext.contextualStrings`, keyed by tag (e.g. "general").
  var contextualStrings: [String: [String]]
  /// iOS only: activate a recording `AVAudioSession` for the microphone.
  var configureAudioSession: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnalysisRequestMessage? {
    let requestId = pigeonVar_list[0] as! Int64
    let source = pigeonVar_list[1] as! AudioSourceKindMessage
    let path: String? = nilOrValue(pigeonVar_list[2])
    let modules = pigeonVar_list[3] as! [ModuleConfigMessage]
    let options: AnalyzerOptionsMessage? = nilOrValue(pigeonVar_list[4])
    let contextualStrings = pigeonVar_list[5] as! [String: [String]]
    let configureAudioSession = pigeonVar_list[6] as! Bool

    return AnalysisRequestMessage(
      requestId: requestId,
      source: source,
      path: path,
      modules: modules,
      options: options,
      contextualStrings: contextualStrings,
      configureAudioSession: configureAudioSession
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      source,
      path,
      modules,
      options,
      contextualStrings,
      configureAudioSession,
    ]
  }
  static func == (lhs: AnalysisRequestMessage, rhs: AnalysisRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && MessagesPigeonInternal.deepEquals(lhs.source, rhs.source) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path) && MessagesPigeonInternal.deepEquals(lhs.modules, rhs.modules) && MessagesPigeonInternal.deepEquals(lhs.options, rhs.options) && MessagesPigeonInternal.deepEquals(lhs.contextualStrings, rhs.contextualStrings) && MessagesPigeonInternal.deepEquals(lhs.configureAudioSession, rhs.configureAudioSession)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnalysisRequestMessage")
    MessagesPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: source, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: modules, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: options, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contextualStrings, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: configureAudioSession, hasher: &hasher)
  }

  public var description: String {
    return "AnalysisRequestMessage(requestId: \(String(describing: requestId)), source: \(String(describing: source)), path: \(String(describing: path)), modules: \(String(describing: modules)), options: \(String(describing: options)), contextualStrings: \(String(describing: contextualStrings)), configureAudioSession: \(String(describing: configureAudioSession)))"
  }
}

/// A result from one module of an analysis.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AnalyzerResultMessage: Hashable, CustomStringConvertible {
  var requestId: Int64
  /// Index into `AnalysisRequestMessage.modules`.
  var moduleIndex: Int64
  var rangeStart: Double
  var rangeEnd: Double
  var resultsFinalizationTime: Double
  var isFinal: Bool
  /// Transcribers: the transcribed text.
  var text: String? = nil
  /// Transcribers: the runs of `text` with their attributes.
  var segments: [TranscriptionSegmentMessage]
  /// Transcribers: alternative transcriptions, best first.
  var alternatives: [String]
  /// Detector: whether speech was detected in the range.
  var speechDetected: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnalyzerResultMessage? {
    let requestId = pigeonVar_list[0] as! Int64
    let moduleIndex = pigeonVar_list[1] as! Int64
    let rangeStart = pigeonVar_list[2] as! Double
    let rangeEnd = pigeonVar_list[3] as! Double
    let resultsFinalizationTime = pigeonVar_list[4] as! Double
    let isFinal = pigeonVar_list[5] as! Bool
    let text: String? = nilOrValue(pigeonVar_list[6])
    let segments = pigeonVar_list[7] as! [TranscriptionSegmentMessage]
    let alternatives = pigeonVar_list[8] as! [String]
    let speechDetected: Bool? = nilOrValue(pigeonVar_list[9])

    return AnalyzerResultMessage(
      requestId: requestId,
      moduleIndex: moduleIndex,
      rangeStart: rangeStart,
      rangeEnd: rangeEnd,
      resultsFinalizationTime: resultsFinalizationTime,
      isFinal: isFinal,
      text: text,
      segments: segments,
      alternatives: alternatives,
      speechDetected: speechDetected
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      moduleIndex,
      rangeStart,
      rangeEnd,
      resultsFinalizationTime,
      isFinal,
      text,
      segments,
      alternatives,
      speechDetected,
    ]
  }
  static func == (lhs: AnalyzerResultMessage, rhs: AnalyzerResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && MessagesPigeonInternal.deepEquals(lhs.moduleIndex, rhs.moduleIndex) && MessagesPigeonInternal.deepEquals(lhs.rangeStart, rhs.rangeStart) && MessagesPigeonInternal.deepEquals(lhs.rangeEnd, rhs.rangeEnd) && MessagesPigeonInternal.deepEquals(lhs.resultsFinalizationTime, rhs.resultsFinalizationTime) && MessagesPigeonInternal.deepEquals(lhs.isFinal, rhs.isFinal) && MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.segments, rhs.segments) && MessagesPigeonInternal.deepEquals(lhs.alternatives, rhs.alternatives) && MessagesPigeonInternal.deepEquals(lhs.speechDetected, rhs.speechDetected)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnalyzerResultMessage")
    MessagesPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: moduleIndex, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rangeStart, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rangeEnd, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: resultsFinalizationTime, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isFinal, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: segments, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: alternatives, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: speechDetected, hasher: &hasher)
  }

  public var description: String {
    return "AnalyzerResultMessage(requestId: \(String(describing: requestId)), moduleIndex: \(String(describing: moduleIndex)), rangeStart: \(String(describing: rangeStart)), rangeEnd: \(String(describing: rangeEnd)), resultsFinalizationTime: \(String(describing: resultsFinalizationTime)), isFinal: \(String(describing: isFinal)), text: \(String(describing: text)), segments: \(String(describing: segments)), alternatives: \(String(describing: alternatives)), speechDetected: \(String(describing: speechDetected)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AuthorizationStatusMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TaskHintMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AudioSourceKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ModuleKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SpeechTranscriberPresetMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DictationPresetMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TranscriptionOptionMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ReportingOptionMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ResultAttributeOptionMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ContentHintMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SensitivityLevelMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ModelRetentionMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 141:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TaskPriorityMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 142:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AssetStatusMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 143:
      return TranscriptionSegmentMessage.fromList(self.readValue() as! [Any?])
    case 144:
      return ErrorMessage.fromList(self.readValue() as! [Any?])
    case 145:
      return AudioFormatMessage.fromList(self.readValue() as! [Any?])
    case 146:
      return RecognizerInfoMessage.fromList(self.readValue() as! [Any?])
    case 147:
      return RecognitionRequestMessage.fromList(self.readValue() as! [Any?])
    case 148:
      return TranscriptionMessage.fromList(self.readValue() as! [Any?])
    case 149:
      return RecognitionMetadataMessage.fromList(self.readValue() as! [Any?])
    case 150:
      return RecognitionResultMessage.fromList(self.readValue() as! [Any?])
    case 151:
      return ModuleConfigMessage.fromList(self.readValue() as! [Any?])
    case 152:
      return AnalyzerOptionsMessage.fromList(self.readValue() as! [Any?])
    case 153:
      return AnalysisRequestMessage.fromList(self.readValue() as! [Any?])
    case 154:
      return AnalyzerResultMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AuthorizationStatusMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? TaskHintMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AudioSourceKindMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ModuleKindMessage {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? SpeechTranscriberPresetMessage {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? DictationPresetMessage {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? TranscriptionOptionMessage {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReportingOptionMessage {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? ResultAttributeOptionMessage {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? ContentHintMessage {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? SensitivityLevelMessage {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? ModelRetentionMessage {
      super.writeByte(140)
      super.writeValue(value.rawValue)
    } else if let value = value as? TaskPriorityMessage {
      super.writeByte(141)
      super.writeValue(value.rawValue)
    } else if let value = value as? AssetStatusMessage {
      super.writeByte(142)
      super.writeValue(value.rawValue)
    } else if let value = value as? TranscriptionSegmentMessage {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? ErrorMessage {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? AudioFormatMessage {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? RecognizerInfoMessage {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? RecognitionRequestMessage {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? TranscriptionMessage {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? RecognitionMetadataMessage {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? RecognitionResultMessage {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? ModuleConfigMessage {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? AnalyzerOptionsMessage {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? AnalysisRequestMessage {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? AnalyzerResultMessage {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Always available.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppleSpeechPlatformApi {
  /// Whether the Speech framework is available (`SFSpeechRecognizer`).
  func isSupported() throws -> Bool
  /// Whether `SpeechAnalyzer` is available (iOS/macOS 26+).
  func isAnalyzerSupported() throws -> Bool
  /// Whether iOS/macOS 27 additions are available.
  func isVersion27Supported() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppleSpeechPlatformApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AppleSpeechPlatformApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppleSpeechPlatformApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether the Speech framework is available (`SFSpeechRecognizer`).
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechPlatformApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// Whether `SpeechAnalyzer` is available (iOS/macOS 26+).
    let isAnalyzerSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechPlatformApi.isAnalyzerSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAnalyzerSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAnalyzerSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAnalyzerSupportedChannel.setMessageHandler(nil)
    }
    /// Whether iOS/macOS 27 additions are available.
    let isVersion27SupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechPlatformApi.isVersion27Supported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isVersion27SupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isVersion27Supported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isVersion27SupportedChannel.setMessageHandler(nil)
    }
  }
}
/// Registered when the Speech framework can be imported.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppleSpeechHostApi {
  func speechAuthorizationStatus() throws -> AuthorizationStatusMessage
  func requestSpeechAuthorization() async throws -> AuthorizationStatusMessage
  func microphoneAuthorizationStatus() throws -> AuthorizationStatusMessage
  func requestMicrophoneAuthorization() async throws -> AuthorizationStatusMessage
  func recognizerSupportedLocales() async throws -> [String]
  /// Null when no recognizer exists for [locale].
  func recognizerInfo(locale: String?) async throws -> RecognizerInfoMessage?
  /// Starts recognition; results arrive through the callback API.
  func startRecognition(request: RecognitionRequestMessage) async throws
  func speechTranscriberIsAvailable() throws -> Bool
  func supportedLocales(kind: ModuleKindMessage) async throws -> [String]
  func installedLocales(kind: ModuleKindMessage) async throws -> [String]
  func supportedLocaleEquivalent(kind: ModuleKindMessage, locale: String) async throws -> String?
  func assetStatus(modules: [ModuleConfigMessage]) async throws -> AssetStatusMessage
  /// Downloads and installs assets; returns false when nothing was needed.
  /// Progress arrives through `onInstallProgress`.
  func installAssets(requestId: Int64, modules: [ModuleConfigMessage]) async throws -> Bool
  func reservedLocales() async throws -> [String]
  func maximumReservedLocales() throws -> Int64
  func reserveLocale(locale: String) async throws -> Bool
  func releaseLocale(locale: String) async throws -> Bool
  func bestAvailableAudioFormat(modules: [ModuleConfigMessage]) async throws -> AudioFormatMessage?
  /// Starts an analysis; results arrive through the callback API.
  func startAnalysis(request: AnalysisRequestMessage) async throws
  func endModelRetention() async throws
  /// Ends live input (stops the microphone) and finalizes the results.
  func finishRequest(requestId: Int64) throws
  /// Cancels a request. No further events are sent for it.
  func cancelRequest(requestId: Int64) throws
  /// Cancels every request; returns how many were active.
  func cancelAll() throws -> Int64
  func activeRequestCount() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppleSpeechHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AppleSpeechHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppleSpeechHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let speechAuthorizationStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.speechAuthorizationStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      speechAuthorizationStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.speechAuthorizationStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      speechAuthorizationStatusChannel.setMessageHandler(nil)
    }
    let requestSpeechAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.requestSpeechAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestSpeechAuthorizationChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestSpeechAuthorization()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestSpeechAuthorizationChannel.setMessageHandler(nil)
    }
    let microphoneAuthorizationStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.microphoneAuthorizationStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      microphoneAuthorizationStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.microphoneAuthorizationStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      microphoneAuthorizationStatusChannel.setMessageHandler(nil)
    }
    let requestMicrophoneAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.requestMicrophoneAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMicrophoneAuthorizationChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestMicrophoneAuthorization()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestMicrophoneAuthorizationChannel.setMessageHandler(nil)
    }
    let recognizerSupportedLocalesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.recognizerSupportedLocales\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recognizerSupportedLocalesChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.recognizerSupportedLocales()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      recognizerSupportedLocalesChannel.setMessageHandler(nil)
    }
    /// Null when no recognizer exists for [locale].
    let recognizerInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.recognizerInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recognizerInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localeArg: String? = nilOrValue(args[0])
        Task { @MainActor in
          do {
            let result = try await api.recognizerInfo(locale: localeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      recognizerInfoChannel.setMessageHandler(nil)
    }
    /// Starts recognition; results arrive through the callback API.
    let startRecognitionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.startRecognition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRecognitionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RecognitionRequestMessage
        Task { @MainActor in
          do {
            try await api.startRecognition(request: requestArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startRecognitionChannel.setMessageHandler(nil)
    }
    let speechTranscriberIsAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.speechTranscriberIsAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      speechTranscriberIsAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.speechTranscriberIsAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      speechTranscriberIsAvailableChannel.setMessageHandler(nil)
    }
    let supportedLocalesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.supportedLocales\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      supportedLocalesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let kindArg = args[0] as! ModuleKindMessage
        Task { @MainActor in
          do {
            let result = try await api.supportedLocales(kind: kindArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      supportedLocalesChannel.setMessageHandler(nil)
    }
    let installedLocalesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.installedLocales\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      installedLocalesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let kindArg = args[0] as! ModuleKindMessage
        Task { @MainActor in
          do {
            let result = try await api.installedLocales(kind: kindArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      installedLocalesChannel.setMessageHandler(nil)
    }
    let supportedLocaleEquivalentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.supportedLocaleEquivalent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      supportedLocaleEquivalentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let kindArg = args[0] as! ModuleKindMessage
        let localeArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.supportedLocaleEquivalent(kind: kindArg, locale: localeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      supportedLocaleEquivalentChannel.setMessageHandler(nil)
    }
    let assetStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.assetStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      assetStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modulesArg = args[0] as! [ModuleConfigMessage]
        Task { @MainActor in
          do {
            let result = try await api.assetStatus(modules: modulesArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      assetStatusChannel.setMessageHandler(nil)
    }
    /// Downloads and installs assets; returns false when nothing was needed.
    /// Progress arrives through `onInstallProgress`.
    let installAssetsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.installAssets\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      installAssetsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let modulesArg = args[1] as! [ModuleConfigMessage]
        Task { @MainActor in
          do {
            let result = try await api.installAssets(requestId: requestIdArg, modules: modulesArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      installAssetsChannel.setMessageHandler(nil)
    }
    let reservedLocalesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.reservedLocales\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reservedLocalesChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.reservedLocales()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      reservedLocalesChannel.setMessageHandler(nil)
    }
    let maximumReservedLocalesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.maximumReservedLocales\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      maximumReservedLocalesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.maximumReservedLocales()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      maximumReservedLocalesChannel.setMessageHandler(nil)
    }
    let reserveLocaleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.reserveLocale\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reserveLocaleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localeArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.reserveLocale(locale: localeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      reserveLocaleChannel.setMessageHandler(nil)
    }
    let releaseLocaleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.releaseLocale\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseLocaleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localeArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.releaseLocale(locale: localeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseLocaleChannel.setMessageHandler(nil)
    }
    let bestAvailableAudioFormatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.bestAvailableAudioFormat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      bestAvailableAudioFormatChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modulesArg = args[0] as! [ModuleConfigMessage]
        Task { @MainActor in
          do {
            let result = try await api.bestAvailableAudioFormat(modules: modulesArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      bestAvailableAudioFormatChannel.setMessageHandler(nil)
    }
    /// Starts an analysis; results arrive through the callback API.
    let startAnalysisChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.startAnalysis\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAnalysisChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! AnalysisRequestMessage
        Task { @MainActor in
          do {
            try await api.startAnalysis(request: requestArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAnalysisChannel.setMessageHandler(nil)
    }
    let endModelRetentionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.endModelRetention\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endModelRetentionChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.endModelRetention()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      endModelRetentionChannel.setMessageHandler(nil)
    }
    /// Ends live input (stops the microphone) and finalizes the results.
    let finishRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.finishRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      finishRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.finishRequest(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      finishRequestChannel.setMessageHandler(nil)
    }
    /// Cancels a request. No further events are sent for it.
    let cancelRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.cancelRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.cancelRequest(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRequestChannel.setMessageHandler(nil)
    }
    /// Cancels every request; returns how many were active.
    let cancelAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.cancelAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAllChannel.setMessageHandler { _, reply in
        do {
          let result = try api.cancelAll()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelAllChannel.setMessageHandler(nil)
    }
    let activeRequestCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_speech.AppleSpeechHostApi.activeRequestCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activeRequestCountChannel.setMessageHandler { _, reply in
        do {
          let result = try api.activeRequestCount()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      activeRequestCountChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AppleSpeechCallbackApiProtocol {
  @MainActor func onAnalyzerResult(result resultArg: AnalyzerResultMessage) async throws
  @MainActor func onRecognitionResult(result resultArg: RecognitionResultMessage) async throws
  @MainActor func onInstallProgress(requestId requestIdArg: Int64, fractionCompleted fractionCompletedArg: Double) async throws
  /// The request finished. For analyses, [lastSampleTime] is the end of the
  /// analyzed audio in seconds.
  @MainActor func onRequestDone(requestId requestIdArg: Int64, lastSampleTime lastSampleTimeArg: Double?) async throws
  @MainActor func onRequestError(requestId requestIdArg: Int64, error errorArg: ErrorMessage) async throws
}
class AppleSpeechCallbackApi: AppleSpeechCallbackApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  @MainActor func onAnalyzerResult(result resultArg: AnalyzerResultMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onAnalyzerResult\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([resultArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: AppleSpeechPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onRecognitionResult(result resultArg: RecognitionResultMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onRecognitionResult\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([resultArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: AppleSpeechPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onInstallProgress(requestId requestIdArg: Int64, fractionCompleted fractionCompletedArg: Double) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onInstallProgress\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([requestIdArg, fractionCompletedArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: AppleSpeechPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// The request finished. For analyses, [lastSampleTime] is the end of the
  /// analyzed audio in seconds.
  @MainActor func onRequestDone(requestId requestIdArg: Int64, lastSampleTime lastSampleTimeArg: Double?) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onRequestDone\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([requestIdArg, lastSampleTimeArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: AppleSpeechPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onRequestError(requestId requestIdArg: Int64, error errorArg: ErrorMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.apple_speech.AppleSpeechCallbackApi.onRequestError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([requestIdArg, errorArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: AppleSpeechPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
